### ISSUE TITLE
Incorrect amount of troops on outposts

### ISSUE THREAD

**Issue by l29ah** [freeorion/freeorion#3059] opened 2020-06-18 19:48 UTC
Bug Report
==========

Environment
-----------

@o01eg 's server, should be e352120

Description
-----------

Player `swaq` has evacuated all his planets, and the troops went to 13 on the outposts as expected. But three turns ago they've grown to 26 for some unknown reasons. Outposts of other players are at 13 as expected. The meter says bullshit:
![2020-06-18-224701_555x360_scrot](https://user-images.githubusercontent.com/31852/85065389-bf9a9f80-b1b5-11ea-88f1-59f8c6e8c5bf.png)

Expected Result
---------------

13 troops

Steps to reproduce
------------------

dunno

**Comment by o01eg** [comment] 2020-06-18 20:34
Looks like his troops aren't affected by outpost effect.

**Comment by geoffthemedio** [comment] 2020-06-18 23:01
As far as I can tell, the output troop effect would come from [this script](https://github.com/freeorion/freeorion/blob/master/default/scripting/species/common/troops.macros#L67) which is included into various species through some macros. If there are no valid source objects that actually exist, but your client thinks there is one due to visibility limitations, maybe that could cause this? Not sure why this would happen unless there are also no ships in the empire.

Might help to move the effect to a tech so that it doesn't depend on a planet with population being owned by the empire, if that's the case...

**Comment by o01eg** [comment] 2020-06-19 05:32
>  If there are no valid source objects that actually exist, but your client thinks there is one due to visibility limitations, maybe that could cause this?

@geoffthemedio  Is there something that couldn't be seen by L29Ah's empire that cause this effect no being applied to swaq's outposts?

**Comment by geoffthemedio** [comment] 2020-06-19 10:08
Player B's empire seeing or not seeing something wouldn't cause the server effects evaluation to do anything different to player A's empire.

But if player B previously observed some objects that player A owned that could act as a source for an effect, but player B now doesn't know that those objects have been destroyed or otherwise changed since player B last had visibility of them, then player B's client might think that those those objects could act as a source for an effect. Player B's client would then calculate effects accounting for player A's outpost assuming that those source objects still exist. But on the server, no such object exists, and thus the effect isn't applied. The final meter totals that the server calculates are sent to player B, but these don't match what player B's client expects based on what player B has observed in the universe, so there is then an "unknown" contribution to the meter accounting for player A's objects in player B's client.

If that's what's happening, the "unknown" effect in the accounting in player A's client is working as intended and the problem is the script being set up in a way that leads to the discrepancy for other empires that don't know what object will be used as a source for the effects. A reasonable solution might be to move the outpost effect out of species and into a tech that all empires start with.

What does player A (swaq?) see for meter accounting for this outpost?

**Comment by agrrr3** [comment] 2020-06-19 10:17
Swaq evacuated all planets, so there is no species to 50% the troops?
..that would be the main bug.
Does swaq still have some ship/planet with species or not?

 If your client has a sensor ghost of a  swaq species (planet or ship) it
would calculate with the 50% applied

**Comment by Oberlus** [comment] 2020-06-19 10:48
Swaq has evacuated all planets.
The outposts should have 50% troops from being outposts (without species).

If there was a species, then it would not have the 50% troops applied.

**Comment by agrrr3** [comment] 2020-06-19 11:29
That 50% is a species effect. You need at least one species in your
*empire* to trigger it. This should be a either a tech effect or the
OwnedBy condition should be dropped/changed

**Comment by o01eg** [comment] 2020-06-19 15:12
> What does player A (swaq?) see for meter accounting for this outpost?

@geoffthemedio  Moderator sees only Bunker Complex and Fortification Network.

I suppose it could be caused because he nullified his entire population.

**Comment by geoffthemedio** [comment] 2020-06-19 20:42
> I suppose it could be caused because he nullified his entire population.

Does he still have ships?

**Comment by geoffthemedio** [comment] 2020-06-19 22:34
That would explain it then.

**Comment by o01eg** [comment] 2020-06-21 06:54
I suppose without population and ships the empire could be considered eliminated. But it still could build exobot colony if it has enought PP in stockpile.

**Comment by Oberlus** [comment] 2020-06-21 10:07
> I suppose without population and ships the empire could be considered eliminated. But it still could build exobot colony if it has enought PP in stockpile.

Or an ally could gift a colony.

**Comment by Voker57** [comment] 2020-06-21 16:00
> > I suppose without population and ships the empire could be considered eliminated. But it still could build exobot colony if it has enought PP in stockpile.
> 
> Or an ally could gift a colony.

Technically, all this could happen, but I'd consider the empire losing its sovereignity and ability to exist as a separate entity after no populated planets are controlled. So I propose this should be put as a condition of forced concession.

**Comment by Oberlus** [comment] 2020-06-21 17:27
> > > I suppose without population and ships the empire could be considered eliminated. But it still could build exobot colony if it has enought PP in stockpile.
> > 
> > 
> > Or an ally could gift a colony.
> 
> Technically, all this could happen, but I'd consider the empire losing its sovereignity and ability to exist as a separate entity after no populated planets are controlled. So I propose this should be put as a condition of forced concession.

That's out of the scope of this issue (I guess a feature request).
Also, the effect of concession is also arguably bad for MP gameplay: since the outposts (or colonies for the matter) become unowned and so lose al techs, they become much easier to invade, giving advantage to the empires nearby. Solving this particular issue as asked by players like @l29ah, i.e. giving control of the empire to an AI (and hence conserving the techs that would make outposts keep their, e.g., 26 troops), would not solve the OP issue.

**Comment by Voker57** [comment] 2020-06-21 18:00
> > > > I suppose without population and ships the empire could be considered eliminated. But it still could build exobot colony if it has enought PP in stockpile.
> > > 
> > > 
> > > Or an ally could gift a colony.
> > 
> > 
> > Technically, all this could happen, but I'd consider the empire losing its sovereignity and ability to exist as a separate entity after no populated planets are controlled. So I propose this should be put as a condition of forced concession.
> 
> That's out of the scope of this issue (I guess a feature request).
> Also, the effect of concession is also arguably bad for MP gameplay: since the outposts (or colonies for the matter) become unowned and so lose al techs, they become much easier to invade, giving advantage to the empires nearby. Solving this particular issue as asked by players like @l29ah, i.e. giving control of the empire to an AI (and hence conserving the techs that would make outposts keep their, e.g., 26 troops), would not solve the OP issue.

That was even further out of scope. And I don't think that's bad, seeking to destroy all populated planets to make invasion of outposts easier is valid gameplay element. Also, since having outposts but no populated planets was not considered in the script, maybe surviving extinction is a bug?

**Comment by Oberlus** [comment] 2020-06-21 18:48
So you mean you don't like L29Ah idea of giving conceded empires to an AI, right?

> since having outposts but no populated planets was not considered in the script, maybe surviving extinction is a bug?

I don't think so. The bug is that it wasn't considered by the script.

**Comment by Voker57** [comment] 2020-06-21 21:18
Concession discussion continued in https://freeorion.org/forum/viewtopic.php?f=6&t=11708

**Comment by Vezzra** [comment] 2020-06-23 17:35
For 0.4.10, personally I strongly prefer the simplest fix/workaround possible for this issue, that touches as few other aspects/mechanics/elements of the game as possible.

Post release more thorough fixes can be applied. So, if this can be fixed for 0.4.10 without changing the current conditions for when an empire is considered eliminated, IMO that would be preferrable. I just want to avoid changes that might trigger the need for more changes to get things right at this point in the release cycle...

**Comment by geoffthemedio** [comment] 2020-06-23 20:38
In addition to @Vezzra's point, the solution to this issue should not depend on avoiding the specific situational cause involving defeated or self-destructed empires.

**Comment by o01eg** [comment] 2020-07-01 07:27
I suppose it was fixed in #3085

**Closed as completed by o01eg** 2020-07-01 07:27 UTC
Labels: category:bug, component:content scripting, status:resolved
