### ISSUE TITLE
Meter growth tooltip doesn't display non-effect-based fuel regeneration

### ISSUE THREAD

**Issue by MatGB** [freeorion/freeorion#839] opened 2016-08-05 15:17 UTC
Prime example being Force Energy Structures, the correct amendments to the stats are applied each turn, but the hover text just says +1/-1 regardless, it would be better to not have that text than have it display wrongly for a lot of each game, but even better would be for it to work correctly.

This is a backend/UI bug not a scripting problem as far as I can see.

**Comment by geoffthemedio** [comment] 2016-08-06 00:22
I think the "always" is unnecessary in the title...

**Comment by l29ah** [comment] 2016-08-09 13:09
Also it thinks that outposts will grow some production due to the industrial automation.

**Comment by geoffthemedio** [comment] 2016-08-24 07:33
Original issue should be fixed now, but in doing so, a smaller similar / related issue with ship/fleet fuel regen display was created.

**Comment by dbenage-cx** [comment] 2017-02-21 04:07
Fixed? Regen is showing here

**Comment by Vezzra** [comment] 2017-02-22 10:29
Confirmed on OSX, normal regen showing up in the tooltip here too. Strange... why does this work all of a sudden?

Anyway, can anyone on Windows confirm this too?

**Comment by MatGB** [comment] 2017-02-23 14:14
Aye, I cannot remember seeing a fix for this go in but Force Energy Structures and fuel regeneration are both working properly as far as I can see.

**Comment by Vezzra** [comment] 2017-02-24 14:52
Well, seems to work on all platforms now, have just been able to confirm this myself.

Closing this as resolved.

**Closed as completed by Vezzra** 2017-02-24 14:52 UTC
Labels: category:bug, component:UI, status:resolved
