### ISSUE TITLE
Crashes when running Fedora package

### ISSUE THREAD

**Issue by subpop** [freeorion/freeorion#2182] opened 2018-06-26 03:31 UTC
### Environment
* **FreeOrion Version**: 0.4.7.1
* **Operating System**: Linux (Fedora 28)
* **Graphic card used**: Intel HD 520
* **Fetched as** 
  * Compiled from source

### Description
I am maintaining the FreeOrion in Fedora. I recently started receiving crash reports of a crash occurring immediately when running `/usr/bin/freeorion`. The message when crashing is:

```
/usr/include/c++/8/bits/stl_vector.h:950: std::vector<_Tp, _Alloc>::const_reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) const [with _Tp = float; _Alloc = std::allocator<float>; std::vector<_Tp, _Alloc>::const_reference = const float&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
```

From the stack trace reported on retrace.fedoraproject.org, it's passing through some font render related function calls. I checked my installed versions of DejaVu and Roboto fonts. I also ran `/usr/bin/freeorion --resource-dir ~/git/freeorion/data/default` and it still crashes, so it's not a problem with the system version of the fonts. Is there something else I should check? Freetype versions or Boost versions?

### Expected Result
I expect the game to simply launch. :)

### Steps to reproduce
* Install `freeorion` from the Fedora repository: `dnf install freeorion`
* Run `freeorion`

### Links
 * The spec file and related sources can be found on src.fedoraproject.org: https://src.fedoraproject.org/rpms/freeorion
* The stack trace for the crash has been captured by a crash tracer: https://retrace.fedoraproject.org/faf/reports/2087972/
* The bug report contains additional data about the system that reported the crash: https://bugzilla.redhat.com/show_bug.cgi?id=1575292

**Comment by dbenage-cx** [comment] 2018-06-26 05:45
I can reproduce from repo installed version ([bt](https://gist.github.com/dbenage-cx/edcdbfc5640c83b740db8a7e9b58296d)), but not from checking out v0.4.7.1 + cherry-pick c9b5b13.

Comparing build instructions (If unresolved, I'll try to go through these another day):
fedoraproject:
```
/usr/bin/c++  -DBOOST_ALL_DYN_LINK -DBOOST_ALL_NO_LINK -DBOOST_LOG_DYN_LINK -DENABLE_BINRELOC -DFREEORION_LINUX -DGiGi_EXPORTS -I/builddir/build/BUILD/src-tarball/GG -isystem /usr/include/freetype2  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -mcet -fcf-protection -DNDEBUG -fPIC   -Wall -std=c++11 -o CMakeFiles/GiGi.dir/src/GLClientAndServerBuffer.cpp.o -c /builddir/build/BUILD/src-tarball/GG/src/GLClientAndServerBuffer.cpp
```

local cmake:
```
/usr/lib64/ccache/c++  -DBOOST_ALL_DYN_LINK -DBOOST_ALL_NO_LINK -DBOOST_LOG_DYN_LINK -DENABLE_BINRELOC -DFREEORION_LINUX -DGiGi_EXPORTS -I/opt/projects/freeorion/GG -I/opt/projects/freeorion/build-4.7.1/GG -isystem /usr/include/freetype2  -O2 -DNDEBUG -fPIC   -Wall -std=c++11 -o CMakeFiles/GiGi.dir/src/GLClientAndServerBuffer.cpp.o -c /opt/projects/freeorion/GG/src/GLClientAndServerBuffer.cpp
```

I do not suspect the following is an issue here, but I do not have such warnings.
From the last [build log for freeorion-0.4.7.1-8.fc28.x86_64](https://kojipkgs.fedoraproject.org//packages/freeorion/0.4.7.1/8.fc28/data/logs/x86_64/build.log), there are multiple warnings for:
```
CMake Warning at /usr/share/cmake/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:153 (find_package)
```

**Comment by Dilvish-fo** [comment] 2018-06-26 05:56
I also feel constrained to point out that 0.4.7.1 is nearly a year old at this point, and itself was merely a bugfix release for a yet older version.  There have been quite a few changes to the code since then, including the commit dbenage-cx mentioned and  [at least one other font related safety check which seems potentially related](https://github.com/freeorion/freeorion/commit/4538457d3ee45b76bc6908af2f16c724530f9da8)

At this point we are right in the process of trying to wrap up 0.4.8.  So please try building the 0.4.8 branch.  The commit that dbenage-cx already mentioned is already in that branch.   If you nevertheless still have the same issue with it, perhaps there is some chance that the issue could get sorted out quickly enough  for the fix to make it into 0.4.8.

**Comment by subpop** [comment] 2018-06-26 05:56
So, that's an interesting data point then. We already pulled in c9b5b13 and [apply it](https://src.fedoraproject.org/rpms/freeorion/blob/master/f/fix_boost166.patch) during `%prep`. Is this a case of some compiler optimizations that don't happen during debug builds?

**Comment by subpop** [comment] 2018-06-26 05:58
I did try 0.4.8-rc1 actually; it still crashed. You can see the [scratch build here](https://koji.fedoraproject.org/koji/taskinfo?taskID=27803483).

**Comment by subpop** [comment] 2018-06-26 06:18
I backported https://github.com/freeorion/freeorion/commit/4538457d3ee45b76bc6908af2f16c724530f9da8 into another standalone patch and am running a scratch build including it [here](https://koji.fedoraproject.org/koji/taskinfo?taskID=27872628). When that build completes, it could be worth trying that RPM.

Edit: Seems the build still fails to run even with this patched.

**Comment by subpop** [comment] 2018-06-26 06:35
Fedora does seem to inject some compiler flags into `$CFLAGS` for builds. For example, on my local system:

```
rpmspec -E '%build_cxxflags' freeorion.spec
-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection
```

**Comment by dbenage-cx** [comment] 2018-06-26 22:29
Adding `GLIBCXX_ASSERTIONS` looks to be enough to reproduce

**Comment by subpop** [comment] 2018-06-27 04:13
The documentation around `_GLIBCXX_ASSERTIONS` makes it sound like a Good Thing:tm:. I can certainly just build the package without that flag, but it's been enabled by Fedora for a reason. Is the better fix to try and figure out why that assertion is getting tripped?

> Undefined by default. When defined, enables extra error checking in the form of precondition assertions, such as bounds checking in strings and null pointer checks when dereferencing smart pointers.

**Comment by dbenage-cx** [comment] 2018-06-27 04:52
I initially started down that path. https://github.com/dbenage-cx/freeorion/commit/06aaf63c241d8257aeecd71d282bb6e06dc4b50f allows the game to launch, but aborts on clicking Single Player.

The same message is displayed from stl_vector.h:950(via  [ListBox::Row::SetColumnStretches](https://github.com/freeorion/freeorion/blob/master/GG/src/ListBox.cpp#L482)).
Resolving that leads to another instance of same message via [GLClientAndServerBufferBase<float>::createServerBuffer](https://github.com/freeorion/freeorion/blob/master/GG/src/GLClientAndServerBuffer.cpp#L100).
Started to look like a never ending chase, but I'll continue to plug away this week.

This issue is relevant for current master as well.

**Comment by subpop** [comment] 2018-06-27 05:35
Oh interesting. So that assertion is tripping all over the place.

**Comment by Dilvish-fo** [comment] 2018-06-27 05:52
Looks like a bunch of great bugs to get squashed.  Go go dbenage-cx!

**Comment by dbenage-cx** [comment] 2018-06-28 05:28
@subpop If you wish to test, a set of modified patches for freeorion v0.4.7.1 is at https://github.com/freeorion/freeorion/compare/v0.4.7.1...dbenage-cx:fix-2182_backport-v0.4.7.1

**Comment by subpop** [comment] 2018-06-28 05:31
AWESOME! I will definitely apply those patches and give it a try.

**Comment by subpop** [comment] 2018-06-29 03:34
Confirmed. That patch set fixes the crash at startup.

**Comment by agrrr3** [comment] 2018-06-29 08:17
I did a compile with the patches; freeorion does start and you can start a game. But if you advance  a few turns the game crashes with some reference to serialization. Also loading savegames crashes it.

**Comment by Vezzra** [comment] 2018-06-29 11:51
@agrrr3, are all these crashes also because that same assertion gets triggered?

@subpop, do the patches only solve the crash at startup, and are you still getting crashes later on like @agrrr3 reported, or don't you get any crashes anymore with those patches applied?

**Comment by dbenage-cx** [comment] 2018-06-30 09:16
@agrrr3 @subpop thanks for testing, the save/load is related to boost 1.66. I added aa06d60 (based off of ce0ca5d from master)

**Comment by agrrr3** [comment] 2018-07-02 22:04
@dbenage-cx yes that commit seems to fix it

**Comment by subpop** [comment] 2018-07-03 05:00
@dbenage-cx I have some [positive votes](https://bodhi.fedoraproject.org/updates/FEDORA-2018-f566c3cfb1) in the Fedora update system too.

**Closed as completed** 2018-07-07 17:16 UTC
Labels: category:bug, status:resolved, component:internal
