### ISSUE TITLE
fleets getting stuck in starlanes

### ISSUE THREAD

**Issue by Voker57** [freeorion/freeorion#826] opened 2016-08-01 20:06 UTC
Sometimes, AI-controlled units get 'stuck' in starlanes, displaying ETA but never actually moving.

Save: http://dump.bitcheese.net/files/nanulyc/stuck.sav
Observe snowflake that is about to enter Saeros beta and end turn.

**Comment by dbenage-cx** [comment] 2016-08-01 21:40
This ship is not currently visible to the players empire (stealth of the ship is higher than the empire detection strength).  Objects that were previously visible are shaded (the thin black lines).
![stealth_monster](https://cloud.githubusercontent.com/assets/17205519/17309582/2f42e694-5805-11e6-9768-311c066806ab.png)

Not a bug, pre se, but commonly reported as needing a UI improvement.
There are many related forum threads, most recent: http://freeorion.org/forum/viewtopic.php?f=28&t=10061

**Comment by Voker57** [comment] 2016-08-01 21:52
I see. IIRC such ship ghosts also cause panic in xenophobics, but I don't have save handy.

**Comment by Vezzra** [comment] 2016-08-02 08:17
Ok, so that's another case of sensor ghost confusion. I agree, we need to address that at some point, but as far as this issue is concerned, we can close it.

**Closed as completed by Vezzra** 2016-08-02 08:17 UTC
Labels: category:bug, status:won't fix

**Comment by geoffthemedio** [comment] 2016-08-02 09:21
Are ghosted fleet icons not overdrawn with scanlines anymore? I think they were supposed to be / were at some point...

**Comment by MatGB** [comment] 2016-08-02 15:45
Scanlines are there—they're in the screenshot, but to a newish player there's zero other indication of what's going on and we're getting lots of feedback indicating that as a UI solution it's not actually very good.

**Comment by l29ah** [comment] 2016-08-04 21:17
Actually i see dashes /under/ the ship icon :/

**Comment by Vezzra** [comment] 2016-08-05 16:43
Screenshot?

**Comment by l29ah** [comment] 2016-08-05 16:54
The one that was posted there will do. On the map the scanlines don't cover the fleet icon.

**Comment by Vezzra** [comment] 2016-08-07 12:48
Oh, you're referring to the fleet icon on the map... are they scanlined at all? Never paid attention to that, but regardless, it's right, there should be some clear visual indication if a fleet icon on the map represents a scan ghost.
