### ISSUE TITLE
Multiplayer: Planet with 65536 Stealth.

### ISSUE THREAD

**Issue by clgillis** [freeorion/freeorion#1923] opened 2017-12-17 20:27 UTC
Issue:
I have a system in a game where I cannot put an outpost on one of the 3 systems.  It shows a Stealth of 65536 which seems a bit out of whack.  This was noticed on turn 62 of the game after a outpost base was built.  Logs and save file attached.

### Environment
Connecting to a remote host for a multiplayer game.  1 human + 4 AI.

Host is Windows 2008 64bit
Client is Windows 7 64bit
FreeOrion Version(both Host and Client): v0.4.7+ [Build 2017-12-11.05ee54a] MSVC 2015

[freeorion.zip](https://github.com/freeorion/freeorion/files/1566013/freeorion.zip)

**Comment by Vezzra** [comment] 2017-12-19 12:39
That's not a bug, just a weird way to display that a planet has *unknown* stealth (due to its stealth being higher than your detection strength). Could probably be improved by displaying "unknown" instead of that magic 65536 number.

Anyway, works as intended, so I'm closing this.

**Closed as completed by Vezzra** 2017-12-19 12:39 UTC
Labels: category:bug, status:invalid, component:internal
