### ISSUE TITLE
Player Status (Playing, Turn Done) in Empire View Missing

### ISSUE THREAD

**Issue by Dpunkt** [freeorion/freeorion#1069] opened 2016-10-24 19:49 UTC
After Upgrading from 4.5 to 4.6 i missed the Player Status in the Empire View.
I do not know if this Information was removed for a purpose (see this as Feature request) or is missing without reason (bug).

I played together with a friend, i am using Win7 and the prebuild binary. he is using Linux with the game self compiled. Both of us are missing this Feature, since it contributes to the game flow.

**Comment by geoffthemedio** [comment] 2016-10-24 19:58
What "player status" are you referring to?

Is the window just not wide enough by default on your monitor? (It can be resized)

**Comment by Dpunkt** [comment] 2016-10-24 20:04
Resizing fixed this.
With missing left-right-Scrollbars we both did not get the idea to resize the window.
Improvment: Add Scrollbars

**Comment by Vezzra** [comment] 2016-10-30 11:03
Adding scrollbars sounds like a reasonable idea. @Dpunkt, can you open a separate feature request issue for this?

Then we can close this issue here, I suppose as "works for me"?

**Comment by geoffthemedio** [comment] 2016-10-30 11:07
Due to some quirks with ListBox, adding horizontal scrollbars might be difficult. Same reason there aren't any on the FleetWnd or ObjectListWnd.

**Comment by Dpunkt** [comment] 2016-10-30 11:19
Scrollbars were just a quick idea how to shuw the Player that there is Information hidden. 
If  you have trouble implementing it, showing "hidden content" by other means (eg an three dot icon, with mouseover hint) in the window  would serve the same purpose.

**Comment by Vezzra** [comment] 2017-02-12 15:24
Closing this as "works for me", as the original issue as described in the OP actually works as intended.

The actual problem is that the player status window might be too small to display all columns, which is a different matter. If someone thinks that an issue should be opened for that, feel free to do so.

**Closed as completed by Vezzra** 2017-02-12 15:24 UTC
Labels: component:UI, status:works for me, category:tweak
