### ISSUE TITLE
No star fields seen when zoomed out, stars are intermittent when zoomed in

### ISSUE THREAD

**Issue by l29ah** [freeorion/freeorion#2648] opened 2019-11-17 07:04 UTC
### Environment

* **FreeOrion Version**: 9f541b0612bb4ae88c469ab4dd65e77df0a2133b
* **Operating System**: Gentoo GNU/Linux
* **Graphic card used**: Intel Corporation UHD Graphics 620 (rev 07)
* **Fetched as** 
  * Compiled from source

### Description
I can only see the stars clearly when only a handful of systems can fit my display. This sucks since star fields provide an important strategic cue regarding your position in the galaxy. I have to zoom in and move camera around much to obtain such an information now, esp. when playing with >150 systems.

Stars are clearly seen:
![](https://pstbin.ru/f/61078/)
Stars are barely there and show up and vanish when you move the camera around:
![](https://pstbin.ru/f/36438/)
No stars can be seen:
![](https://pstbin.ru/f/33099/)

### Expected Result
Stars clearly seen on all zoom levels or some other cues on the absolute position in the galaxy. Probably an option in settings that set the "size" of stars could do the job, or the stars scaling up with the player zooming out?

**Comment by Oberlus** [comment] 2019-11-17 10:13
This happens to me when using Linux (in my case Ubuntu 14 & 18, compiled from source) but not when using Windows (7 & 8.1, release & weekly test builds). In Windows all white dots are always drawed.
Never tried a Linux binary version.

**Comment by geoffthemedio** [comment] 2019-11-17 10:43
Stars are rendered as point sprites, and how those are rendered is more-or-less dependent on the driver / graphics card, so may not work the same between different systems. The zooming of the starfields is done with an overall zoom factor in the view matrix, which also scales the point sprites, which interacts with the point size set when rendering the points:

https://github.com/freeorion/freeorion/blob/master/UI/MapWnd.cpp#L1877

can be changed to have different, or no, scaling, or a different minimum or maximum, like:

`glPointSize(std::max(1.0, 2*std::sqrt(ZoomFactor())));`

Alternatively, the background starfield rendering could be re-implemented with a shader instead of the fixed pipeline calls.

Some degree of scaling is generally needed though, as otherwise when zoomed out, it gets rather cluttered...
![Big Starsfield](https://user-images.githubusercontent.com/11386908/69006560-d4b60400-0930-11ea-8c96-cd6d2355513b.png)

**Comment by Oberlus** [comment] 2019-11-17 11:04
> Stars are rendered as point sprites, and how those are rendered is more-or-less dependent on the driver / graphics card

I bet it's the driver more than the graphics card. 
I've tested in a laptop with Ubuntu 18 and Windows 8.1, graphics card nvidia GTX 860M, and in a PC with Windows 7 and Nvidia GTX 560Ti.
Linux does the intermittent points while windows on the same machine (and in a different one) doesn't.
For me, the problem is not the scaling, or at least not for Windows, that does the scaling without hiding any of the points. The points do appear and dissappear as you move the background, so it is somehow filtering them to show you only a few at any given position.

The workaround (in Linux) for me is to grab the background and move it in circles, so that the intermitency of the points when moving them allows to induce the more dense areas (the main body of the galaxy).

**Comment by geoffthemedio** [comment] 2019-11-17 11:08
> the blinking sprites

?

**Comment by Oberlus** [comment] 2019-11-17 11:09
> 
> 
> > the blinking sprites
> 
> ?

Edited my message (I meant the points)

**Comment by geoffthemedio** [comment] 2019-11-23 11:07
Hopefully resolved by https://github.com/freeorion/freeorion/commit/d0c68055a65032d38f054e68b6f2ac249cc17c61

**Closed as completed by geoffthemedio** 2019-11-23 11:07 UTC
Labels: component:UI, status:resolved, category:tweak
