### ISSUE TITLE
Combat not always initiated between planets and aggressive fleets

### ISSUE THREAD

**Issue by MatGB** [freeorion/freeorion#1618] opened 2017-06-28 17:49 UTC
### Environment

* **FreeOrion Version**:  Compiled from #1587  
* **Operating System**: Linux
  * Compiled from source

### Description
I've thought this was occasionally happening for a bit but hadn't found an example that was clear. Screenshot shows the problem, the previous turn two Yellow ships arrived and died, the next turn this ship arrived, debug data dump says it's on aggressive, but no combat or bombard is reported. That ship should be dead, but isn't. However, my system is still blockaded.

Autosaves for the previous turn and this, to see this happen it should be OK to simply hit end turn, can't guarantee combat won't happen.

### Expected Result
Combat should occur if there's an aggressive ship in system owned by a player other than planet owners.
[combat-failure.zip](https://github.com/freeorion/freeorion/files/1109671/combat-failure.zip)
[no-planet-combat.zip](https://github.com/freeorion/freeorion/files/1109670/no-planet-combat.zip)
![screenshot_20170628_183720](https://user-images.githubusercontent.com/11533206/27652081-54f6c9a0-5c32-11e7-8f6d-1590f9874bd0.png)

**Comment by LGM-Doyle** [comment] 2017-06-29 18:54
@MatGB I was unable to load the game.  Do you know specifically which commit you were playing from?  There have been changes in PR #1587 and also in `master` to the various parts of the save file format, so I'll need that in order to replicate the problem.  Also if you merged it with other branches, then I will probably need that branch posted.

Or if it is happening regularly, then just wait until it shows up in a game from `master`.

**Comment by MatGB** [comment] 2017-07-01 12:13
Probably best to wait till I find another instance but if you do want to try a complete mess of a branch, I put it up here:
[Commits · MatGB/freeorion](https://github.com/MatGB/freeorion/commits/add_design_wnd_library)

Several WIPs including yours mixed in, not at all surprising it didn't load in hindsight. Still, quitting that game now so I can start a fresh branch from master now we've got the design stuff merged in.

**Comment by LGM-Doyle** [comment] 2017-07-01 14:13
I'll wait.

I'll keep it in mind and if I find it while testing other things. I'll link the fix back here.

Does correct bombardment resume on the next turn?  Or is it a transient event that fixes itself on the next turn?

**Comment by MatGB** [comment] 2017-07-01 14:30
In this case the following turn combat happened as usual and the ships died, my initial reaction was that it wasn't set to aggressive hence the data dump which confirmed it was, combined with the established blockade.

**Comment by Dilvish-fo** [comment] 2017-08-27 00:23
I have now encountered this same problem, and my-oh-my, it is proving rather perplexing so far.  Loading the savegame from the turn right before the enemy ship arrives at Fox β properly results in combat (10 out of 10 tries) just as you'd expect (which was a rude surprise when trying to repeat the problem).  Luckily, loading the savegame from 2 turns before the enemy arrives does always cause the problem to repeat-- no combat on arrival (although the following turn another enemy ship arrives and that will still trigger combat).

I attach those two savefiles, although they were made with an altered setup I confirmed they are compatible with current master.  I also just pushed to master a commit which adds some more logging for combat conditions determination. Set your combat logging level to trace to get the apparently key info (so far) for this problem.  

Slight bit of background info: the subject system, Fox β, has three planets, one is unowned but defended by medium tech natives, another is owned and defended by the human player, and the third is empty/unowned.  All three simply have stealth at 5, and on turn 71 just before the enemy ship arrives it is visible in the starlane, it is armed and aggressive and does not appear to be subject to any detection range malus or anything else I can think of that would cause it problems.    Nevertheless, it turns out that (in the problem scenario) **when the enemy ship arrives on turn 72 it for some reason has only Basic Visibility of both of the occupied planets**, although it does have partial visibility of the unoccupied planet.
[1_turn_prior_combat_works.sav.zip](https://github.com/freeorion/freeorion/files/1254053/1_turn_prior_combat_works.sav.zip)
[2_turns_prior_combat_fails.sav.zip](https://github.com/freeorion/freeorion/files/1254054/2_turns_prior_combat_fails.sav.zip)

Besides the basic visibility problem, it's also quite perplexing that these two files will yield different results, every time, the turn 70 file always results in faulty visibility and no combat on turn 72, while the turn 71 file always results in proper visibility and combat on turn 72, with no other differences apparent.  And loading the turn 70 (combat failing) file, advancing a turn and then saving that will result in a file which, just like the other turn 71 file, always results in combat on turn 72.  I experience these problems in Ubuntu 16.04; testing of these files on other OS's would be appreciated.

**Comment by Dilvish-fo** [comment] 2017-08-27 00:28
A further tidbit-- just to double check the visibility malus issue, I loaded up turn 68 from that game, built supertesters, and confirmed that on turn 70 there is no ion cloud or other source of trouble in the area, nor any other kind of visibility malus applied to the arriving enemy (yet still, following that game forward to turn 72 the enemy still does not detect the target planets and there is no combat until turn 73.

**Comment by MatGB** [comment] 2017-08-27 00:36
I'd forgotten about this one, and yeah, having it not occur if you load the savegame from one turn but happen if you load the turn before is really weird and explains why replicating it was harder.

Could it be related to that (now fixed) bug about derelicts and similar not letting fleets be given orders to go through on the turn they're revealed? Timing of visibility reveal isn't something I'm at all hot on but it seems like a similar issue.

**Comment by Vezzra** [comment] 2017-08-27 11:19
> A further tidbit-- just to double check the visibility malus issue, I loaded up turn 68 from that game, built supertesters, and confirmed that on turn 70 there is no ion cloud or other source of trouble in the area, nor any other kind of visibility malus applied to the arriving enemy (yet still, following that game forward to turn 72 the enemy still does not detect the target planets and there is no combat until turn 73.

That check could have failed because of #1608. Meaning, apparently the Super Testers Detection Strength bonus is currently broken in master, so you might want to repeat that check with the fix applied which has been proposed in #1608.

**Comment by Dilvish-fo** [comment] 2017-08-27 17:49
> That check could have failed ... apparently the Super Testers Detection Strength bonus is currently broken in master, 

Hmm, no, that Issue was just wrong (and I've commented in it and closed it), and the detection strength issue discussed there wouldn't have affected my ability to see any ion clouds, I just needed the range.  And I am pretty sure I had built at my capital anyways, but just to be absolutely sure I checked again now with them built at my capital, confirmed that I had the detection bonus, and still could observe nothing that explained the odd trouble in this case.

**Comment by Dilvish-fo** [comment] 2017-08-28 00:32
And just to note one more potential cause ruled out-- settings threads to 1 (for server effects and then for all 3 groups) did not prevent the problem, still getting the odd Basic Visibility for the two occupied planets.

**Comment by Dilvish-fo** [comment] 2017-08-28 01:48
It would be appreciated if other folks could test out the two savefiles I posted above so we can get some insight on whether this problem is acting the same across platforms or is platform specific-- Mat and I are both on Ubuntu.

**Comment by Vezzra** [comment] 2017-08-28 11:13
> Hmm, no, that Issue was just wrong (and I've commented in it and closed it), and the detection strength issue discussed there wouldn't have affected my ability to see any ion clouds, I just needed the range.

Alright, just wanted to make sure.

> It would be appreciated if other folks could test out the two savefiles I posted above so we can get some insight on whether this problem is acting the same across platforms or is platform specific-- Mat and I are both on Ubuntu.

I've already put that on my list, but, well, still on my trip... 😉

**Comment by geoffthemedio** [comment] 2017-08-28 12:32
> It would be appreciated if other folks could test out the two savefiles I posted above

My initial test gave consistent results... combat from the T-1 save, no combat from the T-2 save.

**Comment by LGM-Doyle** [comment] 2017-08-28 15:08
I think that the problem is that effect generated visibility changes are not cleared after they are applied.

Specifically when loading at T-2, the telepathic Derthrean on "Hewish β I" spot the inhabited planets in the "Fox β" system on T-2.  This grants basic visibility, which is then erroneously applied on turn T-1.

However when loading on T-1 the inhabited planets are already visible so the Derthrean telepathic effect is not generated.

I've posted PR #1708, which I think fixes the problem, by clearing the effects generated visibility changes after applying them.

**Comment by Dilvish-fo** [comment] 2017-08-28 18:43
You absolutely do appear to have identified the crux of the problem here (with the minor correction that  apparently Derthrean do not have telepathic detection,  it looks like it's only Trith that get it so it must be some Trith colony triggering this).   So that is great, thanks for digging into this.

1708 does fix this problem for me, but I have some concerns about it, which I guess I'll discuss there.

**Comment by LGM-Doyle** [comment] 2017-08-28 19:03
@Dilvish-fo thanks for figuring out the strangeness of the two turn run up to the non-combat.  Having a good and bad test case meant that I could just pile debuging on until even the telepaths could not hide.  Using a save from two turns back was not the obvious thing to try.

**Closed as completed** 2017-09-01 06:19 UTC
Labels: category:bug, component:game mechanic, status:resolved, component:internal
