### ISSUE TITLE
Unable to use the small troop ship design in the multiplayer game

### ISSUE THREAD

**Issue by l29ah** [freeorion/freeorion#2107] opened 2018-05-16 10:34 UTC
### Environment
* **FreeOrion Version**: https://github.com/Voker57/freeorion/tree/teamsmac-14.6.2
* **Operating System**: Linux
* **Fetched as** 
  * Compiled from source

### Description
Player L29Ah can't have the small troop ship design. It is not in the design list, yet when i try to create it, it won't let me to, saying it's a duplicate. No obsolete designs. May be related to https://github.com/freeorion/freeorion/issues/2099

https://dump.bitcheese.net/files/cururij/lvn.mps

**Comment by geoffthemedio** [comment] 2018-05-17 09:28
Possible workaround...

Make these changes, recompile, then use the shown command. Should add designs back to your displayed list. Hopefully future turns will work without the change.

![before_and_after](https://user-images.githubusercontent.com/11386908/40169081-745ba4be-59c5-11e8-88e4-247edd773e6d.png)

````
diff --git a/default/stringtables/en.txt b/default/stringtables/en.txt
index c112aaad9..48c5c9915 100644
--- a/default/stringtables/en.txt
+++ b/default/stringtables/en.txt
@@ -4257,6 +4257,9 @@ Add All Saved Designs to Empire now
 DESIGN_WND_ADD_ALL_SAVED_START
 Add All Saved Designs at Game Start
 
+ADD_ALL_DEFAULT_DESIGNS
+Add All Default Designs Now
+
 DESIGN_WND_ADD_ALL_DEFAULT_START
 Add All Default Designs at Game Start
 

diff --git a/UI/DesignWnd.cpp b/UI/DesignWnd.cpp
index 41ec67df9..8193d2cf2 100644
--- a/UI/DesignWnd.cpp
+++ b/UI/DesignWnd.cpp
@@ -2995,6 +2995,22 @@ void CompletedDesignsListBox::BaseRightClicked(GG::ListBox::iterator it, const G
         GetOptionsDB().Set<bool>("resource.shipdesign.default.enabled", !add_defaults);
     };
 
+    auto* design_manager = ClientUI::GetClientUI()->GetShipDesignManager();
+    auto add_default_designs_now = [&empire_id, &design_manager, this]() {
+        DebugLogger() << "Add default designs to empire";
+        if (empire_id == ALL_EMPIRES || empire_id != HumanClientApp::GetApp()->EmpireID())
+            return;
+        auto* empire = GetEmpire(empire_id);
+        const auto& ids = empire->ShipDesigns();
+        std::set<int> ordered_ids(ids.begin(), ids.end());
+
+        auto displayed_designs = dynamic_cast<CurrentShipDesignManager*>(design_manager->CurrentDesigns());
+        if (!displayed_designs)
+            return;
+
+        displayed_designs->InsertOrderedIDs(ordered_ids);
+        Populate();
+    };
 
     // create popup menu with a commands in it
     auto popup = GG::Wnd::Create<CUIPopupMenu>(pt.x, pt.y);
@@ -3021,6 +3037,8 @@ void CompletedDesignsListBox::BaseRightClicked(GG::ListBox::iterator it, const G
     popup->AddMenuItem(GG::MenuItem(true)); // separator
     popup->AddMenuItem(GG::MenuItem(UserString("DESIGN_WND_ADD_ALL_DEFAULT_START"), false, add_defaults,
                                     toggle_add_default_designs_at_game_start_action));
+    popup->AddMenuItem(GG::MenuItem(true)); // separator
+    popup->AddMenuItem(GG::MenuItem(UserString("ADD_ALL_DEFAULT_DESIGNS"), false, false, add_default_designs_now));
 
     popup->Run();
 }
````

**Comment by l29ah** [comment] 2018-05-17 10:20
```
[ 75%] Building CXX object CMakeFiles/freeorion.dir/UI/DesignWnd.cpp.o
/home/l29ah/projects/freeorion-teamsmac/UI/DesignWnd.cpp: In member function ‘virtual void CompletedDesignsListBox::PopulateCore()’:
/home/l29ah/projects/freeorion-teamsmac/UI/DesignWnd.cpp:2650:20: warning: unused variable ‘empire’ [-Wunused-variable]
     if (const auto empire = GetEmpire(EmpireID())) {
                    ^
/home/l29ah/projects/freeorion-teamsmac/UI/DesignWnd.cpp: At global scope:
/home/l29ah/projects/freeorion-teamsmac/UI/DesignWnd.cpp:2931:38: error: ‘empire_id’ was not declared in this scope
     auto add_default_designs_now = [&empire_id, &design_manager, this]() {
                                      ^
/home/l29ah/projects/freeorion-teamsmac/UI/DesignWnd.cpp:2931:50: warning: capture of variable ‘design_manager’ with non-automatic storage duration
     auto add_default_designs_now = [&empire_id, &design_manager, this]() {
                                                  ^
/home/l29ah/projects/freeorion-teamsmac/UI/DesignWnd.cpp:2930:11: note: ‘ShipDesignManager* design_manager’ declared here
     auto* design_manager = ClientUI::GetClientUI()->GetShipDesignManager();
           ^
/home/l29ah/projects/freeorion-teamsmac/UI/DesignWnd.cpp:2931:66: error: invalid use of ‘this’ at top level
     auto add_default_designs_now = [&empire_id, &design_manager, this]() {
                                                                  ^
/home/l29ah/projects/freeorion-teamsmac/UI/DesignWnd.cpp: In lambda function:
/home/l29ah/projects/freeorion-teamsmac/UI/DesignWnd.cpp:2933:13: error: ‘empire_id’ was not declared in this scope
         if (empire_id == ALL_EMPIRES || empire_id != HumanClientApp::GetApp()->EmpireID())
             ^
/home/l29ah/projects/freeorion-teamsmac/UI/DesignWnd.cpp:2935:34: error: ‘empire_id’ was not declared in this scope
         auto* empire = GetEmpire(empire_id);
                                  ^
/home/l29ah/projects/freeorion-teamsmac/UI/DesignWnd.cpp:2944:18: error: ‘Populate’ was not declared in this scope
         Populate();
                  ^
```

**Comment by geoffthemedio** [comment] 2018-05-17 11:59
Make sure you have the latest master? `empire_id` is defined there https://github.com/freeorion/freeorion/blob/master/UI/DesignWnd.cpp#L2954. Updated patch:
````
 UI/DesignWnd.cpp | 19 +++++++++++++++++++
 1 file changed, 19 insertions(+)

diff --git a/UI/DesignWnd.cpp b/UI/DesignWnd.cpp
index 41ec67df9..61797ca33 100644
--- a/UI/DesignWnd.cpp
+++ b/UI/DesignWnd.cpp
@@ -2995,6 +2995,22 @@ void CompletedDesignsListBox::BaseRightClicked(GG::ListBox::iterator it, const G
         GetOptionsDB().Set<bool>("resource.shipdesign.default.enabled", !add_defaults);
     };
 
+    auto* design_manager = ClientUI::GetClientUI()->GetShipDesignManager();
+    auto add_default_designs_now = [&empire_id, &design_manager, this]() {
+        DebugLogger() << "Add default designs to empire";
+        if (empire_id == ALL_EMPIRES || empire_id != HumanClientApp::GetApp()->EmpireID())
+            return;
+        auto* empire = GetEmpire(empire_id);
+        const auto& ids = empire->ShipDesigns();
+        std::set<int> ordered_ids(ids.begin(), ids.end());
+
+        auto displayed_designs = dynamic_cast<CurrentShipDesignManager*>(design_manager->CurrentDesigns());
+        if (!displayed_designs)
+            return;
+
+        displayed_designs->InsertOrderedIDs(ordered_ids);
+        Populate();
+    };
 
     // create popup menu with a commands in it
     auto popup = GG::Wnd::Create<CUIPopupMenu>(pt.x, pt.y);
@@ -3022,6 +3038,9 @@ void CompletedDesignsListBox::BaseRightClicked(GG::ListBox::iterator it, const G
     popup->AddMenuItem(GG::MenuItem(UserString("DESIGN_WND_ADD_ALL_DEFAULT_START"), false, add_defaults,
                                     toggle_add_default_designs_at_game_start_action));
 
+    popup->AddMenuItem(GG::MenuItem(true)); // separator
+    popup->AddMenuItem(GG::MenuItem(UserString("ADD_ALL_DEFAULT_DESIGNS"), false, false, add_default_designs_now));
+
     popup->Run();
 }
 ````

**Comment by dbenage-cx** [comment] 2018-06-25 00:49
Not arguing for escalation, this is not limited to multiplayer games:
* $ freeorion --resource.shipdesign.default.enabled 0
* Attempt to create a Comsat design (Colony Base hull with no part)

**Comment by Vezzra** [comment] 2018-06-25 10:08
Yep, confirmed, I can reproduce the issue following these steps. Looks like all predefined designs are affected. If you start a game without the predefined ship designs, you can't create any design that matches one of those.

Which basically renders the option to turn off the predefinded ship designs useless. Not game-breaking, so I won't block the release for this, but needs to be addressed of course.

**Comment by geoffthemedio** [comment] 2018-06-25 13:43
Yes; I spent a bit of time trying to figure out why this was happnening, and tried adding commands to add the designs later, or to change how they are removed / not added dependent on that option, but I didn't get it working.

**Comment by Dilvish-fo** [comment] 2018-06-25 16:40
Then it sounds to me that for 0.4.8 we should disable the option that disables the predefined designs.

**Comment by geoffthemedio** [comment] 2018-06-25 16:55
No objections.

**Comment by geoffthemedio** [comment] 2019-08-10 12:20
Hopefully fixed by commits picked from https://github.com/freeorion/freeorion/pull/2387

**Closed as completed by geoffthemedio** 2019-08-10 12:20 UTC
Labels: category:bug, component:UI, status:resolved
