### ISSUE TITLE
Can't Drop Ship Onto New Fleet Panel (Outside Home System?)

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#1474] opened 2017-04-08 10:04 UTC
Starting a new quickstart game, I can normally manipulate fleets in my home system. If I merge the ships into a single fleet and move it to the next system without closing and re-opening the fleets window, I can't drag-drop ships into a new fleet using the drop target on the fleets window. Moving the fleet, back to the home system, it works again. Splitting and re-forming the fleet doesn't seem to help. Closing and re-opening the fleets window seems to fix it, and reset which system the drag-drop works in to the current one.

**Comment by dbenage-cx** [comment] 2017-04-08 10:15
Can reproduce only if fleet window stays open.  Once it is closed and reopened, functionality is restored.

**Comment by LGM-Doyle** [comment] 2017-04-08 12:16
The problem was that the new fleet wnd target has a system id that is never updated to track the moving fleetwnd.  This is now fixed in master by https://github.com/freeorion/freeorion/commit/e9a82e6e6f7671a5320e731687f538d724b1ffc3

An additional oddity, is that parts of the code assume that you can also drop fleets on the new fleet drop target, but enough parts don't so that the new fleet drop target only works with ships.

Is this working as desired?

**Comment by geoffthemedio** [comment] 2017-04-08 12:31
dropping fleets onto new fleet target could make sense if you wanted to merge them, but not being able to do so is fine, I think...

**Closed as completed** 2017-04-08 12:41 UTC
Labels: category:bug, component:UI, status:resolved
