### ISSUE TITLE
Multi player lobby window layout glitches 

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion#940] opened 2016-08-31 19:03 UTC
### Environment
- **FreeOrion Version**: master
- **Operating System**: OSX
- **Graphic card used**: Intel HD Graphics 3000 512 MB
- **Fetched as**
  - Compiled from source
### Description

![multiplayerlobby](https://cloud.githubusercontent.com/assets/10279417/18142469/f3e506c4-6fbd-11e6-9cdb-7be5e2d1f124.png)

Apparently the multiplayer lobby does not adjust itself correctly to bigger font sizes. It has always been a bit cramped, but hasn't been that bad before the change of the default font size.

**Comment by Vezzra** [comment] 2016-08-31 19:06
I'm not sure if I should tag that for the release... on the one hand, it probably _should_ be fixed, as it's a rather prominently visible glitch, on the other hand, if it can't be fixed without too much trouble, I don't think it's worth to hold up the release for this. Opinions?

**Comment by adrianbroher** [comment] 2016-08-31 19:13
Is this caused by the new Roboto font? What about reversing that commit and postpone to 0.4.6 + 1 release?

Edit: Never mind, the PR isn't merged yet.

**Comment by Vezzra** [comment] 2016-08-31 19:42
It's caused by the increased default font size. Because I never use multiplayer, I only discovered this very recently.

**Comment by TheSilentOne1** [comment] 2016-09-01 12:46
I think the multiplayer setup screen could do without the galaxy graphic. That'd make some space.

**Comment by adrianbroher** [comment] 2016-09-04 11:34
Should this still be considered an issue? My screenshot uses stock configuration with Roboto.

![bildschirmfoto von 2016-09-04 13-32-50](https://cloud.githubusercontent.com/assets/84891/18230694/4446cfb0-72a4-11e6-8dfe-e0c81a529878.png)

**Comment by Vezzra** [comment] 2016-09-04 11:44
Looks like this in OSX now (also stock config with Roboto):

![multiplayerlobby2](https://cloud.githubusercontent.com/assets/10279417/18230743/7680115c-72a5-11e6-82c1-490da438a041.png)

Not release stopping, but should be addressed.

**Comment by Ouaz** [comment] 2016-09-04 16:07
W7, Roboto, default settings:

![mp_setup_en](https://cloud.githubusercontent.com/assets/11946570/18232171/4cf3e4a6-72ca-11e6-8b5d-c9059096aedd.PNG)

But with french language:

![mp_setup_fr](https://cloud.githubusercontent.com/assets/11946570/18232177/672153ea-72ca-11e6-8c60-138a13eda1b6.PNG)

Make the window resizeable should do the trick?

**Comment by geoffthemedio** [comment] 2016-09-04 16:32
It already is resizable in the latest build; you're apparently using an older version than @Vezzra or @adrianbroher as theirs have the resize tab at the bottom right that yours lacks.

The problem is to implement repositioning / size-dependent layout of the widgets in this window. Or just move it all to the right a bit.

**Comment by Vezzra** [comment] 2016-09-04 16:35
And the text in the dropdown input boxes should be clipped and not overwrite everything to the right.

**Comment by rrobgill** [comment] 2020-06-22 05:01
This seems to still be a problem on 0.4.10. 

Even though the window is resizeable, the galaxy settings doesn't shift into the available space when the window is enlarged, and the text still sits over the chatbox.

Before resize - (fontsizes 18/20):
![image](https://user-images.githubusercontent.com/35944068/85250161-53ce6600-b445-11ea-8802-df2b9034bd4e.png)

After resize:
![image](https://user-images.githubusercontent.com/35944068/85250191-647edc00-b445-11ea-8d48-c6fb4dce8d85.png)

**Closed as completed** 2020-06-22 15:02 UTC
Labels: category:bug, component:UI, status:resolved
