### ISSUE TITLE
persistent_config.xml is not applied after a version update

### ISSUE THREAD

**Issue by l29ah** [freeorion/freeorion#2815] opened 2020-03-31 18:02 UTC
### Environment

* **FreeOrion Version**: master
* **Operating System**: Gentoo GNU/Linux
  * Compiled from source

### Description

at configuration updates it first drops all the settings to default, then uses the settings, then only at the next start it will apply the persistent settings

### Expected Result
persistent_config.xml being always applied

**Comment by geoffthemedio** [comment] 2020-03-31 18:16
What does "at configuration updates" mean?

**Comment by l29ah** [comment] 2020-03-31 19:45
It happens when the version of freeorion that has written the configuration file is different from the version that is running now.

**Comment by Oberlus** [comment] 2020-04-01 07:26
Regardless of version changes that reset non-persistent configuration, we have another issue: server cookies are wiped out after disconnection (or just never saved), so the server asks for password again on each connection.
That is unacceptable because it quickly depletes the quota of the email service used to send the notifications and passwords and makes the server inaccessible.

@o01eg thinks this might be due to this issue, but I could open a new one if it's not the case.

**Comment by o01eg** [comment] 2020-04-01 07:55
Looks like it related to not saving default values. Language options are affected too.

**Comment by o01eg** [comment] 2020-04-01 07:59
@geoffthemedio 
I found how to simply reproduce it:
1. Open freeorion with non en locale environment. By default it get language from locale (ru). Close it.
2. String table in `config.xml` is set to `ru.txt`.
3. Open freeorion, edit config to en.txt. Close freeorion.
4. `config.xml` miss entries about stringtable.

**Comment by geoffthemedio** [comment] 2020-04-01 08:31
@o01eg What does "miss entries" mean? Perhaps "is missing", as in the en.txt value isn't written to the config file, even though it wasn't (to the user) the default value for that option?

I don't have a non-english locale environment to test with.

**Comment by o01eg** [comment] 2020-04-01 08:48
Yes, non-default for me `en.txt` value isn't written to config file, while default `ru.txt` value is written.

**Comment by geoffthemedio** [comment] 2020-04-01 08:56
I think that's due to some special handling for stringtable default value determination... For the OptionsDB, the "default" stringtable is always en.txt. The option's value automatically set to something else determined from the locale, though. I can probably fix that, but I don't think it's a good alternative test for the general issue reported here, due to how it's handled differently from other options.

**Comment by Oberlus** [comment] 2020-04-01 09:49
Could https://github.com/freeorion/freeorion/commit/8a687cbde09c21970aab24c5cbc69026aba5125d be the culprit?
Just guessing, because it is the only recent commit I can see in the history that touches config files.

**Comment by geoffthemedio** [comment] 2020-04-01 09:58
Yes and no. 8a687cb probably caused these issues to appear, but for stringtables specifically, the english stringtable en.txt is used as a backup stringtable for strings that the selected stringtable lacks, but is also used as the internal "default value" for the stringtable filename. So even if the program automatically selects ru.txt when starting up, it still keeps en.txt as the internal default value, which is checked to decide whether to output to options.xml.

**Comment by o01eg** [comment] 2020-04-01 10:00
@Oberlus Yes, but is was done to solve https://github.com/freeorion/freeorion/issues/2800 .

And stringtable is a complex issue because if someone changed default option from `<AppImage-temp-1>/.../stringtables/ru.txt` to `<AppImage-temp-1>/.../stringtables/en.txt` next launch it will fail because new correct value should be `<AppImage-temp-2>/.../stringtables/en.txt`.

Maybe this option should include only language name without path?

**Comment by geoffthemedio** [comment] 2020-04-01 10:16
> Maybe this option should include only language name without path?

Then you wouldn't be able to set the stringtable to another location outside of /default

I'll rewrite things to separate the concepts of fallback stringtable and default stringtable based on locale...

**Comment by o01eg** [comment] 2020-04-01 16:14
@geoffthemedio 
> Then you wouldn't be able to set the stringtable to another location outside of /default

What if split it into two options? The first is path to `stringtables` folder, and second one is language.

**Comment by geoffthemedio** [comment] 2020-04-01 16:25
would be rather complicated for the user...

**Comment by o01eg** [comment] 2020-04-01 16:30
He will see one field in UI. Split and restore will happen within code.

**Comment by geoffthemedio** [comment] 2020-04-04 14:52
> I'll rewrite things to separate the concepts of fallback stringtable and default stringtable based on locale...

Hopefully fixed by https://github.com/freeorion/freeorion/commit/77bb2ea79229ed59ac06eca59ba84bb63e9a8254

**Closed as completed** 2020-04-04 18:18 UTC
Labels: category:bug, status:resolved, component:internal
