### ISSUE TITLE
SitRep's vertical scrollbar hides text

### ISSUE THREAD

**Issue by Szunti** [freeorion/freeorion#365] opened 2015-10-01 09:46 UTC
When the vertical scrollbar appears the lines doesn't rewrap and the last character is partially under it.

**Comment by geoffthemedio** [comment] 2015-10-01 09:50
Could you attach a screenshot showing an example of what you mean?

The TextControl class doesn't have scrollbars, so I'm not sure what you're referring to.

**Comment by Szunti** [comment] 2015-10-01 10:07
![freeorion-scrollbar-hide](https://cloud.githubusercontent.com/assets/1443881/10218141/f270b0b8-6834-11e5-9a5f-d20035f5b59e.png)

**Comment by geoffthemedio** [comment] 2015-10-01 10:20
OK, the issue is that the layout in the situation report list hides the right edge of an entry under the vertical scrollbar.

**Comment by geoffthemedio** [comment] 2015-10-01 11:00
Added some extra padding, hopefully resolving this...

https://github.com/freeorion/freeorion/commit/39f508ccb502846950612b4a7e83be8dddcd21e3

**Comment by Szunti** [comment] 2015-10-01 12:33
I think the padding is ugly when the scrollbar is not there. Maybe force the scrollbar to always be there if you don't want to use that space anyway? And even with this padding the text border on right is still missing.

![freeorion-sitrep-scroll](https://cloud.githubusercontent.com/assets/1443881/10220658/6eae7d40-6849-11e5-9396-caebec7f2180.png)

**Closed as completed** 2015-10-01 18:24 UTC
Labels: category:bug
