### ISSUE TITLE
Building progress bar shows complete when at penultimate stage

### ISSUE THREAD

**Issue by MatGB** [freeorion/freeorion#1337] opened 2017-02-18 18:32 UTC
### Environment

* **FreeOrion Version**: #1334 rebased onto 99fb408
* **Operating System**: Linux
  * Compiled from source

### Description
Note: I've seen this in Master, the PR I'm testing is irrelevant but I didn't screenshot it before, thought it a glitch.

Basically, see picture
![spectacle n19226](https://cloud.githubusercontent.com/assets/11533206/23095819/3872d4e4-f608-11e6-9821-ab9d7e9ccea4.png)

The ship has a turn left to complete, the tooltip shows correct completion, but the progress bar shows complete, last box should be white.

### Expected Result
Last box of progress meter should be white not grey, to show it will complete.

### Steps to reproduce
Start game, queue item that takes at least 3 turns to complete, cycle two turns, look at prodwnd.

**Comment by dbenage-cx** [comment] 2017-02-19 03:52
1e12eb0 I have not been able to reproduce
![prod_queue](https://cloud.githubusercontent.com/assets/17205519/23099084/4935877e-f624-11e6-92bb-f64c429037b0.png)

**Comment by geoffthemedio** [comment] 2017-02-19 06:32
nor can I

**Comment by adrianbroher** [comment] 2017-02-19 08:43
Did you produce another item before the flux scout and the flux scout just happened to be 99.5% completed from leftover production (which could lead to an perceived full grey bar) while the the tooltip value floors the completion value to the previous full turn separator?

**Comment by MatGB** [comment] 2017-02-21 22:37
> Did you produce another item before the flux scout and the flux scout just happened to be 99.5% completed from leftover production (which could lead to an perceived full grey bar) while the the tooltip value floors the completion value to the previous full turn separator?

No, taken me a bit to replicate but see attached, zip is the autosave from 50% complete: maybe it needs a 4 turn+ item, or it's a weird bug with a premade, or something.
[FreeOrion_Mat_Cherry_0042_20170221_222450.sav.zip](https://github.com/freeorion/freeorion/files/791699/FreeOrion_Mat_Cherry_0042_20170221_222450.sav.zip)
![screenshot_scout-build-1](https://cloud.githubusercontent.com/assets/11533206/23188355/4e8b2f62-f886-11e6-9b03-81dd1d12d7d4.png)
![screenshot_scout-build-2](https://cloud.githubusercontent.com/assets/11533206/23188354/4e8abfe6-f886-11e6-8704-434f009a3b85.png)

**Comment by dbenage-cx** [comment] 2017-02-21 23:08
Looks like this is due to upkeep increasing when a new ship is created the same turn.

**Comment by dbenage-cx** [comment] 2017-02-22 03:20
@MatGB Thank you for catching this and providing save file

Fixed in 54d20fd

**Closed as completed by dbenage-cx** 2017-02-22 03:20 UTC
Labels: category:bug, component:UI, status:resolved
