### ISSUE TITLE
Bug: during game we encountered empire of color that was not present in empires list, also it was not on any graphs

### ISSUE THREAD

**Issue by afwbkbc** [freeorion/freeorion#899] opened 2016-08-21 15:40 UTC
Screenshot: http://dump.bitcheese.net/images/sywizav/oranzheviy.png
Empire list consists only of green, blue, teal, magenta, cyan and yellow.

**Comment by geoffthemedio** [comment] 2016-08-21 15:50
What version are you playing?

Provide a save file that reproduces the issue, please.

If you examine a planet or ship they own, what empire name does it have, and does it match up to something in the list?

**Comment by Voker57** [comment] 2016-08-21 15:57
Save file: http://dump.bitcheese.net/files/kaxesaw/l29ah2.mps
Upon loading, "orange" species appear to be cyan though.

**Comment by Voker57** [comment] 2016-08-21 15:57
screenshot by @afwbkbc http://dump.bitcheese.net/images/sywizav/oranzheviy.png

**Comment by geoffthemedio** [comment] 2016-08-21 15:58
so it's not reproducible?

**Comment by afwbkbc** [comment] 2016-08-21 15:59
It sometimes reproduces, sometimes not.

**Comment by Vezzra** [comment] 2016-08-21 17:33
Hm, just tried the savegame, but continued the game with only one human player each try. Tried as all three human player empires and as one of the AI empires as well. In all cases only the empire I was playing as appeared in the empires window. And the graphs don't seem to work, at least nothing was displayed when I looked at the production and research output graphs.

However, I can't say for sure which of these issues might be caused by me not using the same build as you... I can't find commit b90e812 that is referenced in the save file...?

@geoffthemedio, that looks quite complicated... do you consider that as critical for the release? To me it seems quite serious, but that might easily block the release...

**Comment by Voker57** [comment] 2016-08-21 17:48
We're using this https://github.com/Voker57/freeorion/tree/teamsmac branch, not sure why you can't see any empires except yours. Everything except this weird color issue is fine.

All graphs but custom one are disabled.

**Comment by geoffthemedio** [comment] 2016-08-21 17:49
I suspect the lack of graphs is because they were disabled / removed server side, as discussed here: https://github.com/freeorion/freeorion/issues/790

**Comment by geoffthemedio** [comment] 2016-08-21 17:49
@Vezzra did you add AI players for the empires you didn't control? Empires show up for me in the empires list only if they have an active player (eg. me or an AI)

**Comment by geoffthemedio** [comment] 2016-08-21 17:59
Perhaps during the games where this occurs, you are also neglecting to add enough AI players when loading the save?

**Comment by Vezzra** [comment] 2016-08-21 18:44
> We're using this https://github.com/Voker57/freeorion/tree/teamsmac branch

Ah, ok - could make my next tests with the correct buid now.

> All graphs but custom one are disabled.

I see, that explains it. Yes, there is one, apparently the custom one you're referring to, that works.

> @Vezzra did you add AI players for the empires you didn't control?

Argh, no. Obviously I never use multiplayer. When adding an AI player for each empire I don't control, everything works.

Couldn't reproduce the issue.

**Comment by Vezzra** [comment] 2016-08-21 18:46
Ok, @geoffthemedio, shall we keep the "Release v0.4.6" milestone? That will block the release as long as we can't solve this...

**Comment by geoffthemedio** [comment] 2016-08-21 18:56
probably not

**Comment by geoffthemedio** [comment] 2016-08-24 07:30
@Voker57 can you check if the issue is related to not having enough AI players for all the non-human empires in the game?-

**Comment by geoffthemedio** [comment] 2016-08-28 22:13
@Voker57 @afwbkbc bump

**Comment by Vezzra** [comment] 2016-09-23 10:57
@afwbkbc, @Voker57, re-bump... please provide feedback, otherwise we can't work on that issue...

**Comment by Voker57** [comment] 2016-09-24 08:10
@Vezzra not sure what it was caused by, maybe human error. I think you can close this.

**Comment by Vezzra** [comment] 2016-09-25 15:38
Ok.

**Closed as completed by Vezzra** 2016-09-25 15:38 UTC
Labels: category:bug, component:UI, status:works for me
