### ISSUE TITLE
Persistent Unidentified Industry Malus On Turn 1

### ISSUE THREAD

**Issue by Gunnarson010** [freeorion/freeorion#512] opened 2016-03-09 05:26 UTC
I started a game recently (build 2016-02-23.746cb85) as the Egassem only to find that I had no Industry whatsoever (0.00).  Upon further examination my home planet has the following malus: Unknown: -22.1.  I sent out a colony ship to a neighboring system and colonized a planet.  After one turn it had the exact same malus.  Needless to say the game was unplayable.

The first time I started, the malus stayed the same for at least 20 turns.  I subsequently reloaded the game and the malus goes away after turn 1.  I tried a few things but could not re-create the persistent version.  I have attached the save file; hopefully this will be of some use.  

[SuperIndustryMalusBug.zip](https://github.com/freeorion/freeorion/files/164556/SuperIndustryMalusBug.zip)

**Comment by Vezzra** [comment] 2016-03-10 13:19
When I load your save game, I can see the issue - there is that unknown malus, your industry meter is at zero. After one turn the unknown malus goes away, and the industry meter starts to build up.

Which, regardless if we can reproduce the malus staying for 20 turns or not, would be a bug, as you start out with 0 industry which only slowly builds up, leaving you with drastically reduced production capacity in the very critical first turns.

However, when I try to recreate the game by using the same build, seed and settings, I don't get that strange malus at the start of the game. On the starting turn my production is 19.1, everything else is like in your savegame (as far as I can see).

Meaning, I can't reproduce the issue. Can you, if you use the same build , seed and settings?

**Comment by Vezzra** [comment] 2016-04-22 13:22
@Gunnarson010, are you still there? Haven't got any response from you to my question above (if you can reproduce the issue reliably when using same build, seed and settings). Need further feedback from you, otherwise we can't do much about it, as I can't reproduce...

**Comment by tkinias** [comment] 2016-06-07 21:48
I know this isn’t especially useful for bug-hunting, but I’ve often noticed newbuilt colonies having an “unknown” malus zero out their production on the first turn.  I never paid that much attention, since I figured it was an undocumented effect I just didn’t understand rather than a bug...

**Comment by MatGB** [comment] 2016-06-08 07:36
It's a display bug, not actually sure if it's a Known Issue, should be, basically the display in your client is telling you estimates for the immediate turn to come production/research, but the server is telling you what happened last turn (sort of, it's more complicated than that), for a new colony, it did nothing last turn and had zero population, it confuses the client a bit, but settles out next turn.

**Comment by Vezzra** [comment] 2016-06-09 12:41
@Gunnarson010 hasn't reported back, I can't really reproduce - can anyone else? If not, should we close this issue...?

**Comment by tkinias** [comment] 2016-06-09 18:30
I can’t reproduce exactly what OP reported, but I do see newbuilt systems
with production zeroed out because of “unknown” malus.  Is that a bug or is
that an intended behaviour?

On Thu, Jun 9, 2016 at 8:41 AM, Vezzra notifications@github.com wrote:

> @Gunnarson010 https://github.com/Gunnarson010 hasn't reported back, I
> can't really reproduce - can anyone else? If not, should we close this
> issue...?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/freeorion/freeorion/issues/512#issuecomment-224882585,
> or mute the thread
> https://github.com/notifications/unsubscribe/AQphOfmNUqaGCsTsl2NASQf0ek6VJDE2ks5qKAnggaJpZM4HsbmT
> .

## 

Thanasis Kinias
Doctoral Student, Department of History
Northeastern University
kinias.t@husky.neu.edu

**Comment by Vezzra** [comment] 2016-06-10 11:46
Well, as @MatGB pointed out in his reply above, this is an unrelated (minor) display bug.

**Comment by tkinias** [comment] 2016-06-10 13:47
Ah, sorry, I misssed that post.  Nevermind!

**Comment by Vezzra** [comment] 2016-08-24 11:14
The OP never reported back, apparently no one can reproduce the issue, so I'm closing this issue. If it turns up again, or anyone finds a way to reproduce it, pls reopen or create a new issue.

**Closed as completed by Vezzra** 2016-08-24 11:14 UTC
Labels: category:bug, status:won't fix, component:game mechanic
