### ISSUE TITLE
Move population effects from species/common/population.macros when possible

### ISSUE THREAD

**Issue by MatGB** [freeorion/freeorion#715] opened 2016-06-18 21:11 UTC
The icons in the tech tree are generated automatically from the techs: [Post](http://www.freeorion.org/forum/viewtopic.php?p=84454#p84454). They were previously all grouped together in species.txt in order that they could be applied in the correct order, now we have an effects priority system and this has been applied to all population effects it is no longer needed for them to be where they are and it would be better for them to be in their originating tech.

Some effects/macros may need to remain where they are if shared between multiple kinds of scripted content, but if at all possible, especially for techs, they should be moved either to the source itself or to a macro file in that folder.

**Comment by geoffthemedio** [comment] 2016-06-18 21:16
(edited your description a bit)

**Comment by MatGB** [comment] 2016-06-18 22:21
Fine by me, that's clearer and I was struggling to word it anyway, thanks.

**Comment by dbenage-cx** [comment] 2016-06-20 02:04
Some planet shields, defense and troop tech effects could move over with priorities assigned.  Some specials and other effects (homeworld) could be shifted as well.

**Comment by geoffthemedio** [comment] 2016-06-25 12:59
I'd like to encourage attention to this issue. Particularly for population macros that are applied to species, where part of the activation is whether the owner has a particular tech, I suspect that the current arrangement is a major contributor to effects processing time increasing with number of ships or planets.

https://github.com/freeorion/freeorion/blob/master/default/scripting/species/common/population.macros#L104

As of now, with these macros in place, the game has to evaluate dozens of effect activation conditions for every object that has a species attached, including all these population effectsgroups for all the ships, which will never be acted on by them. I suspect it would be a lot faster to test the activation and evaluate the scope conditions once per empire, rather than once per ship or planet, as would be the case of they were moved into the tech being tested for in the current activation conditions.

**Comment by dbenage-cx** [comment] 2016-06-25 18:07
@geoffthemedio Is this issue now `won't fix`?  I'm inclined to close the PR, but don't want to appear upset.

**Comment by geoffthemedio** [comment] 2016-06-25 18:11
No? I just explained why it's worth doing. Why should / would it be marked won't fix or closed?

**Comment by dbenage-cx** [comment] 2016-06-25 18:26
Ok, i took your statement to mean that any move into tech would now result in a less efficient process.  Will look into reworking scope/activation.

**Comment by geoffthemedio** [comment] 2016-06-25 18:30
I don't know what you mean by "reworking scope/activation"... The suggested fix is to move tech effects into techs instead of having them in species.

**Comment by MatGB** [comment] 2016-06-26 02:07
@dbenage-cx that was my initial reaction on first read of @geoffthemedio 's comment as well, but on reread I worked out he meant the exact opposite.

I just loaded an existing save that was getting laggy when I saved last night and hit end turn with a timer running, then I recompiled, applied #723 and did the same. 2 second improvement on turn processing (8 reduced to 6), plus loading individual systems is noticeably faster and running a suitability report isn't an excuse to go make coffee.

And that's just switching the techs over. If I'd known it would make this much difference I'd have done it when I added the priorities.

I'm going to change the milestone to 0.4.6, if we can't get it all done that's fine but it's such a noticeable improvement that as much as possible should be pre-release.

**Comment by Vezzra** [comment] 2016-06-26 11:50
@dbenage-cx, what Mat said - @geoffthemedio wants to point out that addressing this issue might go a long way at (of/in - what's the correct English preposition here?) reducing lag caused by effect processing. So no, pls don't close your PR, it's a good step in the right direction 😃

**Comment by Vezzra** [comment] 2016-06-26 11:51
> I'm going to change the milestone to 0.4.6, if we can't get it all done that's fine but it's such a noticeable improvement that as much as possible should be pre-release.

Ack, agree, good idea, done :wink:

**Comment by MatGB** [comment] 2016-06-26 12:00
> a long way at (of/in - what's the correct English preposition here?)

None of them. A long way _to_ reduce lag, but it's English so there no such thing as 'correct', merely commonly used ;-) (and yeah, I forgot to hit the milestone change button, but seriously, a couple hours more play and it's noticeably faster, even when I'm messing around with multiple other scripts)

So, wonder what else we can speed up massively by moving them around and using priorities better, that hadn't really even occured to me.

**Comment by geoffthemedio** [comment] 2016-06-26 14:51
@Vezzra "towards"

Going or getting us a long way towards verbing something is a common expression. 

Something might also do a lot to help verb something else.

**Comment by MatGB** [comment] 2016-07-30 00:12
Unintended side effect of moving the defence effects from species into techs: outposts no longer go to zero defence/shields/troops when an empire is reduced to _just_ outposts.

Not actually sure I like that, the ability to mop up a defeated opponent quickly saves annoyances, but I think it's better solved with a surrender mechanic through diplomacy than the way it was working. Thought it worth observing though in case others have stronger opinions (plus, I have three troop ships sat now waiting for fleets to reduce shields down that're way out of the way in my current test game).

I'm currently testing #804 and while that's a more minor change (and the game I loaded it up into is Low Specials) there's a marked improvement in lag across the board, especially in combination to the supply propagation changes, I think a note under "Key Changes" saying significant work ahs been done to reduce lag and delays in larger/longer games or similar is a definite for the changelog.

**Closed as completed** 2016-07-31 03:27 UTC
Labels: component:content scripting, status:resolved

**Comment by Vezzra** [comment] 2016-07-31 08:55
> Not actually sure I like that, the ability to mop up a defeated opponent quickly saves annoyances, but I think it's better solved with a surrender mechanic through diplomacy than the way it was working.

I agree.

**Comment by dbenage-cx** [comment] 2016-07-31 17:13
Thanks for testing all of these MatGB.

Currently an empire is only eliminated once it has no planets and no ships (outposts count).  Could change this to `(no production or no planets) and no ships`, and then clear the known techs from an eliminated empire.  (Should this discussion move elsewhere?)

**Comment by MatGB** [comment] 2016-07-31 19:22
Definitely elsewhere, it's a broader "what do we want" thing than a specific "will this work" thing, and I'm not sure what I want anyway.

And thanks for doing it, the improvement in performance in larger games is quite remarkable, I really want to play a really big map again and see how well my box can handle things.
