### ISSUE TITLE
Wrong destination on "Incoming enemy" sitrep

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#2599] opened 2019-10-18 11:10 UTC
### Environment
* **FreeOrion Version**: 0.4.8+ 2019-10-13.49f7896 MSVC 2017
  * Weekly development build
* **Operating System**: Windows 7

### Description
The SitRep warning that an enemy is arriving next turn to one of your systems is showing me wrong information, the destination (the system under alert) linked in the sitrep is not the actual destination of the corresponding enemy, that might or might not be going to another of your systems which won't be indicated in any of the warning SitReps.
![FO_bug_sitrep_inc_enemy_bad_destination](https://user-images.githubusercontent.com/28650914/67089137-3acf3000-f1a7-11e9-8527-1e154673ec44.png)
![FO_bug_sitrep_inc_enemy_bad_destination_2](https://user-images.githubusercontent.com/28650914/67089136-3acf3000-f1a7-11e9-9023-833fb93c3e6f.png)

### Steps to reproduce
Load attached save game. It's is turn 256 (same game than the above screenshots).
Press turn and check incoming enemy SitReps at the end of the SitRep window. There should be one for system Robi Beta. In the only connected system (empty Space) there is only a Black Kraken headed to a different system, Robi Alpha, that is not getting any warning of the incoming monster.
Press turn again a check out SitReps: there won't be anything about combat or hidden stuff triggering your mines in Robi Beta, while there is for Robi Alpha.

[FO_bug_inc_enemy_sitrep_wrong_destination.logs.zip](https://github.com/freeorion/freeorion/files/3743550/FO_bug_inc_enemy_sitrep_wrong_destination.logs.zip)
[FO_bug_inc_enemy_sitrep_wrong_destination.sav.zip](https://github.com/freeorion/freeorion/files/3743551/FO_bug_inc_enemy_sitrep_wrong_destination.sav.zip)

**Comment by geoffthemedio** [comment] 2019-10-20 14:11
I think that part of the issue is that monster fleets' destinations are set by effects, but these sitreps are also generated by effects. All effectsgroups' scope conditions are evaluated before any effects fire, so the scope conditions that test to see what systems have fleets moving to them will only be able to check where fleets are moving before any effects are executed. But the destinations of fleets are modified by effects executed essentially at the same time as the sitrep generation, after those conditions are evaluated.

This would explain why destination systems that are 1 starlane jump away for a monster fleet aren't getting sitreps; at the time the condition decides what systems should have sitreps generated about monsters arriving, the monster fleets aren't yet moving to those systems.

This would also explain some sitreps are generated for the wrong system that is 1 jump away from a monster fleet's location; presumably the fleet's destination on the turn prior was the system indicated in the sitrep, but the destination changed after it was decided to generate that sitrep.

I'm not sure that I'm exactly reproducing your results though, as in my test of that save, the black kraken is going to Robi β, at least according to what is shown on the map. One or two other arriving monsters have no notification sitreps, though, including the fleet arriving at Agamem.

**Comment by Oberlus** [comment] 2019-10-20 17:48
> I'm not sure that I'm exactly reproducing your results though

Maybe concorrent computation allows for different unexpected behaviour on different systems?

Anyway, I can add that since I began playing two years ago I've been using that sitrep. Even late game I pay attention to every one of them, by clicking on the system link and checking out what's incoming. I've been not playing single player for 6-8 months until recently. Never before I found one of these wrong destination sitreps. This made me think the problem could come from a recent change.

However, I think I've only met Experimentors twice before, I remember Bloated Juggernauts and Black Krakken but not these super-fast monsters in this save. Since they are so fast, they can get to destination in one turn. Regular monsters need 2+ turns and so they could have the correct destination despite of the problem with effects calculation. And so this could explain why I didn't see this problem before even if it has been there since I began playing FO.

When an enemy is stationed at one hop of distance of your systems, and s/he decides to attack your possition, you don't get a sitrep, right? Just because there is no time for it. You don't know where the enemy is going before it starts going there.
Why we do know where is going the monster before it begins moving?
I suggest doing the same for monsters than for other enemies, so that you can't tell if a monster is going to jump for your 1-hop away position beforehand.

**Comment by geoffthemedio** [comment] 2019-10-20 18:11
> Why we do know where is going the monster before it begins moving?

Effects are applied after movement during a turn cycle, and effects set where monster fleets will move on the next turn cycle's movement. Human players set fleet destinations with orders, which are executed before fleet movement during a turn cycle.

Edit: There is also a limit in the script that generates the arriving ships sitrep, which only considers systems that have an enemy fleet moving to them that is less than 120 uu away from the system.

**Comment by geoffthemedio** [comment] 2019-10-21 21:45
Maybe fixed? https://github.com/freeorion/freeorion/commit/ae6b05b4656080f55666307f0ec87ef2c147b752

**Comment by Oberlus** [comment] 2019-10-22 19:06
> Maybe fixed? [ae6b05b](https://github.com/freeorion/freeorion/commit/ae6b05b4656080f55666307f0ec87ef2c147b752)

Indeed. Tested 10 turns on the same save, all sitreps were right and no system got a monster without prior notice.
Good job. You can close this.

**Closed as completed** 2019-10-22 19:24 UTC
Labels: category:bug, component:content scripting, component:UI, status:resolved
