### ISSUE TITLE
Incorrect pass through

### ISSUE THREAD

**Issue by jinlan** [freeorion/freeorion#2675] opened 2019-12-16 05:21 UTC
Enemy stealthy 5 fleet has passed through my ship, without triggering a combat.
My version is : c0eb3bb, win32 version
[Save](https://github.com/jinlan/issue/raw/master/FreeOrion_incorrect_pass_through_jinlanid.7z)

Don't just press "end turn" after load this save, order the robotic hull ship to stand still, then end turn.

**Comment by Vezzra** [comment] 2019-12-16 10:58
Confirmed on macOS.

Looks like the status of the robotic ship does not get properly reset to "stationary" when ordering it to stand still, because only the enemy fleets passing through that system at that specific turn do not get blocked. Another fleet tries to pass through on the subsequent turn, and this one *does* get blocked.

I'd prefer this to be fixed for 0.4.9, so I'm assigning it to the release milestone, and setting priority to high.

**Comment by o01eg** [comment] 2019-12-17 11:19
`Condition::Stationary` uses a little different code to check stationary compared to `StationaryFleetVisitor`. Can it be related?

https://github.com/freeorion/freeorion/blob/d9345e1c226423462279b89648467fd6b042f23d/universe/Condition.cpp#L8056-L8063

https://github.com/freeorion/freeorion/blob/a01f389f76d14214face26d5f96f9c02847a7aa5/universe/Predicates.cpp#L72-L77

**Comment by o01eg** [comment] 2019-12-18 20:31
Other code possible to blame. Looks like other blockade issue happened here:

https://github.com/freeorion/freeorion/blob/master/server/ServerApp.cpp#L3302-L3313

**Comment by o01eg** [comment] 2019-12-18 21:27
@Vezzra 
> Another fleet tries to pass through on the subsequent turn, and this one does get blocked.

As I see in the debugger this fleet wasn't blockaded, it just targeted for this system:

```cpp
Thread 1 "freeoriond" hit Breakpoint 1, Fleet::MovementPhase (this=0x6120001cc9c0) at /mnt/another/srcs/GIT/freeorion/universe/Fleet.cpp:790
790	void Fleet::MovementPhase() {
(gdb) p *this
$33 = {<UniverseObject> = {<std::enable_shared_from_this<UniverseObject>> = {_M_weak_this = std::weak_ptr<UniverseObject> (use count 5, weak count 1) = {
        get() = 0x6120001cc9c0}}, _vptr.UniverseObject = 0x7ffff7422ca0 <vtable for Fleet+24>, StateChangedSignal = warning: RTTI symbol not found for class 'boost::signals2::signal<void (), blocking_combiner<boost::signals2::optional_last_value<void> >, int, std::less<int>, boost::function<void ()>, boost::function<void (boost::signals2::connection const&)>, boost::signals2::mutex>'

{<boost::signals2::signal_base> = {<boost::noncopyable_::noncopyable> = {<boost::noncopyable_::base_token> = {<No data fields>}, <No data fields>}, 
        _vptr.signal_base = 0x7ffff73f7260 <vtable for boost::signals2::signal<void (), blocking_combiner<boost::signals2::optional_last_value<void> >, int, std::less<int>, boost::function<void ()>, boost::function<void (boost::signals2::connection const&)>, boost::signals2::mutex>+16>}, <boost::signals2::detail::std_functional_base<>> = {<No data fields>}, static arity = <optimized out>, _pimpl = {px = 0x604000f6a590, pn = {pi_ = 0x60300089c350}}}, 
    static INVALID_POSITION = -100000, static INVALID_OBJECT_AGE = -1073741825, static SINCE_BEFORE_TIME_AGE = 1073741825, m_name = "Fleet 15358", 
    m_id = 15358, m_x = 203.98615176128183, m_y = 295.2708413963154, m_owner_empire_id = 7, m_system_id = -1, m_specials = std::map with 0 elements, 
    m_meters = std::map with 1 element = {[METER_STEALTH] = {static DEFAULT_VALUE = 0, static LARGE_VALUE = 65536, static INVALID_VALUE = -65536, 
        m_current_value = 2000, m_initial_value = 2000}}, m_created_on_turn = 79}, static ETA_NEVER = 1073741822, static ETA_UNKNOWN = 1073741824, 
  static ETA_OUT_OF_RANGE = 1073741823, m_ships = std::set with 1 element = {[0] = 9266}, m_prev_system = 2416, m_next_system = 2072, m_aggressive = true, 
  m_ordered_given_to_empire_id = -1, m_travel_route = std::__cxx11::list = {[0] = 2072, [1] = 1280}, m_arrived_this_turn = false, m_arrival_starlane = 2416}
```

**Comment by o01eg** [comment] 2019-12-18 21:50
Also I'm not sure how `Fleet::MovementPhase` checks path for blockage if it calls `Fleet::MovePath` with `flag_blockades = false`.

**Comment by Vezzra** [comment] 2019-12-19 20:30
> As I see in the debugger this fleet wasn't blockaded, it just targeted for this system

Oh, ok. Didn't think of that, but of course. Well, in that case this issue is even more serious. Any chance this can be fixed quickly (that is, before Sunday)? If not, RC1 needs to be postponed once again.

**Comment by o01eg** [comment] 2019-12-21 21:08
> 
> 
> Also I'm not sure how `Fleet::MovementPhase` checks path for blockage if it calls `Fleet::MovePath` with `flag_blockades = false`.

I've tried to call `MovePath` with `true` here but it doesn't change anything with the issue.

**Comment by Oberlus** [comment] 2019-12-24 14:35
> this issue is even more serious. Any chance this can be fixed quickly (that is, before Sunday)? If not, RC1 needs to be postponed once again.

Right now this is the only issue blocking RC1. I've tried reading the code of Fleet.cpp and ServerApp.cpp but I don't understand C++ and have no idea of what could be changed. Maybe @geoffthemedio is our last resort to fix this?

**Comment by geoffthemedio** [comment] 2019-12-25 04:07
I don't know the blockade code very well, as I don't think I wrote it. I'll try to take a look when I have time, but I'm still traveling until the end of the year.

**Comment by TheSilentOne1** [comment] 2019-12-25 20:11
I think @Dilvish-fo is the author of the blockade code.

**Comment by o01eg** [comment] 2019-12-29 09:31
Can we document this behavior and postpone this issue for the next release? I suppose blockage and moving code requires overhaul because it depends on order of fleet processing (see https://github.com/freeorion/freeorion/pull/2220 )

**Comment by Vezzra** [comment] 2019-12-29 10:50
If the blockade mechanics don't work reliably, that is a potentially game-breaking issue. Very much depending on if that only happens in rare edge cases or can happen more frequently.

As it seems to be only rare edge cases, I guess we can downgrade the issue to not-release-blocking. However, I'd like to propose to make a 0.4.9.1 bugfix release as soon as the issue has been fixed.

Bottom line, I'm not too excited about not having this fixed in the release, but I won't object to get the release out nonetheless. However, I'm deferring the final decision to @geoffthemedio - @geoffthemedio, your call.

**Comment by Oberlus** [comment] 2019-12-29 10:54
From current multiplayer game experience, blockade does work, at least most of the time.
The problem could be that it doesn't work until two turns after the blockading fleet arrived the system. This needs testing for confirmation.

**Comment by geoffthemedio** [comment] 2020-01-01 03:32
Please test and report as specifically as possible what happens when something else should happen and ideally provide test saves to reproduce the issue.

**Comment by Vezzra** [comment] 2020-01-01 12:41
@geoffthemedio, should this issue continue to be considered release-blocking, or shall we "demote" it to optional for the release, so we can proceed with RC1 (see [above](https://github.com/freeorion/freeorion/issues/2675#issuecomment-569494051))?

**Comment by geoffthemedio** [comment] 2020-01-03 10:51
@jinlan Any chance you have the save from the turn prior to the one posted with the issue?

**Comment by geoffthemedio** [comment] 2020-01-03 11:12
Please test #2689 

Not sure if it will have any side effects, though...

Possibly the issue was because the fleet in the nameless system was ordered to move, then the game was saved, and so when loading and a supply update was done, it considered that fleet as moving and so not eligible to blockade / control a system. Ordering it to stay afterwards didn't help as there was no obstruction update before the movement during the turn update, so even though the fleet stayed in place, the most recent obstruction info didn't consider that system to be blocked for the fleets moving through it. Doing another obstruction update immediately before movement means the order to stay in place is in effect, so the fleet is considered stationary and able to block the enemy fleets' movement through the system.

**Comment by jinlan** [comment] 2020-01-03 12:29
Sorry. It's auto-save, I played many other games after that. So, don't have the save you asked.

**Closed as completed** 2020-01-05 20:37 UTC
Labels: category:bug, component:game mechanic, status:resolved
