### ISSUE TITLE
AI/server crash -possible bad ship design?

### ISSUE THREAD

**Issue by indywatch** [freeorion/freeorion#3617] opened 2021-12-18 11:04 UTC
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: v0.4.10+ [build 2021-12-13.d81306e] CMake (snap)
* **Operating System**: Debian 4.19.5-2~mx17+1 (2018-12-12) x86_64 GNU/Linux
* **Graphic card used**: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)
* **Fetched as** 
  * Weekly development build

Description
-----------

Server exits during AI turn, client disconnects from server. Game crashes. Locally reproducible each time I load my save file.

Expected Result
---------------

None of that.

Steps to reproduce
------------------

* Load Save file
* Wait
* Crash!

[freeorion.log](https://github.com/freeorion/freeorion/files/7739116/freeorion.log)
[freeoriond.log](https://github.com/freeorion/freeorion/files/7739117/freeoriond.log)
[AI_4.log](https://github.com/freeorion/freeorion/files/7739118/AI_4.log)
[FreeOrion_Coordinator_Helpers_0512_20211218_210534.sav.log](https://github.com/freeorion/freeorion/files/7739131/FreeOrion_Coordinator_Helpers_0512_20211218_210534.sav.log)

**Comment by geoffthemedio** [comment] 2021-12-19 11:49
I'm not sure why or where exactly it happens, but at some stage in determining the targets for an effect, it was making a duplicate of a ship (id: 6830) that seems to have a valid design when viewed in the ObjectsList in the client, but which didn't have a valid ID at that point in the code. This lead to an attempt to create a temporary ship for calculating ship damage to fail, which lead to a crash. I've [added some safety checks](https://github.com/freeorion/freeorion/commit/32078cd0ca6aace49138b6732b122b78cfb846b7) and reworked some things to [avoid doing the temporary ship creation](https://github.com/freeorion/freeorion/commit/4c275416c1a3dfc1431336318354e2964873bb06) at all when not really needed, which seems to stop the crash. There might be some additional minor issues related to this, but it's harder to completely figure out what's going on than just fix the symptoms for now...

**Closed as completed by geoffthemedio** 2021-12-19 11:49 UTC
Labels: category:bug, status:resolved, component:internal

**Comment by geoffthemedio** [comment] 2021-12-22 18:08
After investigating more, I think the sequence of events was:
-An empire detects another empire's ship at basic visibility, which sets the ship's design to **-1**, indicating unknown design
-Some time later, the empire attempts to calculate how many armed ships are in a fleet or system as part of the Flanking policy calculations
-As part of that calculation, it calculates the weapon damage for each ship, in order to check if it is > 0 and thus the ship qualifies as armed
-To do that, it creates a temporary copy of the ship that can be used as a mutable target object in the context of a ValueRef evaluation
-Creating the copy involves constructing a new ship object by passing the design ID, here **-1**
-The **Ship** class constructor throws an exception if passed a ship design ID that isn't the ID of a ship design, which **-1** is not.

Should be fixed now, in that it won't crash. A ship with no valid design ID will be considered as not armed for client-side estimtaions of how many armed ships are present somewhere.
