### ISSUE TITLE
Resizing Game Window While Droplist Open Doesn't Reposition Dropped List

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#1139] opened 2016-11-27 09:19 UTC
Drop the focus or system droplist on the sidepanel, then resize the game window (with the droplist still open). The sidepanel repositions itself, but the dropped list doesn't.
![drop reposition](https://cloud.githubusercontent.com/assets/11386908/20647068/caa403d4-b48a-11e6-8a52-b564d203ad79.png)

**Comment by geoffthemedio** [comment] 2016-11-27 12:53
I also think resizing like this is the cause of a somewhat difficult to reproduce issue I occasionally have, where after dropping the system droplist or focus droplist, I can't select anything in them by clicking. Possibly occurs after reducing the screen size, so that the new position of the droplists is substantially left of the old position, and the old position is now off screen?

**Comment by Vezzra** [comment] 2016-11-27 14:39
Confirmed on OSX.

**Comment by geoffthemedio** [comment] 2016-11-30 09:10
This is not entirely resolved. Currently just for the system droplist (but not the focus drop), after resizing the window, the list doesn't respond to clicks after it is dropped. Specifically, start FreeOrion windowed with default size substantially less than the screen resolution, quickstart, send two scouts to explore for a few turns. Click the system drop and select another system successfully. Double click or otherwise maximize the game window. Click the system drop to open it, then try to click on items in the list... doesn't respond to clicks. Pressing escape closes the dropped list.

**Comment by LGM-Doyle** [comment] 2016-11-30 19:12
This works for me.  I have tried the following variations to duplicate the problem, perhaps I have misunderstood the issue that you are seeing.

Opened freeorion in windowed mode, explored a bit and then:
- dropped system name, resized window while dropped, system name closes but is still selected, key selection still works on system name, re-dropping system name and selecting a system works. 
- dropped focus drop, resized window while dropped, focus drop closes but is still selected, key selection still works on focus drop, dropping system name and selecting a system works. 
- system name drop -> resize app -> focus drop works.
- focus drop -> resize app -> focus drop works.
 
I have tried resizing so it does/does not substantially move the actual/relative position of the system name.

I have done it many times in one session.

I have resized the whole app by maximizing and also by clicking and dragging the app window.

**Comment by geoffthemedio** [comment] 2016-11-30 19:14
don't resize while dropped; resize while not dropped, then drop and attempt to click on the dropped list.

edit: having the droplist open/dropped doesn't seem to matter. resizing the window result in me not being able to click the dropped list.

initially, it works, and respond to clicks
![initial](https://cloud.githubusercontent.com/assets/11386908/20767809/ec3a9d42-b73b-11e6-8ed0-b0b4c9aa699d.png)

after mazimizing, it won't respond to clicks on the dropped list
![after resize](https://cloud.githubusercontent.com/assets/11386908/20767823/fa286754-b73b-11e6-8ae1-32c44092ea3d.png)

**Comment by LGM-Doyle** [comment] 2016-11-30 20:11
Thanks for the extra info.  

My problem was that my freeorion defaulted, even windowed, to full monitor size and the sidepanel defaulted to open on start up from my `persistent_config.xml`, so it grabbed the full screen size for the modal window supporting the drop down.

**Comment by Vezzra** [comment] 2016-12-11 17:57
@geoffthemedio, @LGM-Doyle, is this completely resolved now...? Can we close this?

**Comment by LGM-Doyle** [comment] 2016-12-12 16:02
The bug that I found is fixed.  That bug was the only way that I was able to replicate the behavior.  

I think that this issue is fixed.

**Closed as completed** 2016-12-12 16:52 UTC
Labels: category:bug, component:UI, status:resolved
