### ISSUE TITLE
Homeworld rules change broke SuperTester omniscience.

### ISSUE THREAD

**Issue by ghost** [freeorion/freeorion#1608] opened 2017-06-16 02:44 UTC
Now that the homeworld flag only works for a planet's original species, SuperTester omniscience no longer works, since they never have a homeworld.

Either Supertesters need to ignore the new homeworld restrictions, or the homeworld requirement for omniscience needs to be removed.

**Comment by geoffthemedio** [comment] 2017-08-14 09:01
I'm unable to replicate this issue... Super testers don't appear to have a homeworld-related condition affecting their detection ability.

https://github.com/freeorion/freeorion/blob/master/default/scripting/species/SP_SUPERTEST.focs.txt#L35

There is a capital restriction that could be removed, but nothing presently seems to be broken. Did this issue resolve itself since it was reported?

**Comment by Vezzra** [comment] 2017-08-20 12:06
@geoffthemedio, I think @spikethehobbitmage refers to the capital restriction on [line 46](https://github.com/freeorion/freeorion/blob/master/default/scripting/species/SP_SUPERTEST.focs.txt#L46). If the "Capital" condition indeed can only be met by the original species now, then the Super Testers omniscience actually *is* broken, because detection strength won't get set to 200 anymore.

The effect of this probably isn't immediately obvious, because setting *detection range* to 10000 still works. But sufficiently stealthy objects would remain undetected, which of course is hard to notice.

Maybe replace the "Capital" condition with "Planet"? That way the SetEmpireMeter effect at least won't get triggered for each Super Tester object, only for planets.

**Comment by geoffthemedio** [comment] 2017-08-20 13:20
Capitals have nothing to do with species. It is a property of an empire.

If the concern is that the Super Tester effect will only apply if they are located on the empire's capital planet, then that is a potential issue, though it would require producing the Super Tester Takeover building somewhere other than the capital, or moving the palace building.

But what the actual issue is is not clear.

**Comment by Vezzra** [comment] 2017-08-20 14:26
> But what the actual issue is is not clear.

If I understand correctly (@spikethehobbitmage, please correct me if I'm wrong): apparently there has been a change that causes the "Capital" condition to evaluate to true *only* if the species of the planet that is currently the capital of the empire is the *original* species of that planet.

Meaning, the Super Testers never are the original species of a colony (as they are set by the Takeover building), hence the "Capital" condition fails for them regardless if they are on the empire capital or not.

Consequently the effectsgroup of the Super Tester species which sets the detection strength never triggers, so you only get enhanced detection range, but not detection strength from the Super Testers.

> Capitals have nothing to do with species. It is a property of an empire.

If this means that the "Capital" condition triggers regardless if the species of the capital is the original one or not, then there is no issue indeed, and this should be closed.

Further feedback from @spikethehobbitmage would be helpful at this point...

> If the concern is that the Super Tester effect will only apply if they are located on the empire's capital planet, then that is a potential issue

Regardless if this issue here is valid or not, I'd agree that having the Super Tester effect apply only if they are located on the capital is a problem. Either clarify in the descriptions of the building and species that the Super Testers only work correctly on empire capitals, or remove the restriction (I'd prefer the latter).

**Comment by geoffthemedio** [comment] 2017-08-20 14:59
Removing the restriction to capitals would mean the effect would fire on all planets on which the species is located. That's probably not a problem in practice.

**Comment by Dilvish-fo** [comment] 2017-08-27 17:38
> apparently there has been a change that causes the "Capital" condition to evaluate to true only if the species of the planet that is currently the capital of the empire is the original species of that planet.

While I would agree that the OP does *appear( to be claiming this, I find no evidence of it in the code, and given that the OP has not provided any evidence nor tried to clarify anything since creating the issue, I think it's time we should conclude the claim is unfounded (likely some type of observer error).

> I'd agree that having the Super Tester effect apply only if they are located on the capital is a problem.  Either clarify in the descriptions of the building and species that the Super Testers only work correctly on empire capitals, or remove the restriction (I'd prefer the latter).

It's not that the entire set of Super Testers effects only apply if they are located on the capital-- empire detection strength is the only one of their effects that I see to be at an empire level, and it seems appropriate to me (and potentially useful during testing) if it continued to only apply if the the Capital is in fact inhabited by SuperTesters.  And it also looks to me like their ingame description [has correctly noted this for quite some time now](https://github.com/freeorion/freeorion/blob/63d91814acf62834d53be63fccb1eaf61086b31b/default/stringtables/en.txt#L7382). "(Stealth-busting power only works when they are in a Capital)"  (since scrolling the line to read the relevant portion in the Github presentation is quite awkward, I suggest just copying the line from there and then pasting to an editor.)

Whether we leave the Capital restriction in or not just changes which type of flexibility it gives the person testing.  I have a slight preference to leave as is, but if you want to change it I won't object.  But it seems clear that there is no actual *problem* with the way it works and is described, and certainly not the problem asserted by this Issue, so I am going to close this.

**Closed as completed by Dilvish-fo** 2017-08-27 17:38 UTC
Labels: category:bug, component:content scripting, status:works for me

**Comment by MatGB** [comment] 2017-08-28 02:30
I would prefer it as is if it's working as it was, having the option of putting Testers in on a small colony to get the distance bonus without revealing everything I haven't the tech for is useful sometimes if testing edge case situations, if they only apply the detection strength bonus if at your capital then it's still available as an option without removing the ability to use them without a complete reveal.

**Comment by Vezzra** [comment] 2017-08-28 11:09
@Dilvish-fo, ah, ok, I completely missed that the detection strength bonus being tied to the capital is already mentioned in the pedia. So, if the issue isn't reproducible, closing this is fine.

@MatGB: Good point, didn't think of that.
