### ISSUE TITLE
Issue compiling Freeorion on Fedora 32

### ISSUE THREAD

**Issue by mikedahlgren** [freeorion/freeorion#2795] opened 2020-03-19 04:54 UTC
* **FreeOrion Version**: GitHub Master from 3/18/20
* **Operating System**: Fedora 32

### Description

While running make I receive the following error:

````
[ 16%] Built target GiGi
Scanning dependencies of target freeorionversion
Writing file: util/Version.cpp
Building v0.4.9+ build 2020-03-18.f835296
[ 16%] Built target freeorionversion
Scanning dependencies of target freeorioncommon
[ 17%] Building CXX object CMakeFiles/freeorioncommon.dir/combat/CombatEvent.cpp.o
In file included from /usr/include/boost/serialization/deque.hpp:25,
                 from /home/dahlgren/freeorion/combat/../util/Serialize.ipp:13,
                 from /home/dahlgren/freeorion/combat/CombatEvent.cpp:6:
/usr/include/boost/serialization/collections_save_imp.hpp: In function ‘void boost::serialization::stl::save_collection(Archive&, const Container&, boost::serialization::collection_size_type)’:
/usr/include/boost/serialization/collections_save_imp.hpp:60:16: error: no post-decrement operator for type
   60 |     while(count-- > 0){
      |                ^~
In file included from /usr/include/boost/serialization/deque.hpp:26,
                 from /home/dahlgren/freeorion/combat/../util/Serialize.ipp:13,
                 from /home/dahlgren/freeorion/combat/CombatEvent.cpp:6:
/usr/include/boost/serialization/collections_load_imp.hpp: In function ‘typename boost::enable_if<boost::serialization::detail::is_default_constructible<typename T::value_type>, void>::type boost::serialization::stl::collection_load_impl(Archive&, T&, boost::serialization::collection_size_type, boost::serialization::item_version_type)’:
/usr/include/boost/serialization/collections_load_imp.hpp:72:16: error: no post-decrement operator for type
   72 |     while(count-- > 0){
      |                ^~
/usr/include/boost/serialization/collections_load_imp.hpp: In function ‘typename boost::disable_if<boost::serialization::detail::is_default_constructible<typename T::value_type>, void>::type boost::serialization::stl::collection_load_impl(Archive&, T&, boost::serialization::collection_size_type, boost::serialization::item_version_type)’:
/usr/include/boost/serialization/collections_load_imp.hpp:94:16: error: no post-decrement operator for type
   94 |     while(count-- > 0){
      |                ^~
In file included from /home/dahlgren/freeorion/combat/../util/Serialize.ipp:15,
                 from /home/dahlgren/freeorion/combat/CombatEvent.cpp:6:
/usr/include/boost/serialization/map.hpp: In function ‘void boost::serialization::load_map_collection(Archive&, Container&)’:
/usr/include/boost/serialization/map.hpp:58:16: error: no post-decrement operator for type
   58 |     while(count-- > 0){
      |                ^~
In file included from /usr/include/boost/serialization/unordered_set.hpp:24,
                 from /home/dahlgren/freeorion/combat/../util/Serialize.ipp:16,
                 from /home/dahlgren/freeorion/combat/CombatEvent.cpp:6:
/usr/include/boost/serialization/unordered_collections_save_imp.hpp: In function ‘void boost::serialization::stl::save_unordered_collection(Archive&, const Container&)’:
/usr/include/boost/serialization/unordered_collections_save_imp.hpp:69:16: error: no post-decrement operator for type
   69 |     while(count-- > 0){
      |                ^~
In file included from /usr/include/boost/serialization/unordered_set.hpp:25,
                 from /home/dahlgren/freeorion/combat/../util/Serialize.ipp:16,
                 from /home/dahlgren/freeorion/combat/CombatEvent.cpp:6:
/usr/include/boost/serialization/unordered_collections_load_imp.hpp: In function ‘void boost::serialization::stl::load_unordered_collection(Archive&, Container&)’:
/usr/include/boost/serialization/unordered_collections_load_imp.hpp:64:16: error: no post-decrement operator for type
   64 |     while(count-- > 0){
      |                ^~
In file included from /home/dahlgren/freeorion/combat/../util/Serialize.ipp:18,
                 from /home/dahlgren/freeorion/combat/CombatEvent.cpp:6:
/usr/include/boost/serialization/set.hpp: In function ‘void boost::serialization::load_set_collection(Archive&, Container&)’:
/usr/include/boost/serialization/set.hpp:53:16: error: no post-decrement operator for type
   53 |     while(count-- > 0){
      |                ^~
In file included from /home/dahlgren/freeorion/combat/../util/Serialize.ipp:19,
                 from /home/dahlgren/freeorion/combat/CombatEvent.cpp:6:
/usr/include/boost/serialization/vector.hpp: In function ‘void boost::serialization::save(Archive&, const std::vector<bool, Allocator>&, unsigned int)’:
/usr/include/boost/serialization/vector.hpp:191:16: error: no post-decrement operator for type
  191 |     while(count-- > 0){
      |                ^~
/usr/include/boost/serialization/vector.hpp: In function ‘void boost::serialization::load(Archive&, std::vector<bool, Allocator>&, unsigned int)’:
/usr/include/boost/serialization/vector.hpp:207:72: error: no pre-increment operator for type
  207 |     for(collection_size_type i = collection_size_type(0); i < count; ++i){
      |                                                                        ^
make[2]: *** [CMakeFiles/freeorioncommon.dir/build.make:63: CMakeFiles/freeorioncommon.dir/combat/CombatEvent.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:631: CMakeFiles/freeorioncommon.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
````

**Comment by adrianbroher** [comment] 2020-03-19 07:26
Cannot reproduce with f835296bb72370edeb76416cb8695d44f6f85003 on Fedora 31, which provides boost 1.69.

**Comment by adrianbroher** [comment] 2020-03-19 08:06
Can reproduce with f835296bb72370edeb76416cb8695d44f6f85003 in a Fedora 32 container, which provides boost 1.72.

**Comment by adrianbroher** [comment] 2020-03-19 08:34
Can reproduce with v0.4.9 in a Fedora 32 container, which provides boost 1.72.

**Comment by geoffthemedio** [comment] 2020-03-19 13:30
Not sure what changed to cause the problem, but 1.69 also lacks the increment operators in `collection_size_type`: https://www.boost.org/doc/libs/1_69_0/boost/serialization/collection_size_type.hpp

Only difference to 1.72 appears to be grooming / whitespace: https://www.boost.org/doc/libs/1_72_0/boost/serialization/collection_size_type.hpp

Is the compiler version different between Fedora 31 and 32?

**Comment by mikedahlgren** [comment] 2020-03-19 16:18
There is also a difference in the compiler version.  Fedora 32 is using GCC Version 10.0.1 while Fedora 31 has GCC Version 9.2.1

Source: https://apps.fedoraproject.org/packages/gcc

**Comment by adrianbroher** [comment] 2020-03-19 21:16
I claim this is a bug within boost serialization in combination with GCC 10.0.1

This minimal example fails with the same kind of errors within the Fedora 32 container, but builds and runs fine on Fedora 31.

```
// compile with: g++ -l boost_serialization

#include <fstream>
#include <iostream>
#include <vector>
#include <boost/archive/text_oarchive.hpp>
#include <boost/archive/text_iarchive.hpp>
#include <boost/serialization/vector.hpp>

int main(int argc, char** argv)
{
	std::vector<int> data({1, 2, 3});

	{
		std::ofstream ofs("thing.dat");
		boost::archive::text_oarchive oa(ofs);
		oa & data;
	}

	std::vector<int> read;

	{
		std::ifstream ifs("thing.dat");
		boost::archive::text_iarchive ia(ifs);
		ia & read;
	}

	for (auto& e: read)
	{
		std::cout << e << std::endl;
	}

	return 0;
}
```

**Comment by geoffthemedio** [comment] 2020-03-19 21:54
Does adding the missing operators to `collection_size_type` help? Something like
````
    collection_size_type & operator--() {
        t--;
        return *this;
    }
    collection_size_type operator--(int) {
        collection_size_type temp = *this;
        t--;
        return temp;
    }
    collection_size_type & operator++() {
        t++;
        return *this;
    }
    collection_size_type operator++(int) {
        collection_size_type temp = *this;
        t++;
        return temp;
    }
````

Or perhaps something like this in Serialize.ipp and SerializeMultiplayerCommon.cpp so the fix is in FreeOrion code:
````
diff --git a/util/Serialize.ipp b/util/Serialize.ipp
index a74897324..cb8918fea 100644
--- a/util/Serialize.ipp
+++ b/util/Serialize.ipp
@@ -22,10 +22,15 @@
 #include <boost/uuid/uuid_serialize.hpp>
 #include <boost/uuid/uuid_io.hpp>
 #include <boost/serialization/optional.hpp>
+#include <boost/serialization/collection_size_type.hpp>
 
 #include <GG/Clr.h>
 
 namespace boost { namespace serialization {
+    collection_size_type& operator++(collection_size_type& c);
+    collection_size_type operator++(collection_size_type& c, int);
+    collection_size_type& operator--(collection_size_type& c);
+    collection_size_type operator--(collection_size_type& c, int);
 
     template <class Archive>
     void serialize(Archive& ar, GG::Clr& clr, const unsigned int version)



diff --git a/util/SerializeMultiplayerCommon.cpp b/util/SerializeMultiplayerCommon.cpp
index a52210907..00c4ff1a7 100644
--- a/util/SerializeMultiplayerCommon.cpp
+++ b/util/SerializeMultiplayerCommon.cpp
@@ -11,6 +11,34 @@
 #include <boost/uuid/random_generator.hpp>
 #include <boost/uuid/uuid_io.hpp>
 
+namespace boost { namespace serialization {
+    // Prefix increment
+    collection_size_type& operator++(collection_size_type& c) {
+        std::size_t& t = c;
+        t++;
+        return c;
+    }
+    // Postfix increment
+    collection_size_type operator++(collection_size_type& c, int) {
+        collection_size_type temp = c;
+        ++c;
+        return temp;
+    }
+    // Prefix decrement
+    collection_size_type& operator--(collection_size_type& c) {
+        std::size_t& t = c;
+        t--;
+        return c;
+    }
+    // postfix decrement
+    collection_size_type operator--(collection_size_type& c, int) {
+        collection_size_type temp = c;
+        --c;
+        return temp;
+    }
+}}
+
+
 
 template <class Archive>
 void GalaxySetupData::serialize(Archive& ar, const unsigned int version)
````

**Comment by robertramey** [comment] 2020-03-20 05:02
I will look into supplying the missing operators

**Comment by mikedahlgren** [comment] 2020-03-27 04:21
Hi Robert, just curious if you have had a chance to take a look?  Thanks!

**Comment by adrianbroher** [comment] 2020-03-31 10:14
@geoffthemedio
> Or perhaps something like this in Serialize.ipp and SerializeMultiplayerCommon.cpp
> *snip*

Sounds good, but I would like to include this conditionally on the compiler and its version.

I will give it a try.

**Comment by robertramey** [comment] 2020-03-31 11:51
I looked at this over the weekend.  I'm happy with my solution.  But it still doesn't work yet!  I don't know if I'll be able to get it finished before the next release. FYI it shows up as an error in the Boost test matrix for gcc version 10.[http://www.boost.org/development/tests/develop/developer/serialization.html](url)
Doesn't seem to be a problem for clang version 10 though.

**Comment by geoffthemedio** [comment] 2020-03-31 12:15
> I would like to include this conditionally on the compiler and its version.

Probably also conditional on the Boost version...

Also please sanity check that code, if you don't rewrite it.

**Comment by adrianbroher** [comment] 2020-04-03 11:36
@mikedahlgren FYI: Fedora has updated it's gcc package a week ago, containing a fix.

**Comment by robertramey** [comment] 2020-04-03 14:56
Sooo - there is a bug in gcc 10.0 which is revealed by boost serialization.  This would call for no action on my part.  But while investigating this, I've updated collection_size_type to be more formally correct and limiting implicit conversions which exposed this problem.  But now I'm having difficulties as this has exposed some overzealous implicit type conversion which I generally try to avoid in the hope of diminishing surprising behavior.  This is still pending.

**Closed as completed** 2020-04-03 20:38 UTC
Labels: category:bug, status:resolved, component:internal

**Comment by mikedahlgren** [comment] 2020-04-14 19:53
Just wanted to say thank you for the investigation and I can confirm that it does indeed work now.
