### ISSUE TITLE
Fleet Windows not showing

### ISSUE THREAD

**Issue by cpeosphoros** [freeorion/freeorion#1859] opened 2017-11-16 14:32 UTC
### Environment
```
$ inxi -GSx
System:    Host: chronos-18 Kernel: 4.4.0-98-generic x86_64 (64 bit gcc: 5.4.0)
           Desktop: Cinnamon 3.2.7 (Gtk 3.18.9) Distro: Linux Mint 18.1 Serena
Graphics:  Card: NVIDIA GM200 [GeForce GTX 980 Ti] bus-ID: 01:00.0
           Display Server: X.Org 1.18.4 drivers: nvidia (unloaded: fbdev,vesa,nouveau)
           Resolution: 1920x1080@60.00hz, 1680x1050@59.88hz
           GLX Renderer: GeForce GTX 980 Ti/PCIe/SSE2 GLX Version: 4.5.0 NVIDIA 384.98 Direct Rendering: Yes
```
* **FreeOrion Version**: 5f3d5b0  
* **Fetched as**
  * Compiled from source
### Description
Clicking on a fleet (or otherwise selecting it, e.g., via <CTRL>-<G>) only opens its Fleet Window once. After that, selecting a fleet doesn't open its fleet window, effectively rendering the game unplayable. 
### Expected Result
Selecting a fleet should open its fleet window.
### Steps to reproduce
* Compile 5f3d5b0  
* Play game
* Select a fleet. Fleet window shows.
* Unselect it.
* Select it again. Fleet window doesn't show.
### Notes
* Happens both with player's fleets and with monsters.
* Closing the game and reopening resets the behavior (i.e. each fleet can be selected once and have its window shown), which is effectively a workaround, albeit a very clumsy one.
* Moving/resizing a Fleet Window and closing it doesn't save its position/size (another fleet's window will open at the default position and size).
* I've tried reverting recent commits which affect FleetWnd.cpp or FleetWnd.h and recompiling, to no avail.

**Comment by geoffthemedio** [comment] 2017-11-16 16:28
I would guess this is related to https://github.com/freeorion/freeorion/pull/1857

**Comment by Vezzra** [comment] 2017-11-16 17:02
@cpeosphoros, can you narrow down which commit introduced the issue for you?

**Comment by geoffthemedio** [comment] 2017-11-16 20:39
Workaround: Press escape. 

More detail: click on a fleet icon to (fail at trying to) open it. Press escape. Click the fleet icon again to open the fleets window.

When you press escape, the selection highlighting of the fleet icon on the map should go away, after which clicking the icon again should work.

**Comment by Vezzra** [comment] 2017-11-17 10:50
I can reproduce this issue on OSX. I can also confirm the workaround @geoffthemedio suggested works.

The issue indeed has been introduced by #1857, so, @wheals, can you take a look at this? While it's not actually game-breaking, this is still a quite serious UI bug, and needs to be fixed ASAP.

**Comment by cpeosphoros** [comment] 2017-11-17 11:07
@geoffthemedio Thanks for the workaround. Sometimes it takes more than one Esc for it to work, but it works.

**Comment by geoffthemedio** [comment] 2017-11-17 12:17
If you've opened other windows since closing the broken FleetWnd, it could take multiple escapes.

**Closed as completed** 2017-11-25 11:26 UTC
Labels: category:bug, component:UI, status:resolved
