### ISSUE TITLE
Evacuation will evacuate a new colony

### ISSUE THREAD

**Issue by l29ah** [freeorion/freeorion#950] opened 2016-09-04 22:52 UTC
- start http://dump.bitcheese.net/files/furyfub/bug-colony.mps as L29Ah
- scrap evacuation at (already evacuated) Navi 5 I
- colonize Navi 5 I with the colony ship hanging there
- end turn
- it will vanish the next turn and evacuation will still be there, so it will be wasted

**Comment by Vezzra** [comment] 2016-09-05 17:23
Well, that's not actually a bug, but, lets say, expected behaviour. When you issue the scrap command, the building gets _marked_ for scrapping, the actual scrapping occurs during turn execution. The colonizing command works the same way - you issue the command, actual command execution occurs during turn execution.

If you issue both commands on the same turn, the order in which those commands are executed matters. Obviously colonizing and the effects of the Evacuation building happen before scrapping, so your pop gets evacuated before the building is scrapped.

You need to wait a turn before you colonize that planet.

I don't know if that issue can be fixed at all. Of course we could try to change the order in which things are done during turn execution, but that will probably lead to other issues, where yet another order would be preferable. I doubt that you can come up with an ordering that will be optimal for all possible different settings/situations.

But I don't want to dismiss this as wontfix right away, maybe others can offer more insight what can possibly done here.

**Comment by l29ah** [comment] 2016-09-05 17:26
Is there an article where i can read about the order of order executions?

**Comment by l29ah** [comment] 2016-09-05 17:30
Also why isn't the evacuation get auto-scrapped the turn it evacuates all the population?

**Comment by geoffthemedio** [comment] 2016-09-05 18:03
See: https://github.com/freeorion/freeorion/blob/master/server/ServerApp.cpp#L2820

**Comment by l29ah** [comment] 2016-09-06 03:56
I wonder if i should make a pedia article on this.

**Comment by MatGB** [comment] 2016-09-06 04:10
It would make sense to expand the Evacuation and Concentration Camp articles a bit—note that it's not a problem for the outpost building method of colonising, and we're trying to encourage that method over colonise by ship.

The turn order is displayed in the message window, invasions and colonisation happen first, before pretty much everything, and effects are processed near the end. Building scrapping, IIRC, happens before effects—it might be possible now we have a priority system to have the buildings destroy themselves on the turn they complete but I've not looked into trying.

**Comment by l29ah** [comment] 2016-09-06 04:20
On Mon, Sep 05, 2016 at 09:10:25PM -0700, Mat Bowles wrote:

> It would make sense to expand the Evacuation and Concentration Camp articles a bit—note that it's not a problem for the outpost building method of colonising, and we're trying to encourage that method over colonise by ship.

Colonizing by ship is very useful sometimes because it consumes one turn instead of 6+ with the building.

## 

()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by Vezzra** [comment] 2016-09-07 09:57
> Colonizing by ship is very useful sometimes because it consumes one turn instead of 6+ with the building.

Not really, because the colony ship takes much longer to build than an outpost ship. Usually build time for colony ship should be the same as for an outpost ship + colony building.

The build time for the colony bilding only gets higher if the "source colony" (that's a colony with the same species as the colony building you're producing) is very far away, to account for the travel time a colony ship would have needed.

So, normally using a colony ship shouldn't save you time (at least not much).

**Comment by l29ah** [comment] 2016-09-07 14:02
On Wed, Sep 07, 2016 at 02:57:38AM -0700, Vezzra wrote:

> > Colonizing by ship is very useful sometimes because it consumes one turn instead of 6+ with the building.
> 
> Not really, because the colony ship takes much longer to build than an outpost ship. Usually build time for colony ship should be the same as for an outpost ship + colony building.

Yes really, because sometimes you need to colonize that planet NOW and have time to prepare for this, in an assault for instance. Insta-colonies are useful as they provide you with some nasty focuses like psychogenic domination and protection, and give you the ability to build stargates, and have more troops.
Or, in my case, it is faster to build a colony ship while depopulating a planet to repopulate it later.

## 

()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by Vezzra** [comment] 2016-09-08 08:26
Fair enough, I hadn't these special cases in mind. Although some of those (psychgenic domination, protection, stargates) should be available immediately on conquered colonies too, having a few colony ships around certainly gives you more flexibility.

Btw, this reminds me that we need to do more about what's possible with colonies you just conquered. Being able to psycho-dominate enemy ships for you doesn't seem right...

**Comment by Voker57** [comment] 2016-09-09 16:55
> I don't know if that issue can be fixed at all. 

How about removing the building abuse like colonies, evacuation and concentration camp remnants and implementing special mechanics for that kind of stuff?

**Comment by Vezzra** [comment] 2016-09-11 11:09
I've some ideas to replace things like Evacuation and Concentration Camps with "influence" projects, once the basic framework for the new influence resource and influence colony upkeep is in place.

Keeping the colony buildings however makes much sense to me - building up a new colony should cost PP, and buildings are perfect for that.

One idea that has come up though is to have a second kind of "projects" that can be "built" and cost PP, which could replace all those buildings that only serve the purpose of executing some one-time effects and then destroy themselves (like terraforming etc.). Because a building actually should be something you produce and that is supposed to stay and have a continuous effect or provide some function, like stargates, industrial centers etc.

So there are actually some ideas floating around that might address what you're asking for.

**Closed as completed** 2017-02-12 16:03 UTC
Labels: category:bug, component:content scripting, status:resolved

**Comment by l29ah** [comment] 2017-02-12 17:25
:(

**Comment by Vezzra** [comment] 2017-02-12 18:57
Sorry, but when I reviewed this issue and the discussion above I got the impression that everyone more or less accepted that while certainly not ideal, the Evacuation building works as intended, and we just forgot to close this issue.

Scrapping Evacuation, then wait one turn before recolonizing is an easy enough workaround, and the Evacuation building is probably going to be replaced by an influence project anyway, at which point we can take care that this issue doesn't happen anymore.

Fixing this issue now by getting the building work looks unreasonably complicated, AFAICT this would require tweaking the order in which things get done in the effects execution code, and that sounds awfully messy.

Not worth the trouble for something that's is likely to be replaced at some point. I hope you can live with the less than ideal way how things work currently in the meantime.

**Comment by l29ah** [comment] 2017-02-12 18:58
On Sun, Feb 12, 2017 at 10:57:46AM -0800, Vezzra wrote:
> Sorry, but when I reviewed this issue and the discussion above I got the impression that everyone more or less accepted that while certainly not ideal, the Evacuation building works as intended, and we just forgot to close this issue.
> 
> Scrapping Evacuation, then wait one turn before recolonizing is an easy enough workaround, and the Evacuation building is probably going to be replaced by an influence project anyway, at which point we can take care that this issue doesn't happen anymore.
> 
> Fixing this issue now by getting the building work looks unreasonably complicated, AFAICT this would require tweaking the order in which things get done in the effects execution code, and that sounds awfully messy.
> 
> Not worth the trouble for something that's is likely to be replaced at some point. I hope you can live with the less than ideal way how things work currently in the meantime.

Sounds good, thanks!

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by l29ah** [comment] 2021-07-01 00:08
So, what were these influence ideas, again?

**Comment by Vezzra** [comment] 2021-07-04 08:22
Well, as stated in the old posts above, the idea is still to replace e.g. the Evacuation building by an influence project (that will cost IP instead of PP). Influence projects won't be part of the first 0.5 release though, as that would be too much. In 0.5, only the fundamental mechanics, the new Influence resource, colony influence upkeep and government/policies will be implemented.

In the following releases, influence projects will be added (maybe already in 0.5.1). So, you still need a bit more patience, but we're definitely closer to finally getting there. 😉

**Comment by agrrr3** [comment] 2021-07-06 19:04
Note from a users perspective that I would expect the building to vanish in the same turn that depopulation happens. I tried out by using the current value - what happens is that the building vanishes but the population grows instead of being set to zero. I guess that does not work as we have effect evaluation happening twice and in the second pass the evacuation building is already gone, so normal population growth happens.

Note that it should be possible to check for the age of the colony and if it is higher than the age of the evacuation building the building could be destroyed and the minus two population effect could be prevented from happening...

**Comment by Vezzra** [comment] 2021-07-11 10:04
Ok, #3514 has been merged which is supposed to fix this issue, so I'm changing "won't fix" to "resolved" and the milestone to 0.5.

**Comment by Vezzra** [comment] 2021-07-11 10:06
@l29ah, can you check if #3514 really fixed the issue for you (the fix should be in the next test builds) and report back?
