### ISSUE TITLE
Piloting skill does not affect direct weapon damage

### ISSUE THREAD

**Issue by Blue-Award** [freeorion/freeorion#4604] opened 2023-07-07 14:57 UTC
Bug Report
==========

Environment
-----------
* **FreeOrion Version**: 2023-07-04 d2b1f58
* **Fetched as** 
  * Weekly development build

Description
-----------

Direct weapon fire doesn't seem to be affected by piloting skill. E.g. Eaxaw's mass drivers or lasers etc do not have increased power, and coversely Gysache's do not have decreased power.

It affects fighters' damage, though.

Steps to reproduce
------------------
You can start game with Eaxaw or Gysache and look at the starting frigates. Their damage matches "generic"/average output, rather above/below average

**Comment by Blue-Award** [comment] 2023-07-07 14:59
My guess would be changes related to fixing flanking etc. have introduced this

**Comment by agrrr3** [comment] 2023-07-08 10:07
> My guess would be changes related to fixing flanking 

you mean #4557 - yeah, possible; i a vaguely remember looking at the species effect, but maybe not (or not at the end of the implementation)


some testcases to check if fixing this:

- defensive and offensive flanking work out of supply
- md2 upgrade happens only in supply
- flux lance, arc disruptor, flak, md1/md2 have the expected values in the ship designer
- two stationary ships out of supply increase their stats with flanking
- research Laser-2 does not increase
- unapplying flanking policy makes damages drop to previous values
- flying into supply upgrades laser damage
- applying flanking increases damage on top of tech damage


edit: notes...
 2023-06-12.a13baa603 2023-06-14 (367) 
 snap download freeorion --revision 367
 2023-06-27.1b21f9b98 2023-07-02 (369)  -- first weekly with #4557 merged
 i can confirm the breakage happened inbetween

**Comment by agrrr3** [comment] 2023-07-08 12:40
Ok, the problem was that in my change I override the capacities' max meters, but the effect evaluation order concerning those was like this:
- default cumulative effects from backend (if not NoDefaultCapacityEffects) (prio 100, i think these are always executed first)
- cumulative effects from species trait (prio 100, species)
- overriding (prio 100, tech)
so basically i erased the species' effects . My effects result in the same value from the backend, so that was not a problem just not necessary.

We could fix this by lowering the prio of all the species weapon effects', but I rather apply my effect only for the NoDefaultCapacityEffects parts which request it (looking at you SR_WEAPON_0_1)

**Comment by MichaelCourtney** [comment] 2023-07-09 12:47
Have not tested yet. Just leaving to fix this in release as well

**Comment by agrrr3** [comment] 2023-07-09 13:04
> Have not tested yet. Just leaving to fix this in release as well

you mean we should merge without more testing? (OK for me)

or did you mean we also check if we need to fix this in the 0.5 release?  - i just checked; no problem in 0.5

**Comment by MichaelCourtney** [comment] 2023-07-09 13:18
> > Have not tested yet. Just leaving to fix this in release as well
> 
> you mean we should merge without more testing? (OK for me)
> 
> or did you mean we also check if we need to fix this in the 0.5 release? - i just checked; no problem in 0.5

I meant there was a fix in release branch that neaded checking as well. If you have checked release it doesn't (because you checked). As far as merging without checking, current is broken, so merging without checking, I won't make a call. It's either broken more or its fixed.

**Closed as completed** 2023-07-22 21:06 UTC
Labels: category:bug, component:content scripting, status:resolved
