### ISSUE TITLE
Unable to create game save file

### ISSUE THREAD

**Issue by jdtrouble** [freeorion/freeorion#1061] opened 2016-10-18 13:46 UTC
### Environment
- **FreeOrion Version**:
  FreeOrion v0.4.6 build 2016-09-16.49fe9123
- **Operating System**:
  Windows 10 x64
- **Graphic card used**:
  Geforce (I can give you exact model if needed, when I get home)
  GeForce Quadro K1000M
- **Fetched as** 
  - Binary release
### Description

I am unable to create  good save files. I get the error message "Error when writing to save file" and the file itself is 0KB when it is created. The game has been working fine up until now, but around turn 319 (when the save file gets bigger than 17MB) is when I start seeing the error. The game cannot autosave, and I cannot manually save.

I made my last save file public using OneDrive (I don't know if it'll allow you to access it without a login, I apologize in advance if that is a problem):
https://1drv.ms/u/s!AhMcDvp4p7eThtF8qh_oUZFURceaVQ
- Windows: %APPDATA%\FreeOrion
  FYI, GitHub doesn't allow me to attach log files
  [freeorion.txt](https://github.com/freeorion/freeorion/files/536403/freeorion.txt)
  [freeoriond.txt](https://github.com/freeorion/freeorion/files/536404/freeoriond.txt)
### Expected Result

Can be able to save the game at any time.
### Steps to reproduce
- First step.
  Enjoy FreeOrion for days, saving regularly
- Issue occurs.
  Observe error message. Any attempt to save the game after that fails.

**Comment by geoffthemedio** [comment] 2016-10-18 18:13
Try starting the game, going into the options and enabling Create Binary Save Files, then load the last working save, then resave to a new file or end turn to cause an autosave.

**Comment by jdtrouble** [comment] 2016-10-19 03:15
That seemed to have fixed it. If I have further issues I'll let you know. Thanks!

**Comment by Vezzra** [comment] 2016-10-19 16:45
Obviously there is still something botched with the compressed XML serialization, we're getting these reports repeatedly. I've tagged the solution provided as "workaround" for now, but that needs to be properly fixed of course.

So, leave that issue open or close it and create another one more specifically for the problem that compressed XML serialization does not work with large saves?

**Comment by geoffthemedio** [comment] 2016-10-19 17:50
Based on the log, nothing is "botched" other than the XML serialization output text needs too much memory to store. Might be OK to write it all directly to disk, but allocating enough memory apparently fails on @jdtrouble 's system. From the log:

```
2016-10-18 09:27:49.500036 [debug] Server : Allocating buffers for XML serialization...
2016-10-18 09:27:49.500036 [debug] Server : Unable to preallocate full serialization buffers. Attempting serialization with dynamic buffer allocation.
```

If XML serializing all the gamestate data actually needs that much RAM (it tries to allocate 512 MB), then failures in the serialization are going to start happening (eg. if empires keep remembering everything they've ever seen).

Alternatives include automatically falling back to binary when XML fails.

**Comment by Vezzra** [comment] 2016-10-19 19:02
Ok, I see... but whatever the reason, I think this needs to be fixed. Whether by reducing the amount of (stale) data the game generates, or writing directly to disk, or whatever.

> Alternatives include automatically falling back to binary when XML fails.

Correct me if I'm wrong, but isn't the same serialization code used to exchange the gamestate between client and server? Which means, won't that kind of fallback cause problems where client and server are on different platforms that are not "binary compatible" (so to speak)?

**Comment by geoffthemedio** [comment] 2016-10-19 19:12
If writing directly to disk without using an in-memory buffer was possible, I wouldn't be using an in memory buffer. The problem is that serialization goes in multiple steps: saving data to XML format text, compressing that XML text, and writing the compressed text to disk. Both the first and second steps need in-memory buffers to write to. The first needs a big buffer.

The same code generates XML text for client-server and pre-saving serialization, but the data that code is passed is different, and the compression step isn't done for client-server messages, and adding a fallback for save-to-disk wouldn't mean there would be one for client-server messages.

Also, since the server to client messages contain only one empire's gamestate knowledge, they will generally be smaller than the full gamestate save information, so are less likely to have problems. Furthermore, the lack of the compression step means a different type of container can be used to hold the serialized data, which might be more flexible, though I'm not sure about that... possibly it just never showed problems due to the first point.

**Comment by Vezzra** [comment] 2016-10-19 19:22
Ok... so I guess the fallback on binary serialization for saving when XML fails should work sufficiently well and be comparatively easy to implement...?

**Comment by geoffthemedio** [comment] 2016-10-19 19:32
Would have to try it to see.

**Comment by Vezzra** [comment] 2017-02-12 15:28
What's the status on this? Anymore we can do to improve things?

**Comment by geoffthemedio** [comment] 2017-02-12 17:28
I may have implemented the binary fallback. Don't have a suitable test case though...

**Comment by Vezzra** [comment] 2017-02-12 19:02
Hm, we could close the issue as "resolved" then, and should the issue turn up again, reopen or create a new issue. Better than having this one hanging around for the next couple of years...?

**Comment by geoffthemedio** [comment] 2017-02-12 19:39
Preferably someone who regularly tests big enough games to run into save errors could test..

**Comment by geoffthemedio** [comment] 2017-02-13 11:03
Reference: https://github.com/freeorion/freeorion/commit/ad372e88d485b6572af7ed055962b974e4cb946c

Not sure if it works. Might need to clear or reopen the output stream after a partial XML save before trying again as binary.

Might also be possible to split up the XML serialization compression a bit... instead of writing the whole gamestate to one archive and compressing it all, then having to load it all to uncompress, it may be possible to write and compress parts of the gamestate seaprate, like the empires, the universe, species, combat logs...

https://github.com/freeorion/freeorion/blob/master/server/SaveLoad.cpp#L199

this might not be of much help though, as I suspect the universe is generally far bigger than the rest. Subdividing further would require going into the universe's serialization code and making it compression-aware, which would complicate matters more.

**Comment by geoffthemedio** [comment] 2017-03-28 12:03
I think this is resolved by binary serialization fallback. If not, then it can be reopened or a new issue created.

**Closed as completed by geoffthemedio** 2017-03-28 12:03 UTC
Labels: category:bug, status:resolved, component:internal

**Comment by Vezzra** [comment] 2017-03-28 14:56
Should that still be considered a "workaround" resolution, or shall we remove that tag?
