### ISSUE TITLE
Monsters not being blockaded properly

### ISSUE THREAD

**Issue by MatGB** [freeorion/freeorion#1237] opened 2017-01-22 23:30 UTC
### Environment
* **FreeOrion Version**: d9352da
* **Operating System**: Linux
  * Compiled from source

### Description
Multiple occasions last few games I've had monsters 'escape' one of my fleets in situations where they would normally be blockaded and prevented from moving. As it's normally been a Fighter carrier I've thought it due to that but I've just had a Large Juggernaut escape from 3 heavily armed Sentient Hull flagships when it definitely should have been pinned down.

### Expected Result
Monsters that arrive in a system already containing armed aggressive vessels should be prevented from leaving while those vessels remain.

**Comment by dbenage-cx** [comment] 2017-01-23 17:35
Is movement of a fleet supposed to be prevented to/from a blockaded system?  I've only seen such from monsters attempting to leave combat (as noted in expected result), even though they do not have any script definition keeping them from moving.

So curious if a previous c++ bug was fixed leading to this condition, or if fleets are supposed to be hard-coded to prevent leaving such systems.  I suspect the first and we just need to add a check in the monster move macros.

**Comment by MatGB** [comment] 2017-01-28 16:50
One of the better explanations given was by Dilvish [here](http://www.freeorion.org/forum/viewtopic.php?p=76985#p76985), you're supposed to be able to block anything that arrives after you, including both neutrals and enemies. Plus, monsters are supposed to be blocked if they arrive at the same time as you. There was a bug that sometimes you could block monsters trying to leave if you arrived first: that appeared to have been a turn processing glitch that was never intended but was useful.

According to this write up static monsters were also meant to blockade an attacking fleet from moving past for one complete turn,t hat never used to work but it is now working: I'm being blockaded by monsters when I'm not sure I should be, but not able to blockade them even when I definitely should be.

Hunting down Large Juggernauts was hard enough before, if you can't pin them and other annoyances like Large Krills down then it becomes an exercise in frustration waiting so many turns for them to complete their next move.

**Comment by dbenage-cx** [comment] 2017-01-29 02:45
Thank you for searching out the post and the explanation.

**Comment by Vezzra** [comment] 2017-01-29 15:10
IIRC the mechanism should work as follows: if a fleet arrives at a system that is already occupied by hostile armed forces, it can only retreat from that system by the starlane it entered it. That is hardcoded in the backend engine.

What I'm not sure is if that applied equally to space monsters, or if those are meant to be blocked from *any* retreat, regardless which starlane they try to take, or if they too can retreat by the starlane by which they originally entered the system.

But I'm quite sure there hasn't been any special movement scripting in the space monsters content scripts regarding this mechanic. It's all done in the C++ code.

**Comment by MatGB** [comment] 2017-02-01 00:42
It has been up to recently that monsters were completely blockaded, as were any new ships created after the blockading side arrived, so newly created floaters and drones as well as built ships by an enemy world couldn't get away, that's no longer the case (exception: you can't blockade something you can't see, in theory).

Also now able to confirm that monsters are blockading attacking ships entirely except for their initial entry route regardless of time spent fighting them: that's also new, Dilvish said it was meant to be for a whole turn, that wasn't previously the case, but you now can't get passed at all unless you're stealthed, nor can you leave by a different route. 

Don't like this as an unintended change, could live with it but when you could get passed if you survived a turn you could build armoured outposters or even colony ships to get past low level sentries, now you can't, which can be a problem on some layouts: I'd prefer it if the supposed intended mechanic were in place.

**Comment by Vezzra** [comment] 2017-02-02 13:13
Hm, I see. Stuff (ships/monsters) that gets created in a blockaded system should definitely not be able to leave at all, I agree. Also, being able to get past a space monster after surviving one turn of combat is important too.

Space monsters not being able to leave even via the starlane they entered is debatable, but I also agree that shouldn't happen as an unintended change. After all, I can see the point where pinning down space monsters can become annoying and un-fun if they could escape that way.

Can you find out which commit introduced these changes of the blockade mechanic?

**Comment by MatGB** [comment] 2017-02-04 23:52
> Can you find out which commit introduced these changes of the blockade mechanic?

I don't know where to start with that sort of thing, sorry.

**Comment by dbenage-cx** [comment] 2017-02-05 00:55
Suspect some of this may be due to `ALL_EMPIRES` having a different meaning depending on the context.  From an earlier brief look into this, unowned ships were being blockaded but only from the starlane(s) an owned ship arrived from(so they pick another route, which is open for the empire `ALL_EMPIRES`).

I'm not sure this is worth spending much effort on until after the current changes wrt `PathFinder` are merged.  If no-one else finds it before, I will try to track down the change after finishing some other work.

**Comment by MatGB** [comment] 2017-02-05 01:09
> I'm not sure this is worth spending much effort on until after the current changes wrt PathFinder are merged.

Fair enough. If the general area has ongoing work then fixing it with/after that makes sense.

It is, however, causing trouble for the AI, which expects to be able to get past monsters and tries to do so, I've only observed shielded ships get blocked by Maintenance Ships, but what I haven't observed is probably worse than that given it sometimes tries to force past Sentinels. Consequently it's basically Release blocking, either it needs fixing or the AI will need updating, the former is preferable.

**Comment by Vezzra** [comment] 2017-02-05 09:39
> I don't know where to start with that sort of thing, sorry.

Well, more or less by using `git bisect`, which means building FO a lot of times and then test run each build. As each test run takes some time because you need to recreate a proper "test situation", this will get exceedingly time consuming, and I guess your FO time budget won't allow that...

Trying to track the issue down and fix it after ongoing work in this area has been finished sounds reasonable.

> Consequently it's basically Release blocking, either it needs fixing or the AI will need updating, the former is preferable.

Yep, pretty much this.

**Comment by LGM-Doyle** [comment] 2017-02-05 13:26
I don't think that it was caused by the pathfinder work since this issue was started on Jan 22nd and the initial pathfinder changes were only merged Jan 31st, https://github.com/freeorion/freeorion/pull/1249. 

Is the intended behavior to treat `ALL_EMPIRES` fleets differently than regular empire fleets, so that `ALL_EMPIRES` fleets can't blockade and can't leave a blockaded system?  

Regular empire fleets, if I remember correctly, if they have arrived first in a system are considered blockading and prevent enemies from leaving except along the same path from which they came.  

Both the behaviors that @MatGB observed of not being able to push past Maintenance ships and monsters being able to leave along the path they arrive is just the mechanics working the same as an empire on empire blockade.

Possibly the bug was introduced by a change that regularized fleet behavior.

@dbenage-cx unless you want to fix this, I could work on it so that it hopefully is fixed faster before all the pathfinder PRs are merged?

**Comment by Vezzra** [comment] 2017-02-05 13:39
> Is the intended behavior to treat ALL_EMPIRES fleets differently than regular empire fleets, so that ALL_EMPIRES fleets can't blockade and can't leave a blockaded system?

If I understand correctly, more or less this. With the amendmend that ALL_EMPIRE fleets block regular fleets for one turn (so the latter can't just pass through and avoid combat completely, but have to survive at least one turn of combat before they can continue on).

**Comment by dbenage-cx** [comment] 2017-02-05 17:15
@LGM-Doyle please feel free, the only thought I had here was to possibly define guard the debug messages (testing this is a pain ;) ).

**Comment by MatGB** [comment] 2017-02-06 01:04
Also related: before, if you had armed ships survive a round with a guard monster then supply would propagate in/through, this is no longer the case. 

Especially important with Maintenance Ships in the early game.

**Comment by geoffthemedio** [comment] 2017-02-06 15:00
> Also related: before, if you had armed ships survive a round with a guard monster then supply would propagate in/through, this is no longer the case.

This is probably related. The supply propagation code bases what systems an empire can propagate supply into partly on

**Comment by Vezzra** [comment] 2017-02-06 15:56
@geoffthemedio, why did you close this issue...?

**Comment by geoffthemedio** [comment] 2017-02-06 16:24
I don't remember doing so... misclick apparently.

**Comment by Vezzra** [comment] 2017-02-10 14:42
Well, #1287 which is a fix for this issue has been merged, so actually we can close this now as resolved I guess.

**Comment by Vezzra** [comment] 2017-02-10 14:42
Fixed by #1287

**Closed as completed by Vezzra** 2017-02-10 14:42 UTC
Labels: category:bug, component:game mechanic, status:resolved
