### ISSUE TITLE
Conquered planet (outpost) claims BLD_COL_EXOBOT is present

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#4049] opened 2022-08-08 13:14 UTC
Bug Report
==========

Environment
-----------
* **FreeOrion Version**: 2022-07-26 9439c8d
* **Operating System**: Don't know, I loaded the save file on Ubuntu 20.04.
* **Fetched as** 
  * Compiled from source

Description
-----------
Build 2022-07-26.9439c8d. I have conquered a system from AI that had Cynos homeworld and another planet (I landed with troops on the cynos planet). Cynos can produce ships but can't colonize planets. So here I go, hauling an organic outpost ship and establishing outpost to then change into a colony. But when trying to build colony, I get "(FAILED) that doesn't contain an object that is a BLD_COL_EXOBOT building". I tried abandoning the outpost, and establishing it again, same thing. Now I am in the process of trying to build a colony ship instead of outpost ship and seeing if that fixes that (otherwise probably need that "super tester takeover" thing if I want to claim that planet after all?)

https://www.freeorion.org/forum/viewtopic.php?p=113277#p113277

Expected Result
---------------
Can build colony buildings on outpost

Steps to reproduce
------------------

Load attached save file and check out the Xenon (alpha or beta, can't remember) system with one outpost and one Cynos colony.
Colony buildings are unavailable.

[cannot_build_colony_on_xenon_T331.zip](https://github.com/freeorion/freeorion/files/9281918/cannot_build_colony_on_xenon_T331.zip)

**Comment by Grummel7** [comment] 2022-08-08 18:22
Adding buildings to the object list, you can see that the planet indeed contains a Exobot Colony Building, which still belongs to the empire Solidarity.
This is mysterious:
How did you get the planet, but not the building?
Why can you not see the building?
An why does the building still exist? Every colony building should self-destroy 2 turns after being finished.

You conquered the planet in 314 and in 318 its population died out (Evacuation?)
Do you have an (auto)-save a few turns before 314, so we can see the planet how it looked like before you conquered it?

**Comment by geoffthemedio** [comment] 2022-08-08 22:13
> An why does the building still exist?

Probably it doesn't still exist on the server, but the game is remembering the last state of the object that the player's empire was aware of, and the client assumes that it will still be there but just isn't visible currently. the orders are rejected client side due to the building, but would go through if the client let the player issue them. I guess the situation can only arise if the planet is captured on the turn the colony building exists? Or maybe the player saw the building on the one turn it existed, then never saw it again, since it destroyed itself, but the player didn't have visibility of it on the turn after it was seen, so didn't get informed of the destruction?

**Comment by Grummel7** [comment] 2022-08-09 07:00
> Probably it doesn't still exist on the server, but the game is remembering the last state of the object that the player's empire was aware of, and the client assumes that it will still be there but just isn't visible currently...

Good point, I can actually reproduce the effect now: When you see a colony building, fly away the scout that provides the visibility -> The building remains in the list.

**Comment by Grummel7** [comment] 2022-08-09 14:59
@geoffthemedio Can we change the scripting context in the client, so that it only uses visible objects?

Most scripts only are affected by objects that are visible (or would be, if they still existed). The only exception that comes to my mind are scrying spheres. Blocking an action because we know that something that would block it existed in the past simply sounds wrong. Everything we are not seeing now, might be gone.

**Comment by geoffthemedio** [comment] 2022-08-09 15:11
No, but visibility tests could be added to the problematic location or enqueue conditions.

**Comment by Grummel7** [comment] 2022-08-09 20:58
This could potentially affect almost every building, but by modifying ENQUEUE_BUILD_ONE_PER_PLANET most should be covered.

**Comment by o01eg** [comment] 2022-08-10 06:19
Maybe after take over the planet consider full visibility of planet and automatically clean ghost buildings?

**Comment by agrrr3** [comment] 2022-08-10 11:07
I think visibility is not the problem here - ownership should be checked instead (so prevent building if you have such a building on the planet/in the queue). The colony buildings do not check for ownership, but should.

**Comment by Grummel7** [comment] 2022-08-10 16:54
No building checks for ownership of other buildings on the same planet. The scripts all assume that all buildings on the planet belong to the planets owner.
Which is true so far, at least for all real buildings, that's why this issue hasn't been identified so far, although I guess it exists for quite some time. Of course so far the issue would have shown only if somebody tried to build exactly the same building.

**Comment by Grummel7** [comment] 2022-08-10 17:01
> Maybe after take over the planet consider full visibility of planet and automatically clean ghost buildings?

If we can do this, I would prefer it over my PR.

**Comment by agrrr3** [comment] 2022-08-11 09:02
> No building checks for ownership of other buildings on the same planet. The scripts all assume that all buildings on the planet belong to the planets owner.

They mostly all use the same macro(s). Adding a check there should be easy and is going the right path (it opens up the possibility of actually having foreign buildings on the planet).

**Comment by Oberlus** [comment] 2022-08-11 09:15
For reference:

On (why not) removing ownership of buildings.
https://www.freeorion.org/forum/viewtopic.php?f=9&t=12361

Old suggestions for embassy building (within IMO too complex suggestions):
https://www.freeorion.org/forum/viewtopic.php?f=6&t=11467&p=99480&hilit=embassy#p99480
https://www.freeorion.org/forum/viewtopic.php?f=6&t=11258&p=96306&hilit=embassy#p96306

**Comment by Grummel7** [comment] 2022-08-11 14:23
Things get a bit messed up now. I once suggested to remove ownership of buildings, but that has nothing to do with this issue.

We have a problem that a building that once existed prevents a player from building the same. This is not a problem of who owns that old building, which does in fact not even exist anymore. Checking the (presumed) ownership of buildings is only a way to tell the script to ignore these ghosts.

If we add embassies, they will follow different rules, e.g. most likely more than one player will be able to build one on the same planet, regardless of whether players will see other embassies or not.

**Closed as completed** 2022-08-21 21:28 UTC
Labels: category:bug, component:game mechanic, status:resolved
