### ISSUE TITLE
Weapon ship parts broken

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion#420] opened 2015-12-08 18:58 UTC
All weapon ship parts seem to have strength 0 now. On the pedia pages of the parts the correct strength is shown, but all ships and space monsters display 0 for all their weapon parts.

**Comment by MatGB** [comment] 2015-12-09 02:13
I'm playing with a compile made at [eaabf3d](https://github.com/freeorion/freeorion/commit/eaabf3d526a59cda9f6cb885525af235261760d4) but with a fully up to date default folder and they're working fine for me. The only thing that touches the backend code committed since is [Merge pull request #413 from freeorion/List-Drag-Drop-Reworking · freeorion/freeorion@7d56884](https://github.com/freeorion/freeorion/commit/7d568848ad716889557026ba5389e77d679d0385) so either it's something in there or it's Mac specific or there's something weirder going on, I'm going to make a new compile in a bit to see.

**Comment by MatGB** [comment] 2015-12-09 03:54
Basically confirmed, compiling current trunk gives me the same problems, creating a new branch off of [a573641](https://github.com/freeorion/freeorion/commit/a5736419a6869ab24edf6516bbca01026660b087) then cherry picking the more recent default-folder-only changes gives me a fully functioning game, so it's something in @geoffthemedio's list drag/drop rework.

**Comment by geoffthemedio** [comment] 2015-12-09 10:38
Try:

```
@@ -578,9 +580,9 @@ void Ship::ResetPairedActiveMeters() {

     for (PartMeterMap::iterator it = m_part_meters.begin(); it != m_part_meters.end(); ++it) {
        if (it->first.first == METER_CAPACITY) {
-            // special case for capacity... if it has an associated max capacity, reset it, otherwise don't
+            // special case for capacity... if it has an associated max capacity, don't reset it, otherwise do
             PartMeterMap::iterator max_it = m_part_meters.find(std::make_pair(METER_MAX_CAPACITY, it->first.second));
-            if (max_it != m_part_meters.end())
+            if (max_it == m_part_meters.end())
                 it->second.ResetCurrent();
         }
     }
```

**Comment by Vezzra** [comment] 2015-12-09 10:55
Yep, that seems to fix the issue (only did a brief test on OSX, but all weapon parts show the expected strength again).

**Closed as completed** 2015-12-10 12:26 UTC
Labels: category:bug
