### ISSUE TITLE
Another UI quirk (Objects window)

### ISSUE THREAD

**Issue by cpeosphoros** [freeorion/freeorion#517] opened 2016-03-12 00:47 UTC
When Objects window overlaps the Planets panel, clicking on the Object windows "goes through" and the panel gets clicked.

If I scroll the Planets panel so no actual Planet is under the area I'm clicking (just the background of the panel), clicking Objects works fine.

"$ git status
On branch master
Your branch is up-to-date with 'origin/master'."

**Comment by Vezzra** [comment] 2016-03-18 12:50
I can't reproduce that issue on any of my platforms - neither Windows, nor OSX, nor Linux (Ubuntu 15.10). Can you explain in more detail what exactly you're doing to get that behavior? Maybe provide a screenshot?

**Comment by cpeosphoros** [comment] 2016-03-18 22:19
I'm not able to reproduce it in my latest build, either.

I've noticed a small change in the behavior of the Objects view scrolling (previously it kept a line when scrolling, now it doesn't). Possibly that change had the side effect of making the bug I reported earlier go away. All for the better.

**Comment by Vezzra** [comment] 2016-03-19 18:18
Ok, in that case I'm closing this. We can always reopen should the issue turn up again.

**Closed as completed by Vezzra** 2016-03-19 18:18 UTC
Labels: category:bug
