### ISSUE TITLE
monsters fleet stuck in space

### ISSUE THREAD

**Issue by krator44** [freeorion/freeorion#1130] opened 2016-11-25 18:07 UTC
### Environment

* **FreeOrion Version**: 0.4.6+ HEAD [build 2016-11-23.b56dfe7c0]
* **Operating System**: gentoo linux
* **Graphic card used**: intel HD graphics 520 (rev 07)
* **Fetched as** 
  * Compiled from source 

### Description

monsters fleet is stuck in the middle of a space lane with 3 turns to arrive at its destination star. the fleet doesn't move no matter how many turns pass, cannot be attacked or destroyed.

### Expected Result

monsters fleet arrives at its destination.

### Steps to reproduce

its difficult to reproduce but what happened might have been that the fleet decided to divide into two fleets in space and one of them got stuck. (see http://www.freeorion.org/forum/viewtopic.php?f=28&t=9718)

**Comment by TheSilentOne1** [comment] 2016-11-25 18:18
Could you be seeing a sensor ghost? The scanlines sometimes can be difficult to spot. Could you provide a screenshot?

**Comment by krator44** [comment] 2016-11-25 18:41
![screenshot from 2016-11-25 13-32-16](https://cloud.githubusercontent.com/assets/5042951/20633449/a8474aa2-b314-11e6-9dc5-a2f93433fa48.png)

i think you're right - thats what it looks like.

attaching screenshot.

**Comment by MatGB** [comment] 2016-11-25 23:52
That's a ghost sensor image (look at the fleet icon, there are scanlines there), you did see it at some point, probably because of a Derelict Scout, but can no longer (your detection is 10, Floaters can't be seen until you've researched Active Radar).

It will disappear when you have visibility of its position with detection of more than 15, Active Radar will put it up to 30. Alternatively, right click on the fleet and it'll give you the option to dismiss the sensor ghost.

I'm still of the opinion we need to improve the UI with regards to stuff you can't see, but I have no clue how to do this, ideas very welcome.

Closing as wontfix as there isn't actually a problem, it's working as intended, but we need to work on ways to improve the info given to players to prevent this confusion.

**Closed as completed by MatGB** 2016-11-25 23:52 UTC
Labels: status:invalid, status:won't fix, component:UI
