### ISSUE TITLE
Cannot use non-latin letters in input boxes

### ISSUE THREAD

**Issue by l29ah** [freeorion/freeorion#832] opened 2016-08-02 17:33 UTC
For instance, when i try to type cyrillic letters in the player name box, it shows spaces instead.

**Comment by Cjkjvfnby** [comment] 2016-08-02 20:29
Reproduces for me.  win7 x64, en stringtable

**Comment by dbenage-cx** [comment] 2016-08-02 23:51
With pasted text, looks like it stops after `u+03ff` (Greek and Coptic), with the exception of `u+1e00` - `u+1efb` (Latin Extended Additional).

Edit: "it stops" referring to not displaying the correct character, displaying a seemingly blank space instead.  So the unicode ranges `u+0400` - `u+1dff` and `u+1efc`\+ do not display correctly.

**Comment by geoffthemedio** [comment] 2016-08-03 01:00
I suspect that it hasn't loaded the necessary code pages of the font due to those pages not appearing in the stringtable. Try adding characters from them to the stringtable (in a commented out line is fine) and restarting the game?

**Comment by geoffthemedio** [comment] 2016-08-03 01:01
The newest test builds should have some lines near the start of freeorion.log indicating what code pages are loaded:

```
2016-07-29 14:22:05.157025 [debug] Client : loading 11 charsets for current stringtable characters
2016-07-29 14:22:05.157025 [debug] Client : Loading 11 Unicode charsets: Basic Latin, Latin-1 Supplement, Latin Extended-A, Latin Extended-B, Combining Diacritical Marks, Greek and Coptic, Latin Extended Additional, General Punctuation, Mathematical Operators, Geometric Shapes, Supplemental Arrows-A, 
```

**Comment by geoffthemedio** [comment] 2016-08-03 01:03
Switching to a suitable stringtable and restarting should have similar effects, if you haven't done so already.

**Comment by l29ah** [comment] 2016-08-03 01:05
On Tue, Aug 02, 2016 at 06:00:41PM -0700, Geoff wrote:

> I suspect that it hasn't loaded the necessary code pages of the font due to those pages not appearing in the stringtable. Try adding characters from them to the stringtable (in a commented out line is fine) and restarting the game?

Yes, it did the job.
Also there's a funny problem: when i add "☺" using XCompose, it shows mojibake, but it works as intended if i copy-paste it.

## 

()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by Vezzra** [comment] 2016-08-03 08:10
Ok, seems simple to fix, a comment line containing characters of all relevant code pages could probably be added to all stringtable files, that should take care of the issue, right?

Tagging this for release.

**Comment by geoffthemedio** [comment] 2016-08-04 08:06
What are "all relevant code pages? Every possible language for which there is a stringtable? Do we even know all possibly needed pages for every relevant language? What if people want to post random other characters in text?

Having a way to tell it to load more code pages dynamically might be useful.

**Comment by Vezzra** [comment] 2016-08-04 08:19
> Every possible language for which there is a stringtable?

This? AFAIK that would mean the cyrillic alphabet, the greek has to be included anyway, and all the other languages (for which we have a stringtable) use the latin alphabet. For a quick fix for the release that should be sufficient?

> Having a way to tell it to load more code pages dynamically might be useful.

Of course that's the preferable solution. But unless it's reasonably simple to implement (which I doubt), that should be a post release project.

**Comment by dbenage-cx** [comment] 2016-08-11 22:56
Appears that some characters will not render correctly regardless (or there is a flaw in my attempt to verify).

Pasting the string `肛門オーガズム` into en.txt and using a capable font, this string is still renders as blank spaces in chat (copy/paste) and encyclopedia articles.

Added the above string into `SD_SCOUT_2_DESC` and replaced `font`, `font-bold`, and `font-title` with `path\to\NanumGothic.ttf`

```
Client : Loading 12 Unicode charsets: Basic Latin, Latin-1 Supplement, Latin Extended-A, Latin Extended-B, Combining Diacritical Marks, Greek and Coptic, Latin Extended Additional, General Punctuation, Mathematical Operators, Supplemental Arrows-A, Katakana, CJK Unified Ideographs, 
```

Font used was NanumGothic 3.020, which supports each of these characters (The first is CJK Unified, the remaining are Katakana).

**Comment by geoffthemedio** [comment] 2016-08-15 03:30
I get some of those characters rendering after switching to NanumGothic as the main font, putting that string into en.txt in a comment, and then pasting it into the player name text box...

![asianchars](https://cloud.githubusercontent.com/assets/11386908/17655000/e0d168b6-62e3-11e6-98cd-c910f67a6b5d.png)

Looking at the font textures from the options UI tab show font textures button, I see the Katakana, but not the other character textures.

**Comment by geoffthemedio** [comment] 2016-08-15 12:25
![preview](https://cloud.githubusercontent.com/assets/11386908/17664395/ad0d88d4-632e-11e6-847e-3ba6005f7e48.png)

Looking at the preview on the NanumGothic download page, those same characters aren't present in the font, so I don't think it's an issue with FreeOrion...

**Comment by l29ah** [comment] 2016-08-15 12:29
Why doesn't freeorion get the xft font substitution feature and ignores fontconfig?

## 

()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by adrianbroher** [comment] 2016-08-15 12:34
> Why doesn't freeorion get the xft font substitution feature and ignores fontconfig?

Because we don't use system fonts.

**Comment by l29ah** [comment] 2016-08-15 12:43
Can this be helped?

**Comment by geoffthemedio** [comment] 2016-08-19 09:36
I added some comments to the english / default stringtable that should force some extra codepages to load, regardless of what langauge is actually in use or what is in its stringtable. If there are other potentially useful codepages to add sample characters from, please do so or comment...

https://github.com/freeorion/freeorion/commit/a8371771d8771f661ba57c760e03b83e8b5a8643

**Comment by Vezzra** [comment] 2016-08-19 11:15
@l29ah, @Cjkjvfnby, can you report back if these changes @geoffthemedio committed solved the problem for you? So we'll know if we can close this issue.

**Comment by l29ah** [comment] 2016-08-19 12:59
On Fri, Aug 19, 2016 at 04:15:04AM -0700, Vezzra wrote:

> @l29ah, @Cjkjvfnby, can you report back if these changes @geoffthemedio committed solved the problem for you? So we'll know if we can close this issue.

Cyrillic input works, compose key sequences are broken regardless the target charset (even symbols like α produce garbage instead).

## 

()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by geoffthemedio** [comment] 2016-08-20 06:20
There was substantial discussion about deadkeys here: https://github.com/freeorion/freeorion/issues/701

**Comment by Vezzra** [comment] 2016-08-20 18:30
I guess we won't be able to provide a more comprehensive fix, at least in time for 0.4.6, correct? So when I'm going through all the issues tomorrow, I'll change the milestone to "post 0.4.6" unless someone objects.

**Comment by Vezzra** [comment] 2016-08-21 12:02
No objections so far, so tagging this for post release.

**Comment by Vezzra** [comment] 2017-02-12 14:17
What's the status on this issue? Has everything been addressed, or can we do anything about the things that haven't? Is any work being done on this?

**Comment by l29ah** [comment] 2017-02-12 14:21
I still can't write smileys ☹
otoh, α via compose key works

**Comment by l29ah** [comment] 2017-02-12 14:23
freeorion should be able to fall back to system fonts in case the supplied one doesn't contain the character to be shown instead of producing spaces, like all the sane desktop apps

**Comment by geoffthemedio** [comment] 2017-02-15 14:16
Lack of emoticon / emoji support is a separate issue so it sounds like this is resolved...

**Comment by l29ah** [comment] 2017-02-15 14:18
On Wed, Feb 15, 2017 at 06:16:05AM -0800, Geoff wrote:
> Lack of emoticon / emoji support is a separate issue so it sounds like this is resolved...

It's not an "emoticon", it's an unicode character, just like 本語.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by geoffthemedio** [comment] 2017-02-15 14:24
> It's not an "emoticon", it's an unicode character, just like 本語.

That's why I wrote "/ emoji".

**Comment by geoffthemedio** [comment] 2017-02-15 14:37
@Ouaz Do you know if the current Roboto font file should contain emoji characters and if it dorsn't, can they be added?

**Comment by dbenage-cx** [comment] 2017-02-15 21:34
Do not know if they can be added to Roboto, it has no emoji glyphs (`Miscellaneous Symbols` cp).  At a minimum the basic smileface ☺ `U+263a` works with Deja-vu and addition to stringtable.

Possible to change valid but not found glyphs to the special character � `U+fffd`, instead of blank space? (or even just unknown but not a space/nb space)

**Comment by geoffthemedio** [comment] 2017-02-15 23:44
There is already code that attempts to do that, but apparently fails:
https://github.com/freeorion/freeorion/blob/master/GG/src/Font.cpp#L2034

**Comment by dbenage-cx** [comment] 2017-02-16 06:36
Looks like index is set to 0 in these cases.

Catching it prior(e.g. [diff](https://gist.github.com/dbenage-cx/b2841d4f3c8ee9609197d10b21558a88) ) massively reduces game speed.
(little time to continue looking atm)

**Comment by geoffthemedio** [comment] 2017-02-16 07:01
Not sure what you mean, but it does just advance the rendering position in cases where it can't find a glyph: https://github.com/freeorion/freeorion/blob/master/GG/src/Font.cpp#L1173

In some other cases it can render a `?`, (not a `�`) but I'm not sure when/ how.

**Comment by adrianbroher** [comment] 2017-02-16 11:05
> Possible to change valid but not found glyphs to the special character � U+fffd, instead of blank space? (or even just unknown but not a space/nb space)

That's the wrong use of U+FFFD.  You use that codepoint whenever the character cannot be represented in unicode (eg. the value is above U+10FFFF or if a UTF-8 encoding starts with 10xxxxxx).  You want to use '.notdef', which is located at the index 0 of the glyph table.

https://www.microsoft.com/typography/otspec/recom.htm
http://stackoverflow.com/questions/13730544/is-there-a-glyph-not-found-character

**Comment by Ouaz** [comment] 2017-02-17 18:31
@geoffthemedio 
> Do you know if the current Roboto font file should contain emoji characters and if it dorsn't, can they be added?

@dbenage-cx 
> Do not know if they can be added to Roboto, it has no emoji glyphs (Miscellaneous Symbols cp)

I think I can add them manually with FontForge as I did with glyphs U+27F2 and U+27F3 (https://github.com/freeorion/freeorion/commit/8b534fd94796713cdc658e26372b74d5eb45daa8). I have to check, though.

But somebody has to give me a list of which emoji characters (with unicode value) need to be added. ^^

**Comment by MatGB** [comment] 2017-02-17 18:57
My preference is none, Emoji are an abomination unto Nuggan, but if others are happy to put in the work I don't strongly object, I just don't think the work is worth it.

**Comment by Ouaz** [comment] 2017-02-17 19:55
Ok, I checked then tested... et voilà.

For `u+263a` :

![fo_emoji](https://cloud.githubusercontent.com/assets/11946570/23080861/c195ef9c-f552-11e6-839a-c0332176ad06.png)

But I'm with MatGB on this... Emoji are kind of useless in FO, no? But I'm OK to add some other missing glyphs (mainly for unsupported languages in the specific Roboto 2.001101 font file we use in FO), if it's requested.

**Comment by dbenage-cx** [comment] 2017-02-17 21:37
> Emoji are an *Abomination unto Nuggan*

++ (though the basic ones are very useful in some situations)
If they are desired, should probably aim for a complete set, e.g. [v1.1](http://www.unicode.org/emoji/charts/emoji-versions.html) (78 glyphs)

**Comment by geoffthemedio** [comment] 2017-03-28 11:57
So is this resolved? At least the original problem of non-latin characters not working?

Adding emoji support is presumably a separate issue.

**Comment by l29ah** [comment] 2017-03-28 13:01
Well, the stringtable hack works for russian letters, but the inability to use system fonts sucks.

**Comment by geoffthemedio** [comment] 2017-03-28 13:20
system fonts is a separate issue

**Comment by Vezzra** [comment] 2017-10-29 16:45
@l29ah, @geoffthemedio, judging by your last comments here I get the impression that this issue should be closed as resolved - right? The remaining complaints seem to be separate issues? So, can we close this?

**Closed as completed** 2017-10-29 22:03 UTC
Labels: category:bug, component:UI, status:resolved
