### ISSUE TITLE
Drag-'n-drop ships causes SegFault.

### ISSUE THREAD

**Issue by Hacklin** [freeorion/freeorion#441] opened 2016-01-12 12:09 UTC
[bug_dragNDropSegFault-20160109.zip](https://github.com/freeorion/freeorion/files/87226/bug_dragNDropSegFault-20160109.zip)

See bug_dragNDropSegFault-20160109.txt inside the attched zip file

**Comment by geoffthemedio** [comment] 2016-01-12 12:11
Duplicate of:
https://github.com/freeorion/freeorion/issues/397

**Closed as completed by geoffthemedio** 2016-01-12 12:11 UTC
Labels: category:bug, status:duplicate

**Comment by Hacklin** [comment] 2016-01-12 12:28
Yes, you're right.
Sorry should have checked for previous bugs.

The attached zip file contain a Backtrace, a SaveGame and in bug_dragNDropSegFault-20160109.txt instructions on how to reproduce it (every time in my setup).

Looking at the backtrace I think the invalid window coordinates may stem from changing the parent-child relationship.

From my experience when removing a parent-child relationship
1) the removeChild() of the parent should check that the parent of the child being removed is itself (if not, the child->setParent() of the child should not be called) and
2) before a child calls  parent->removeChild() from its setParent(), the child should have changed/removed its parent in case the parent calls the childs setParent() from parent->removeChild().

**Comment by geoffthemedio** [comment] 2016-01-12 12:49
If you think you know how to fix it, please try and report back if it works...

**Comment by geoffthemedio** [comment] 2016-01-13 03:42
2) doesn't apply, but I made some tweaks including some related to 1)

https://github.com/freeorion/freeorion/commit/8e365a4737496a5dd36499e7581187132471becd
