### ISSUE TITLE
Per-player system commenting

### ISSUE THREAD

**Issue by l29ah** [freeorion/freeorion#909] opened 2016-08-23 16:06 UTC
When multiple games are being played or a game is being played over a lot of load-save cycles, it is hard to keep track of ones' intentions. It would be nice to be able to rename/comment/mark systems to make the previous intentions more readily available.

**Comment by wheals** [comment] 2016-08-23 16:35
Duplicate of #590?

**Closed as completed** 2016-08-23 16:47 UTC
Labels: status:duplicate, category:feature, component:UI
