### ISSUE TITLE
Loading ship designs from file doesn't work

### ISSUE THREAD

**Issue by l29ah** [freeorion/freeorion#921] opened 2016-08-25 22:38 UTC
I've created a design, used `Save Design File`, it created a file with the design in `~/.config/freeorion/shipdesigns/Дестроер.txt`, yet i don't see the design neither in `Finished`, nor in the `Saved` tabs in a new game.

**Comment by Voker57** [comment] 2016-08-26 12:43
works for me, but freeorion saved them in ~/.local/share/freeorion/shipdesigns/

**Comment by dbenage-cx** [comment] 2016-08-26 23:40
### Environment
- **FreeOrion Version**: 0.4.5+
- **Operating System**: Fedora 24
- **Graphic card used**: n/a
- **Fetched as** 
  - Compiled from source e017c3f

### Description

Ship designs saved during the current session are not available as saved designs without client restart.  These designs are also not loaded as pre-defined designs if a new game is started within the same session.
Closing the client and restarting resolves this issue.

### Expected Result

Saving a new ship design should result in immediate listing in the design window 'Saved' tab.
Saved designs should be available as pre-defined designs for new games in the current session (pending the option is set to the default state of True/1)

### Steps to reproduce
- Start new game with `--auto-add-saved-designs 1`
- Create and save a new ship design
- Design is not listed on the `Saved` tab
- Resign current game and start a new game.
- Previous design is not listed in `Saved` tab, nor available as pre-defined design.

**Comment by Vezzra** [comment] 2016-08-29 08:48
@geoffthemedio, why did you change the category from "bug" to "feature request"?

**Comment by geoffthemedio** [comment] 2016-08-29 08:55
Because it works as is when you restart the game. It's not a bug, it's a missing feature.

**Comment by Vezzra** [comment] 2016-08-29 09:33
Only if requiring a restart of the app is intended by the current implementation, which I guess it is judging by your statement. Otherwise it _would_ be a bug, as just staring a new game (without restarting the program) should be sufficient.

Although @Voker57's comment seems to indicate that for him this actually works - just starting a new game gives him the saved designs, so how does that work?

**Comment by geoffthemedio** [comment] 2016-08-29 09:44
Not "intended", but not completely broken.

I suspect @Voker57's comment is misleading.

**Comment by Vezzra** [comment] 2016-08-29 09:57
> Not "intended", but not completely broken.

That's still a bug and not a feature request then in my eyes. Either the current implementation is expected to require a program restart, or it's expected that just starting a new game should be sufficient. In the first case it's not a bug, in the latter case it is (IMO).

If we want to distinguish between "completely broken" things and just "impaired" things, we could introduce something like "category:glitch".

**Comment by Voker57** [comment] 2016-08-29 15:26
@geoffthemedio is right, I didn't understand the issue. Designs work if I restart the game.

**Comment by geoffthemedio** [comment] 2016-08-29 16:17
We can multi-categorize, I suppose.

**Comment by Vezzra** [comment] 2016-08-30 08:25
> @geoffthemedio is right, I didn't understand the issue. Designs work if I restart the game.

Ah, ok. Good, makes things simpler.

> We can multi-categorize, I suppose.

I guess I can live with that 😉

**Comment by LGM-Doyle** [comment] 2017-08-14 16:26
Fixed by [ Allow editing and deletion of saved ship designs within app ](https://github.com/freeorion/freeorion/projects/4)

**Closed as completed by LGM-Doyle** 2017-08-14 16:26 UTC
Labels: category:bug, component:UI, status:resolved
