### ISSUE TITLE
Link errors on OSX and Linux [build 04a69b7]

### ISSUE THREAD

**Issue by mtdew365** [freeorion/freeorion#475] opened 2016-02-08 01:09 UTC
Version  04a69b7  will not compile on Fedora 23.  I have an automated script that runs and I am now receiving an error....

[100%] Linking CXX executable ../../freeorion
CMakeFiles/freeorion.dir/**/**/UI/ObjectListWnd.cpp.o: In function `boost::detail::function::function_obj_invoker3<(anonymous namespace)::CustomRowCmp, bool, GG::ListBox::Row const&, GG::ListBox::Row const&, unsigned long>::invoke(boost::detail::function::function_buffer&, GG::ListBox::Row const&, GG::ListBox::Row const&, unsigned long)':
ObjectListWnd.cpp:(.text+0x2918): undefined reference to`boost::locale::generator::generate(std::**cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
ObjectListWnd.cpp:(.text+0x2975): undefined reference to `boost::locale::generator::generator()'
ObjectListWnd.cpp:(.text+0x298e): undefined reference to`boost::locale::generator::~generator()'
collect2: error: ld returned 1 exit status
client/human/CMakeFiles/freeorion.dir/build.make:1848: recipe for target 'freeorion' failed
make[2]: **\* [freeorion] Error 1
CMakeFiles/Makefile2:454: recipe for target 'client/human/CMakeFiles/freeorion.dir/all' failed
make[1]: **\* [client/human/CMakeFiles/freeorion.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: **\* [all] Error 2
Install Free Orion
Building v0.4.5+ build 2016-02-07.04a69b7
[  0%] Built target freeorionversion
[ 24%] Built target freeorioncommon
[ 40%] Built target GiGi
[ 41%] Built target GiGiSDL
[ 61%] Built target freeorionparse
[ 67%] Built target freeoriond
[ 73%] Built target freeorionca
[ 73%] Linking CXX executable ../../freeorion
CMakeFiles/freeorion.dir/**/__/UI/ObjectListWnd.cpp.o: In function `boost::detail::function::function_obj_invoker3<(anonymous namespace)::CustomRowCmp, bool, GG::ListBox::Row const&, GG::ListBox::Row const&, unsigned long>::invoke(boost::detail::function::function_buffer&, GG::ListBox::Row const&, GG::ListBox::Row const&, unsigned long)':
ObjectListWnd.cpp:(.text+0x2918): undefined reference to`boost::locale::generator::generate(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
ObjectListWnd.cpp:(.text+0x2975): undefined reference to `boost::locale::generator::generator()'
ObjectListWnd.cpp:(.text+0x298e): undefined reference to`boost::locale::generator::~generator()'
collect2: error: ld returned 1 exit status
client/human/CMakeFiles/freeorion.dir/build.make:1848: recipe for target 'freeorion' failed
make[2]: **\* [freeorion] Error 1
CMakeFiles/Makefile2:454: recipe for target 'client/human/CMakeFiles/freeorion.dir/all' failed
make[1]: **\* [client/human/CMakeFiles/freeorion.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: **\* [all] Error 2

Thanks.

**Comment by geoffthemedio** [comment] 2016-02-08 07:32
Try adjusting the include at the top of ObjectListWnd.cpp:

```
-#include <boost/locale.hpp>
+#include <boost/locale/generator.hpp>
```

**Comment by Scara83** [comment] 2016-02-08 08:39
Hey,
got the same Problem with the build on Linux Mint Distro. The adjustion didn't help, it's building the ObjectListWnd.cpp new but still the same message...

**Comment by geoffthemedio** [comment] 2016-02-08 08:58
Try

```
static std::locale loc = gen.operator()("en_US.UTF-8");
```

on line 1682

**Comment by Vezzra** [comment] 2016-02-08 09:29
All that won't help, it's not a compile error but a link error we're dealing with here. I've got the same issue on OSX, the problem is that you need to link the boost locale library. On OSX I also had to add the iconv system library, as boost locale depends on that (on OSX at least).

Don't know if on Linux it would be sufficient to just add the boost locale lib to the required libraries, and cmake will pull in the required dependencies automatically. Can't test ATM, because I'm not at home and have no access to my Linux system.

Will look into it and report back.

**Comment by Vezzra** [comment] 2016-02-08 09:32
@adrianbroher, if you can assist, feel free to do so... :smiley:

**Comment by Vezzra** [comment] 2016-02-08 10:05
Ok, I've created PR #476 which adds boost locale to the list of required boost libraries.

@mtdew365, @Scara83, most likely @MatGB and all others of our Linux folks too, pls try to build with that PR and report back.

**Comment by Scara83** [comment] 2016-02-08 11:06
That solved it here =)

**Comment by adrianbroher** [comment] 2016-02-08 14:05
> All that won't help, it's not a compile error but a link error we're dealing with here.

You're right.

> Don't know if on Linux it would be sufficient to just add the boost locale lib to the required libraries, and cmake will pull in the required dependencies automatically.

The cmake boost find module should know and append all required subdependencies.

**Comment by mtdew365** [comment] 2016-02-08 14:19
That works for me :)  As a side note.  I erased and downloaded the project again from git and the CMakeLists.txt was the "old" version.  After I added "locale" in the dependencies it compiled.  Thanks

**Comment by Vezzra** [comment] 2016-02-08 14:30
> As a side note. I erased and downloaded the project again from git and the CMakeLists.txt was the "old" version. After I added "locale" in the dependencies it compiled.

That would be because the fix hasn't been merged into master yet, it's provided by the PR I referred to above (#476). To test the fix, you'd need to build the PR - but just applying the required change manually works too of course :wink:

**Closed as completed** 2016-02-08 14:32 UTC
Labels: category:bug

**Comment by Vezzra** [comment] 2016-02-08 14:35
Considered fixed.
