### ISSUE TITLE
Numpad Keys Reposition Cursor and Add Number Text

### ISSUE THREAD

**Issue by luiges90** [freeorion/freeorion#161] opened 2015-07-01 09:16 UTC
Version: build 2015-06-24.6652f69
OS: Windows 7, 32 bit
1. Go to design panel
2. Choose an existing design or create a new one
3. Attempt to rename the ship, and hit the numpad 7 button
4. For no reason, the cursor go to the beginning to the text field, putting the character 7 there :confused: 

Also, for numpad 4 key, the cursor will move one character before

No issue for the number keys above the letters, just the numpad :confused:

**Comment by MatGB** [comment] 2015-07-01 09:20
I _think_ this is a known issue, to check, try this: alt+tab out of the game, turn numlock off, then alt+tab back in, turn numlock back on again.

Retry what you were doing. If the numpad now behaves as expected then it's the SDL issue I discovered last week, if it _doesn't_ then it's a different issue.

**Comment by luiges90** [comment] 2015-07-01 09:21
@MatGB Yes it fixes the issue, didn't expect a quick reply :smile:

**Comment by MatGB** [comment] 2015-07-01 09:27
I'd just finished a game and switched back to email, OK, good, we know what the cause is, have a workaround and at some point someone can look at it properly.

**Comment by Dilvish-fo** [comment] 2015-07-09 18:05
I had investigated this when it came up for Mat earlier-- it is a known SDL bug (I believe they've fixed it for windows now, but for some reason were still having trouble with Linux; I'm not sure about OSX).
Since our only plan (at least currently) is simply to wait for the SDL folks to fix it, seems to me we should close this out.

**Comment by Vezzra** [comment] 2015-07-10 11:35
> Since our only plan (at least currently) is simply to wait for the SDL folks to fix it, seems to me we should close this out.

Agreed.

**Closed as completed** 2015-07-11 18:56 UTC
Labels: category:bug, status:won't fix, status:workaround
