### ISSUE TITLE
Split/Duplicate production gives incorrect batch sizes

### ISSUE THREAD

**Issue by MatGB** [freeorion/freeorion#1610] opened 2017-06-20 01:53 UTC
### Environment
* **FreeOrion Version**: 8b96e3a
* **Operating System**: Linux
  * Compiled from source

### Description
When using either the split or duplicate commands introduced for production in 051a839 the batch size isn't honoured, so an order of 10 troop ships becomes an order of 1 troop ship.

### Expected Result
Batch sizes should be honoured if you split or duplicate a production item.

**Comment by geoffthemedio** [comment] 2017-06-20 12:53
Hopefully fixed by https://github.com/freeorion/freeorion/commit/8962f2365250f9337f3a5d6e1c8d3df825584841

**Closed as completed by geoffthemedio** 2017-06-20 12:53 UTC
Labels: category:bug, component:UI, status:resolved

**Comment by Vezzra** [comment] 2017-06-21 13:47
From my brief testing of the last test builds it looks like the fix works as intended.
