### ISSUE TITLE
Improve stockpiling input warning (old waste warning)

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#2175] opened 2018-06-23 20:16 UTC
Currently, a red icon appears when the Imperial Stockpile is getting more than 3x the current _maximum use_. If less than that is getting into the IS, the only warning for that is the green numbers besides the IS symbol in the upper menu.

I'm used to rely on that red icon to remind me to check the production queue. With Sly I've ran into the situation where all my production output was smaller than 3x _maximum use_, so I never get the red icon, and if I miss the green numbers of positive stockpile input I my pass several turns until I realise I'm putting my whole production into the IS.

I expect something more striking than the mentioned green numbers. I suggest the following:
- Trigger the red icon when current input > 3x maximum use OR current stockpile > 5x maximum use.
- Show a yellow icon (akin to the red one) when there is any positive input to the IS but hte red icon is not in place.

**Comment by Vezzra** [comment] 2018-06-24 11:45
While not technically a bug, the issue is still a quite serious problem for gameplay. Not enough to consider it release blocking, but enough to allow a fix into 0.4.8 if provided in time.

**Comment by Vezzra** [comment] 2018-07-12 15:52
Addressed by #2200.

**Closed as completed by Vezzra** 2018-07-12 15:52 UTC
Labels: component:UI, status:resolved, category:tweak
