### ISSUE TITLE
Something is bottlenecking FPS for no reason. Please tighten up thread timings or sleep timers or whatever

### ISSUE THREAD

**Issue by afwbkbc** [freeorion/freeorion#1360] opened 2017-02-22 15:05 UTC
Ok, so there definetely seem to be programming bugs that won't FPS go over certain value.
My hardware is barely used - CPU like 1%, GPU 1-2%, disk ~0%, etc.
Still, I can't get my FPS over 190 (192 was highest I got and it only happened once. So there's definetely SOMETHING that introduces delay (some timers probably, or maybe mutexes).
This drives me mad.
It should be so simple to find all timer interval values and reduce them, no? Or maybe remove them to allow maximum FPS that system is capable of.
Will you accept optimisation pull requests from me if I do it? Game is barely playable now.

**Comment by afwbkbc** [comment] 2017-02-22 15:08
Specs: AMD FX-9590 / ASUS STRIX GeForce GTX1070 / 2 x Samsung 850 Pro 512GB SSD / Corsair Vengeance Pro 32GB 2400MHz DDR3 / ASUS Crosshair V Formula-Z

**Comment by afwbkbc** [comment] 2017-02-22 15:14
http://dump.bitcheese.net/images/zezupid/2017220175627.jpg

**Comment by geoffthemedio** [comment] 2017-02-22 15:15
> Will you accept optimisation pull requests from me...

Maybe. But this is a duplicate of https://github.com/freeorion/freeorion/issues/1291

**Closed as completed by geoffthemedio** 2017-02-22 15:15 UTC
Labels: status:duplicate, component:UI, category:tweak

**Comment by Vezzra** [comment] 2017-02-23 08:32
> Still, I can't get my FPS over 190 [...]
This drives me mad. [...]
Game is barely playable now.

Do you have any idea how ridiculous that sounds...? I'm still waiting for an explanation just how having a FPS of 190 makes the game "barely playable", when everyone else is able to play the game with a *fraction* of that just perfectly fine. But I have the sneaking suspicion that won't happen even when hell freezes over.

But, as @geoffthemedio already said, we may be willing to accept a PR from you, provided it actually does offer an improvement, doesn't break things, and you stay responsive for code review and requests for changes.

Just dumping an PR on us and never getting back to questions/input from our side won't work.
