### ISSUE TITLE
"Cancel Giving Ship" crashes game

### ISSUE THREAD

**Issue by agrrr3** [freeorion/freeorion#3625] opened 2021-12-24 05:38 UTC
current slow game 018, turn 68, 2021-11-27.cd8138ea3 (snap rev 269) .

Ophiuchus "give fleet to - wobbly" on Deemi beta.  Then turned, and then wanted to change the commands. Doing "Cancel Giving Ship", the game dumps one back to console

**Comment by geoffthemedio** [comment] 2021-12-24 09:13
I can't replicate this on Windows in a local multiplayer game.

**Comment by geoffthemedio** [comment] 2022-04-17 10:01
this might have been fixed by recent switching to scoped signals. If you can somehow test again, that would be helpful...

**Comment by geoffthemedio** [comment] 2022-10-09 11:13
@agrrr3 can you check the status of this?

**Comment by l29ah** [comment] 2023-08-01 17:25
Reproduces for me on ae870ac7b0ed5dbe0b27116126c83680f4b121f5

**Comment by geoffthemedio** [comment] 2023-08-01 20:09
stack trace for the crash might be helpful...

**Comment by o01eg** [comment] 2024-09-15 11:13
@geoffthemedio  Version **2024-09-02.84e9cd9**

```
Thread 1 "freeorion" received signal SIGSEGV, Segmentation fault.
0x00007ffff3cca0a4 in std::_Rb_tree_increment(std::_Rb_tree_node_base const*) () from /lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007ffff3cca0a4 in std::_Rb_tree_increment(std::_Rb_tree_node_base const*) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00005555559f6dc9 in std::_Rb_tree_const_iterator<std::pair<int const, std::shared_ptr<Order> > >::operator++ (this=0x7fffffffa960) at /usr/include/c++/14/bits/stl_tree.h:364
#2  0x0000555555c33543 in operator() (__closure=0x7fffad325620) at /home/oleg/devel/freeorion/UI/FleetWnd.cpp:3721
#3  0x0000555555c408a8 in std::__invoke_impl<void, FleetWnd::FleetRightClicked(GG::ListBox::iterator, GG::Pt, GG::Flags<GG::ModKey>)::<lambda()>&>(std::__invoke_other, struct {...} &) (
    __f=...) at /usr/include/c++/14/bits/invoke.h:61
#4  0x0000555555c3e5a0 in std::__invoke_r<void, FleetWnd::FleetRightClicked(GG::ListBox::iterator, GG::Pt, GG::Flags<GG::ModKey>)::<lambda()>&>(struct {...} &) (__fn=...)
    at /usr/include/c++/14/bits/invoke.h:111
#5  0x0000555555c3b2a3 in std::_Function_handler<void(), FleetWnd::FleetRightClicked(GG::ListBox::iterator, GG::Pt, GG::Flags<GG::ModKey>)::<lambda()> >::_M_invoke(const std::_Any_data &)
    (__functor=...) at /usr/include/c++/14/bits/std_function.h:290
#6  0x0000555555879af2 in std::function<void()>::operator() (this=0x7fffad4a61a0) at /usr/include/c++/14/bits/std_function.h:591
#7  0x00007ffff540837b in GG::PopupMenu::Run (this=0x7fffad38b560) at /home/oleg/devel/freeorion/GG/src/Menu.cpp:248
#8  0x0000555555c3528e in FleetWnd::FleetRightClicked (this=0x5555581d6cd0, it=std::shared_ptr<GG::ListBox::Row> (use count 4, weak count 3) = {...}, pt=..., modkeys=...)
    at /home/oleg/devel/freeorion/UI/FleetWnd.cpp:3752
#9  0x0000555555c8e0a2 in boost::_mfi::mf3<void, FleetWnd, std::_List_iterator<std::shared_ptr<GG::ListBox::Row> >, GG::Pt, GG::Flags<GG::ModKey> >::operator() (this=0x7fffaccf8980, 
    p=0x5555581d6cd0, a1=std::shared_ptr<GG::ListBox::Row> (use count 4, weak count 3) = {...}, a2=..., a3=...) at /usr/include/boost/bind/mem_fn_template.hpp:393
#10 0x0000555555c8ab6f in boost::_bi::list4<boost::_bi::value<FleetWnd*>, boost::arg<1>, boost::arg<2>, boost::arg<3> >::operator()<boost::_mfi::mf3<void, FleetWnd, std::_List_iterator<std::shared_ptr<GG::ListBox::Row> >, GG::Pt, GG::Flags<GG::ModKey> >, boost::_bi::rrlist3<std::_List_iterator<std::shared_ptr<GG::ListBox::Row> >, GG::Pt, GG::Flags<GG::ModKey> > > (
    this=0x7fffaccf8990, f=..., a=...) at /usr/include/boost/bind/bind.hpp:443
#11 0x0000555555c85e97 in boost::_bi::bind_t<void, boost::_mfi::mf3<void, FleetWnd, std::_List_iterator<std::shared_ptr<GG::ListBox::Row> >, GG::Pt, GG::Flags<GG::ModKey> >, boost::_bi::list4<boost::_bi::value<FleetWnd*>, boost::arg<1>, boost::arg<2>, boost::arg<3> > >::operator()<std::_List_iterator<std::shared_ptr<GG::ListBox::Row> >, GG::Pt, GG::Flags<GG::ModKey> > (
    this=0x7fffaccf8980, a1=..., a2=..., a3=...) at /usr/include/boost/bind/bind.hpp:1310
#12 0x0000555555c80038 in boost::detail::function::void_function_obj_invoker3<boost::_bi::bind_t<void, boost::_mfi::mf3<void, FleetWnd, std::_List_iterator<std::shared_ptr<GG::ListBox::Row> >, GG::Pt, GG::Flags<GG::ModKey> >, boost::_bi::list4<boost::_bi::value<FleetWnd*>, boost::arg<1>, boost::arg<2>, boost::arg<3> > >, void, std::_List_iterator<std::shared_ptr<GG::ListBox::Row> >, GG::Pt, GG::Flags<GG::ModKey> >::invoke (function_obj_ptr=..., a0=std::shared_ptr<GG::ListBox::Row> (use count 4, weak count 3) = {...}, a1=..., a2=...)
    at /usr/include/boost/function/function_template.hpp:158
#13 0x00007ffff5403139 in boost::function3<void, std::_List_iterator<std::shared_ptr<GG::ListBox::Row> >, GG::Pt, GG::Flags<GG::ModKey> >::operator() (this=0x7fffaccf8978, 
    a0=std::shared_ptr<GG::ListBox::Row> (use count 4, weak count 3) = {...}, a1=..., a2=...) at /usr/include/boost/function/function_template.hpp:771
#14 0x00007ffff5401806 in boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::m_invoke<boost::function<void(std::_List_iterator<std::shared_ptr<GG::ListBox::Row> >, GG::Pt, GG::Flags<GG::ModKey>)>, 0u, 1u, 2u, std::_List_iterator<std::shared_ptr<GG::ListBox::Row> >&, GG::Pt&, GG::Flags<GG::ModKey>&> (this=0x7fffffffba8f, func=..., 
    args=std::tuple containing = {...}) at /usr/include/boost/signals2/detail/variadic_slot_invoker.hpp:105
#15 0x00007ffff53ffd7f in boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::operator()<boost::function<void(std::_List_iterator<std::shared_ptr<GG::ListBox::Row> >, GG::Pt, GG::Flags<GG::ModKey>)>, std::_List_iterator<std::shared_ptr<GG::ListBox::Row> >&, GG::Pt&, GG::Flags<GG::ModKey>&, 3ul> (this=0x7fffffffba8f, func=..., 
    args=std::tuple containing = {...}) at /usr/include/boost/signals2/detail/variadic_slot_invoker.hpp:90
#16 0x00007ffff53fd6ee in boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, std::_List_iterator<std::shared_ptr<GG::ListBox::Row> >, GG::Pt, GG::Flags<GG::ModKey> >::operator()<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void(std::_List_iterator<std::shared_ptr<GG::ListBox::Row> >, GG::Pt, GG::Flags<GG::ModKey>), boost::function<void(std::_List_iterator<std::shared_ptr<GG::ListBox::Row> >, GG::Pt, GG::Flags<GG::ModKey>)> >, boost::signals2::mutex> > > (this=0x7fffffffbe10, connectionBody=...) at /usr/include/boost/signals2/detail/variadic_slot_invoker.hpp:133
#17 0x00007ffff53fa2e6 in boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, std::_List_iterator<std::shared_ptr<GG::ListBox::Row> >, GG::Pt, GG::Flags<GG::ModKey> >, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void(std::_List_iterator<std::shared_ptr<GG::ListBox::Row> >, GG::Pt, GG::Flags<GG::ModKey>), boost::function<void(std::_List_iterator<std::shared_ptr<GG::ListBox::Row> >, GG::Pt, GG::Flags<GG::ModKey>)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void(std::_List_iterator<std::shared_ptr<GG::ListBox::Row> >, GG::Pt, GG::Flags<GG::ModKey>), boost::function<void(std::_List_iterator<std::shared_ptr<GG::ListBox::Row> >, GG::Pt, GG::Flags<GG::ModKey>)> >, boost::signals2::mutex> >::dereference (this=0x7fffffffbb60) at /usr/include/boost/signals2/detail/slot_call_iterator.hpp:110
#18 0x00007ffff53f68d6 in boost::iterators::iterator_core_access::dereference<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, std::_List_iterator<std::shared_ptr<GG::ListBox::Row> >, GG::Pt, GG::Flags<GG::ModKey> >, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void(std::_List_iterator<std::shared_ptr<GG::ListBox::Row> >, GG::Pt, GG::Flags<GG::ModKey>), boost::function<void(std::_List_iterator<std::shared_ptr<GG::ListBox::Row> >, GG::Pt, GG::Flags<GG::ModKey>)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void(std::_List_iterator<std::shared_ptr<GG::ListBox::Row> >, GG::Pt, GG::Flags<GG::ModKey>), bo--Type <RET> for more, q to quit, c to continue without paging--
```

**Comment by o01eg** [comment] 2024-09-16 03:19
It looks like it crashes because of iterator invalidation on removing gift order.

**Comment by geoffthemedio** [comment] 2024-09-21 12:31
I have a commit to hopefully fix this, but no usable internet for a few days...

**Comment by geoffthemedio** [comment] 2024-09-29 07:04
Can you test with #5011 ?

**Comment by o01eg** [comment] 2024-09-29 17:58
@geoffthemedio Yes, it doesn't crash now.

**Closed as completed** 2024-09-29 19:10 UTC
Labels: category:bug, component:UI, component:game mechanic, status:resolved
