### ISSUE TITLE
Hidden ships targetted as non-hidden. Fighters not shooting.

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#2459] opened 2019-06-04 10:46 UTC
### Environment
* **FreeOrion Version**: v0.4.8+ build 2019-06-03.81-93-654.
* **Operating System**: Ubuntu 16.04
  * Compiled from source

Edit: Using build 2019-05-13.bbb72e1 I get the same results.
Edit: I've tested 2019-02-03.23f627b, had to do a new game. I've checked that the stealth problem is also happening there, dunno about fighters not shooting. So it seems the bug is old (no body uses stealth ships?)

### Description
Hidden ships (stealth 105 in the example) are being targetted by enemy ships with not enough detection (50 in the example).
Fighters are not attacking anyone despite the enemies being detected from start.
(Check out screenshot in https://www.freeorion.org/forum/viewtopic.php?f=28&t=11287)

### Expected Result
Ships with stealth>detection should not be targetted unless detected after firing a weapon (or maybe launching fighters).
Fighters should target and damage enemies.

### Steps to reproduce
* Load attached save game (turn 202).
* Press Turn button.
* Combat ensues on system Boros and issue occurs. Check out combat log.

[FreeOrion_Nobody_Nothing_0202_2019-Jun-04 11:42:38.853675.sav.zip](https://github.com/freeorion/freeorion/files/3251874/FreeOrion_Nobody_Nothing_0202_2019-Jun-04.11.42.38.853675.sav.zip)

[freeorion.log](https://github.com/freeorion/freeorion/files/3251914/freeorion.log)

**Comment by agrrr3** [comment] 2019-06-04 19:50
The visibility calculation is off. Empire 18 should not be able to see the Lacerta. Not sure about how neutral perception is intended to work ATM.
One guess -  the problem could arrise through interaction with the neutral third party.
```
21:34:21.618734 [debug] server : CombatSystem.cpp:188 : Initializing CombatInfo object visibility and known objects for empire: -1
...
21:34:21.618918 [debug] server : CombatSystem.cpp:238 : Ship Lacerta visible from aggressive fleet
...
21:34:21.618954 [debug] server : CombatSystem.cpp:188 : Initializing CombatInfo object visibility and known objects for empire: 1
...
21:34:21.619038 [debug] server : CombatSystem.cpp:226 : Ship Lacerta visible from universe state
...
21:34:21.619054 [debug] server : CombatSystem.cpp:188 : Initializing CombatInfo object visibility and known objects for empire: 18
...
21:34:21.619108 [debug] server : CombatSystem.cpp:238 : Ship Lacerta visible from aggressive fleet
```

```
21:34:21.668990 [debug] combat : CombatSystem.cpp:1261 :  Target Lacerta (223915): VIS_PARTIAL_VISIBILITY to monsters and neutrals
21:34:21.668997 [debug] combat : CombatSystem.cpp:1264 :  Target Lacerta (223915): VIS_FULL_VISIBILITY to empire 1
21:34:21.669003 [debug] combat : CombatSystem.cpp:1264 :  Target Lacerta (223915): VIS_PARTIAL_VISIBILITY to empire 18
```

**Comment by agrrr3** [comment] 2019-06-04 20:06
Ok, I have to retract that statement. So probably for a looong time being active made you partial visible (so if you put the Lacerta to passive, it correctly works as a hidden carrier)

Have to have a closer look at the Fighter fighters

**Comment by agrrr3** [comment] 2019-06-04 21:09
Ok, the combat target conditions got overridden by another part. Should be up in some minutes, sorry this did not make it into the weekly build ;)

**Comment by Oberlus** [comment] 2019-06-05 10:51
> The visibility calculation is off. Empire 18 should not be able to see the Lacerta. Not sure about how neutral perception is intended to work ATM.
> One guess - the problem could arrise through interaction with the neutral third party.

In a different game with an older version (2019-02-03.23f627b), I sent a small camouflage asteroid (stealth 45) to a system with colonies and armed ships all from the same empire (detection 30), no field effects. Combat ensued and my ship was targetted from round 1.

> Ok, I have to retract that statement. So probably for a looong time being active made you partial visible (so if you put the Lacerta to passive, it correctly works as a hidden carrier)

Does this mean that for now we can't use hidden armed ships?

**Comment by agrrr3** [comment] 2019-06-06 18:47
I found the introduction of that code and checked that before that introduction stealthy combat worked as expected e.g. in the weekly 2019-01-20.fffde88 it still works. The next weekly 2019-01-27.35c8071         probably does not.

```
$ git blame -L 238,238 -- combat/CombatSystem.cpp
aa7b82dc61 (geoffthemedio 2019-01-18 22:11:55 +0100 238)                                 DebugLogger() << "Ship " << obj->Name() << " visible from aggressive fleet";

    -Reworking initial combat stealth determination and stealth event format.
    -grooming
```
Not sure what was the reason for reworking combat stealth - but i guess it did not went like it was intended.

```
snap refresh freeorion --channel=edge/000409rev3

                 edge/000409rev3  2019-01-20.fffde88        3           2019-07-06T18:22:19.529362
                 edge/000409rev4  2019-01-27.35c8071        4           2019-07-06T18:45:38.745194

```

**Comment by Oberlus** [comment] 2019-06-07 06:24
@geoffthemedio 
Should that commit that Ophiuchus point out be reverted or would you like to fix it yourself?
Sorry if I'm meddling not being a contributor, but I miss my stealth ships :dancer:

**Comment by geoffthemedio** [comment] 2019-06-08 18:55
I don't recall when these changes were made, but it's quite plausible that if a fleet is agressive/controlling its system, then it should have to reveal itself to do so, and thus be visible already on the first round of combat. This doesn't prevent such ships from being used, but they would need to be in passive / hidden mode to be hidden on the first round of combat.

**Comment by agrrr3** [comment] 2019-06-08 21:00
@geoffthemedio You changed that around mid-january this year (somewhen after introducing the combatTargets). I did not see any discussion or announcement about this.
Do you intend we use one cheap extra ship to trigger combat while the others are passive?

**Comment by geoffthemedio** [comment] 2019-06-09 07:38
I wrote that it's plausible, but I don't recall what was intended or why.

**Comment by Oberlus** [comment] 2019-06-09 08:17
> I wrote that it's plausible, but I don't recall what was intended or why.

IMO, current implementation is not good because it requires micromanagement of fleets. If this change is/was supposed to fix some problem regarding stealth and combat (what problem?), then maybe we have to find a better solution.
I'm opening a discussion about this in the forum: https://www.freeorion.org/forum/viewtopic.php?f=6&t=11293

**Comment by geoffthemedio** [comment] 2019-06-09 10:42
Some alternative mechanism would be needed to decide what ships to have initially revealed in combat if ut doesn't depend on galaxy level visibility to an empire. If ships can be map visible but start combat hidden, then there would be cases where a combat will start but nobody can target anything so nothing happens in the combat...

**Comment by Oberlus** [comment] 2019-06-14 06:33
@geoffthemedio Check out this forum thread when you have the time:
https://www.freeorion.org/forum/viewtopic.php?f=6&t=11294

**Comment by agrrr3** [comment] 2019-06-14 17:11
@geoffthemedio maybe the changes were a stab at blockade problems - i think there was some discussion around that in january 

#2343 #2312

**Comment by geoffthemedio** [comment] 2019-09-07 18:39
@Oberlus @agrrr3 https://github.com/freeorion/freeorion/commit/e2b32a3adbd2b714e2953b172c99203b55bc3ee2 adds a rule to control the aggressive fleet combat visibility. Please test and report if this is resolved with that...

**Comment by geoffthemedio** [comment] 2019-09-15 19:25
@Oberlus @agrrr3 bump Is this resolved or partly resolved?

**Comment by Oberlus** [comment] 2019-09-15 23:20
@geoffthemedio I haven't tested it yet. Maybe this week.

**Comment by urshmost** [comment] 2019-09-23 21:05
Not sure if this is related or not but:
On build 09-15 I noticed a situation where I changed my Frigate from 'hide" to "control system" on the end of turn 12 and on turn 13 an enemy scout traveled right past it.  I went back to turn 11 (a turn earlier) and set it to "control system" and this time on turn 13 when the enemy scout tried to travel past it, the scout was attacked and destroyed.

**Comment by geoffthemedio** [comment] 2019-09-27 16:33
@Oberlus poke

**Comment by alleryn** [comment] 2019-10-06 15:45
> Not sure if this is related or not but:
> On build 09-15 I noticed a situation where I changed my Frigate from 'hide" to "control system" on the end of turn 12 and on turn 13 an enemy scout traveled right past it. I went back to turn 11 (a turn earlier) and set it to "control system" and this time on turn 13 when the enemy scout tried to travel past it, the scout was attacked and destroyed.

Your statement is pretty ambiguous.  You say "on turn 13 an enemy scout traveled".  Ships move between turns, not during them.  If the ship was moving on turn 12.5 (between turns 12 and 13), then i would say this is expected behavior.

As i understand current mechanics, to establish a blockade, a ship has to be aggressive (and armed) during an in-between-turn, and the blockade doesn't affect movement on that in-between-turn (it starts inhibiting movement on the subsequent in-between-turn).

If you are switching your ship to 'control system' on turn 12, it's basically equivalent to having an already-'control system'-ship arrive on turn 12.5.  The blockade is established during turn 12.5 and won't impede enemy ships until turn 13.5.
___________________________________________________________________________________________________________
On the original subject, for what it's worth, i tried loading the save game Oberlus provided in the latest build, but when i end the turn it doesn't advance.  I've never played a game with this many AIs this deep into the game, so maybe i haven't waited long enough, but it's been a good 15 or 20 minutes on my i3 processor 8mb ram system.

Edit: I let it run another couple hours, still didn't advance.  I have log files on off-chance they are useful.

**Comment by geoffthemedio** [comment] 2019-10-06 19:55
The issue with that save, as far as I can tell, is that two of the empires are eliminated, but the game still expects orders from them, but then rejects those orders when it receives them. Hopefully https://github.com/freeorion/freeorion/commit/3f500a6f08df5cec1a74efb22ab37de40fdc46a9#diff-563248add325192e730342065bdfb1d4R1998 resolves this. @o01eg note / maybe comment.

Also a bunch of ship designs are invalid because hull layouts changed since the save was created, so the game probably isn't playable further without major issues.

**Comment by alleryn** [comment] 2019-10-06 21:15
After that latest commit i was able to advance to the next turn, and the fight looks as one would expect.  The carrier is stealthed (and not targeted) during the first bout, and the fighters deal damage.

Added a screenshot to the forum thread, showing the combat results.

**Comment by geoffthemedio** [comment] 2019-10-06 21:27
Does "as one would expect" mean "seemingly correctly"?

**Comment by alleryn** [comment] 2019-10-06 21:45
> Does "as one would expect" mean "seemingly correctly"?

That was my intention, yes.

**Comment by geoffthemedio** [comment] 2019-10-06 21:49
OK, then I"ll call this resolved...

**Closed as completed by geoffthemedio** 2019-10-06 21:49 UTC
Labels: category:bug, category:feature, component:game mechanic, status:resolved
