### ISSUE TITLE
Trojan.Win32.Agent.dg!s1

### ISSUE THREAD

**Issue by nett00n** [freeorion/freeorion#3426] opened 2021-04-29 06:47 UTC
Bug Report
==========
Virustotal detects trojan in installer

Environment
-----------
Just upload an installation package to https://www.virustotal.com

* **FreeOrion Version**: 0.4.10.1
* **Operating System**: null 
* **Graphic card used**: null
* **Fetched as**
  * Binary release

Description
-----------
![image](https://user-images.githubusercontent.com/1846116/116511882-ca42bc80-a8cf-11eb-883e-b341c5619cbf.png)

Expected Result
---------------
No trojans and viruses included =)

Steps to reproduce
------------------
Just upload an installation package to https://www.virustotal.com or open existing report https://www.virustotal.com/gui/file/a80a4dbc780f8f08fd81aef71465ced65d46f7a89a1c3c78cac48ddba9793ef9/detection

**Comment by nett00n** [comment] 2021-04-29 06:56
There is a malware in last testing package too: 
![image](https://user-images.githubusercontent.com/1846116/116512743-26f2a700-a8d1-11eb-9421-2f98bc868988.png)
https://www.virustotal.com/gui/file/9a5bb9c4fbb60c60b7eee427449a6f49ecac06e7cec40083bcc3f5d1df1c6f17/detection

**Comment by geoffthemedio** [comment] 2021-04-29 07:28
Virustotal apparently doesn't detect anything itself, but rather runs various other tests...

https://www.reddit.com/r/antivirus/comments/gozqc1/understanding_virustotal_results_it_is_not/

It's certainly possible that @Vezzra has a trojan that's inserting itself into test builds and installers, but these seem likely to be false positives, since just a single test returns matches. Similar results are discussed online, eg:

https://www.reddit.com/r/antivirus/comments/gp7v18/virus_total_virus_in_vlc_jiangmin_antivirus_engine/

https://www.reddit.com/r/antivirus/comments/ka8j5c/is_gridinsoft_a_false_positive_on_virustotal/

But I obviously can't independently verify that.

**Comment by Vezzra** [comment] 2021-04-30 11:55
If only one of 64 or 59 of the antivirus programs virustotal uses reports a positive, it's practically guaranteed to be a false positive. I have antivirus protection on all my systems, and there is currently no indication that something has slipped by and infected my systems.

Unless there is any other indication that the installer packages might be infected aside from that one positive on virustotal, we can safely ignore this. Unfortunately it's impossible to avoid the occasional false positive...

I'm going to close this as "wont fix". If additional indicators for an infection turn up, please report back.

**Closed as completed by Vezzra** 2021-04-30 11:55 UTC
Labels: category:bug, status:won't fix, component:deployment

**Comment by geoffthemedio** [comment] 2021-05-02 15:17
I uploaded a [FreeOrion v0.4.10+ Windows installer built with TravisCI](https://github.com/freeorion/freeorion/runs/2478146550) and it also triggers a single match: https://www.virustotal.com/gui/file/7bf2a8e709f3796ad01a82c000ddbb6926e97d907c1a88a7ef34b2331fdf7ad3/detection so I don't think the issue is a trojan infection from @Vezzra's machine.
