### ISSUE TITLE
Greek letters do not work with german string table

### ISSUE THREAD

**Issue by sapier** [freeorion/freeorion#771] opened 2016-07-17 13:34 UTC
If you switch stringtable to de system names no longer contain greek letters

freeorion version efc7be038a3301041eded856afa37f122d144c11
OS: debian unstable

**Comment by Vezzra** [comment] 2016-07-17 14:10
Confirmed on OSX. The issue isn't just limited to the German stringtable, apparently the only stringtables that work with the greek letters are the English and French ones (beside those I tried German, Russian and Czech).

Looks like strintables that aren't actively maintained are subject to that problem.

**Comment by geoffthemedio** [comment] 2016-07-17 16:24
Confirmed on Windows that it works fine with French but not German, so I assume this is an issue specific to each broken language's stringtable.

**Comment by geoffthemedio** [comment] 2016-07-17 16:56
It is just a display issue (though a severe one). To demonstrate, right-click a planet or system that has a greek letter in the name in the objects list (can tell due to an oddly wide gap where the letter should be), do a debug data dump, drag-select the text with the name in the messages window, ctrl-c to copy, then paste into some other text editor, where the greek letter should appear.

My guess is that there are no greek letters at all in the broken stringtables, whereas they do appear in the ones that work, and based on just the primary stringtable lacking them, the GUI is deciding not to load the relevant font pages (or whatever they're called). Adding a greek letter to all the stringtables might help, or better, the thing that decides what font stuff to load should also consider the default / english stringtable file.

**Comment by geoffthemedio** [comment] 2016-07-17 17:56
Should be fixed.

**Closed as completed** 2016-07-18 11:17 UTC
Labels: category:bug

**Comment by Vezzra** [comment] 2016-07-19 07:51
Yep, fix confirmed on OSX.
