### ISSUE TITLE
When an AI civilisation has ships, but no planets, message log shows big error every turn.

### ISSUE THREAD

**Issue by psypherium** [freeorion/freeorion#3718] opened 2022-02-23 17:04 UTC
FreeOrion built from git on Arch Linux, AMD drivers.

When an AI civilisation has ships, but no planets, message log shows big error every turn.

As soon as their final planet was taken over, the messages started to appear. When the enemy ships were all destroyed, the error no longer appeared.

[23 Feb 05:01:37] AI_4: AI_Error: AI script error : FreeOrionAI.py:generateOrders():365  - Exception cannot unpack non-iterable NoneType object while trying to calculate_priorities
Traceback (most recent call last):
  File "/home/alistair/Games/freeorion/freeorion/default/python/AI/FreeOrionAI.py", line 362, in generateOrders
    action()
  File "/home/alistair/Games/freeorion/freeorion/default/python/AI/PriorityAI.py", line 65, in calculate_priorities
    InvasionAI.get_invasion_fleets()  # sets AIstate.opponentPlanetIDs, and AIstate.invasionTargetedPlanetIDs
  File "/home/alistair/Games/freeorion/freeorion/default/python/AI/InvasionAI.py", line 226, in get_invasion_fleets
    evaluated_planets = assign_invasion_values(evaluated_planet_ids)
  File "/home/alistair/Games/freeorion/freeorion/default/python/AI/InvasionAI.py", line 285, in assign_invasion_values
    planet_values[pid] = neighbor_values.setdefault(pid, evaluate_invasion_planet(pid))
  File "/home/alistair/Games/freeorion/freeorion/default/python/AI/InvasionAI.py", line 447, in evaluate_invasion_planet
    least_jumps_path, max_jumps = _get_path_from_capital(planet)
TypeError: cannot unpack non-iterable NoneType object
Local context: {'planet_id': 2304, 'empire_id': 2, 'detail': ['sys_supply: -99, planet_supply: 1, supply_val: -19600', 'Base environment: 3', 'GRO_SYMBIOTIC_BIO_PSM_early(1)', 'GRO_XENO_GENETICS_PSM_early(0)', 'GRO_XENO_HYBRIDS_PSM_early(0)', 'GRO_SUBTER_HAB_PSM_late(1)', 'CON_NDIM_STRC_PSM_late(2)', 'CON_ORBITAL_HAB_PSM_late(1)', 'GRO_PLANET_ECOL_PCM(1)', 'GRO_SYMBIOTIC_BIO_PCM(-1)', 'Homeworld (2)', 'max_pop = base + size*[psm_early + species_mod*abs(psm_early) + psm_late]', '        = 0.00 + 3 * [4.00 + 0.00*abs(4.00) + 6.00]', '        = 30.00', 'ind_val 313.2', 'preexisting system colony', 'threat reducing value by  99 %'], 'planet': P_2304<Astrum β I>, 'system_id': 2288, 'predicted_detectable': True, 'system_last_seen': 1003, 'planet_last_seen': 1003, 'species_name': 'SP_SSLITH', 'species': <freeOrionAIInterface.species object at 0x7fa6ff986ea0>, 'empire_research_list': ('SHP_WEAPON_4_4', 'PRO_NDIM_ASSMB', 'PRO_ZERO_GEN', 'PRO_NEUTRONIUM_EXTRACTION', 'SHP_SOLAR_CONT', 'CON_CONC_CAMP', 'LRN_ART_BLACK_HOLE', 'DEF_SYST_DEF_MINE_2', 'DEF_SYST_DEF_MINE_3', 'LRN_UNIF_CONC', 'LRN_PSY_DOM', 'SHP_BLACKSHIELD', 'DEF_PLAN_BARRIER_SHLD_5', 'SPY_DETECT_5', 'GRO_GAIA_TRANS', 'CON_ART_HEAVENLY', 'CON_ART_PLANET', 'SPY_STEALTH_PART_1', 'SHP_WEAPON_ARC_DISRUPTOR_2', 'SHP_ORGANIC_WAR_ADAPTION', 'SPY_LIGHTHOUSE', 'SHP_BOMBARD', 'SPY_STEALTH_1', 'SHP_NANOROBO_MAINT', 'SHP_SPACE_FLUX_BUBBLE', 'PRO_GENERIC_SUPPLIES', 'SPY_STEALTH_PART_2', 'SHP_XENTRONIUM_PLATE', 'PRO_TRANS_DESIGN', 'CON_FRC_ENRG_CAMO', 'CON_ORGANIC_STRC', 'SHP_ENDOCRINE_SYSTEMS', 'SPY_DIST_MOD', 'CON_PLANET_DRIVE', 'SPY_STEALTH_PART_3', 'GRO_BIOTERROR', 'SHP_BIOADAPTIVE_SPEC', 'SHP_SINGULARITY_ENGINE_CORE'), 'colony_base_value': -158.57706620685033, 'building_values': {'BLD_IMPERIAL_PALACE': 1000, 'BLD_CULTURE_ARCHIVES': 1000, 'BLD_AUTO_HISTORY_ANALYSER': 100, 'BLD_SHIPYARD_BASE': 100, 'BLD_SHIPYARD_ORG_ORB_INC': 200, 'BLD_SHIPYARD_ORG_XENO_FAC': 200, 'BLD_SHIPYARD_ORG_CELL_GRO_CHAMB': 200, 'BLD_SHIPYARD_CON_NANOROBO': 300, 'BLD_SHIPYARD_CON_GEOINT': 400, 'BLD_SHIPYARD_CON_ADV_ENGINE': 1000, 'BLD_SHIPYARD_AST': 300, 'BLD_SHIPYARD_AST_REF': 1000, 'BLD_SHIPYARD_ENRG_SOLAR': 1500, 'BLD_INDUSTRY_CENTER': 500, 'BLD_GAS_GIANT_GEN': 200, 'BLD_SOL_ORB_GEN': 800, 'BLD_BLACK_HOLE_POW_GEN': 2000, 'BLD_ENCLAVE_VOID': 500, 'BLD_NEUTRONIUM_EXTRACTOR': 2000, 'BLD_NEUTRONIUM_SYNTH': 2000, 'BLD_NEUTRONIUM_FORGE': 1000, 'BLD_CONC_CAMP': 100, 'BLD_BIOTERROR_PROJECTOR': 1000, 'BLD_SHIPYARD_ENRG_COMP': 3000}, 'bld_tally': 0, 'tech_tally': 0, 'value_per_pp': 4, 'universe': <freeOrionAIInterface.universe object at 0x7fa6ffae09e0>}

[23 Feb 05:01:37] AI_4: AI_Error: AI script error : FreeOrionAI.py:generateOrders():365  - Exception local variable 'production_queue' referenced before assignment while trying to generate_production_orders
Traceback (most recent call last):
  File "/home/alistair/Games/freeorion/freeorion/default/python/AI/FreeOrionAI.py", line 362, in generateOrders
    action()
  File "/home/alistair/Games/freeorion/freeorion/default/python/AI/ProductionAI.py", line 273, in generate_production_orders
    for element in production_queue:
UnboundLocalError: local variable 'production_queue' referenced before assignment
Local context: {'total_pp': 0.0, 'building_expense': 0.0, 'building_ratio': 0.3, 'capital_id': -1, 'homeworld': None, 'capital_system_id': None, 'current_turn': 1479, 'max_defense_portion': 0.7, 'sys_orbital_defenses': {}, 'queued_defenses': {}, 'defense_allocation': 0.0, 'target_orbitals': 4, 'aistate': <AIstate.AIstate object at 0x7fa716d36080>, 'empire': E_2<Congregation>, 'universe': <freeOrionAIInterface.universe object at 0x7fa6ffae0d60>}

**Comment by psypherium** [comment] 2022-02-23 17:27
Oh and here is another error that showed in the messages, unrelated:

[23 Feb 04:23:26] AI_3: AI_Error: AI script error : _freeorion_tools.py:assertion_fails():284  - AI raised a warning: Can't split last ship from fleet. See more detailed description in logs.
[23 Feb 04:23:26] AI_3: AI_Error: AI script error : _freeorion_tools.py:assertion_fails():284  - AI raised a warning. See more detailed description in logs.

"See more detailed description in logs." I can't even open the logs, they are so big that they crash Atom, lol. One of the logs is only 80 MB though, I could probably send that if necessary.

**Comment by geoffthemedio** [comment] 2022-02-23 21:50
Are you running on trace level logging, or just a massive galaxy for many turns? Logs otherwise generally aren't that huge... maybe a couple MB per turn.

Assuming the issue is reproducible, you can load a save and play for one or two turns to generate the errors and still have loadable size logs.

**Comment by Grummel7** [comment] 2022-02-25 07:56
I just got the two errors in the first report. I'm surprised I haven't seen them so far, at least the first one was introduced in August. They should be easy to fix.

I've ignored the "Can't split last ship" for quite some time, but since I'm working on the AI now, I may as well try to fix that one, too.

**Comment by geoffthemedio** [comment] 2022-03-12 21:21
@Grummel7 @Cjkjvfnby was this fixed by #3719 ?

**Comment by Grummel7** [comment] 2022-03-13 12:58
I think this issue can be closed.

**Closed as completed** 2022-03-13 13:03 UTC
Labels: category:bug, component:AI, status:resolved
