### ISSUE TITLE
git commit ID's does not belong in the release filenames

### ISSUE THREAD

**Issue by solbu** [freeorion/freeorion#3226] opened 2020-11-10 03:10 UTC
Hi.
I am an rpm packager for Mageia, and the way you generate the release filenames makes it an unneccesary burden on packagers.

To give an example:
The current release source tarball is named «FreeOrion_v0.4.10.1_2020-09-25.39cfe10_Source.tar.gz».
The characters «39cfe10» is the shortform of the git commit ID. This _does not_ belong in the filename.

Not only do we need to keep up with a growing number of releases (which is really not a hard job), but we _also_ need to keep track of what commit ID is used in the _filename_.
That make us having to manually visit the website or this github releases page and check what random ID the filename has.

So could you please drop this commit ID in the filenames for the future?

**Comment by geoffthemedio** [comment] 2020-11-10 08:10
Why is the git commit problematic but not the date and version number? Seems like you'd need to copy those manually as well, if not building from source yourself...

**Comment by solbu** [comment] 2020-11-10 09:09
First, I didn't notice the date string in the file name. Good catch. ;-)

The issue is that when we subscribe to receiving mail (in this instance from github) about a new release, we usually only need the version number in order to update a package.
Most times we don't even need to visit the project site in order to download the new release. We just increase to the new released version and run commands that will download the tarball and upload it to our buildsystem automatically.

And yes, we are building from source.

**Comment by agrrr3** [comment] 2020-11-10 14:27
Not exactly sure why the situation you describe is a problem. No link to the source tarball in the notification? I wasnt even aware we provide source packages.

If you are building from source, you should be able to get a source archive using the release tag and the github functionality.

Or just do a git clone from github for the release tag (with zero depth if the script is fire-and-forget).

**Comment by Vezzra** [comment] 2020-11-13 12:21
@agrrr3, the problem is that the source tarballs github creates automatically can't be used for the purposes of Linux package managers. We have a build step where a Python script generates the `util/version.cpp` file. To work properly that script needs the git repo present in the source root (as it queries the SHA of the checked out commit).

That does not fit with how the build processes of packages for Linux distro repos works. Therefore, we provide a source tarball which already contains a proper, pre-generated `util/version.cpp` file, which Linux package managers can use.

So, I can see the issue @solbu raises. However, the question is how to address it. For release candidates, releases and maintenance releases we can just drop the part with the date and the commit SHA.

But that does not work with the weekly test builds, as the date and commit SHA are actually part of the version/build number/identifier. Omitting those will result in all weekly test builds of a release cycle have the same filename, and you can certainly see where that is going to be a problem.

So, my question to @solbu is: would it be sufficient for the date and commit SHA part to be dropped only for (maintenance) release (candidate) builds?

**Comment by solbu** [comment] 2020-11-13 18:49
> @agrrr3, the problem is that the source tarballs github creates automatically can't be used for the purposes of Linux package managers. We have a build step where a Python script generates the `util/version.cpp` file. To work properly that script needs the git repo present in the source root (as it queries the SHA of the checked out commit).
> 
> That does not fit with how the build processes of packages for Linux distro repos works. Therefore, we provide a source tarball which already contains a proper, pre-generated `util/version.cpp` file, which Linux package managers can use.

Many distributions have their build servers intentionally configured _without_ internet access. All dependencies required should already be provided with the source code, or downloaded separately and installed as a separate package.
The idea is that all source code should be able to compile even if the original project and all dependencies permanently goes offline for whatever reason. If that cannot be accomplished, the code is treated as proprietary, and we refuse to package it.

Mageia did just that a few years ago, when the game «TripleA» changed their compile steps to download 120 separate github projects to fulfill dependencies. Yes, 120, I counted.
We managed to figure out how to get about 40 packages, and we gave up on the rest. So I took the decition to just drop the game from our distro, and I know for a fact that a few users contated us asking where it went. So it was missed by our users.


> So, I can see the issue @solbu raises. However, the question is how to address it. For release candidates, releases and maintenance releases we can just drop the part with the date and the commit SHA.

> So, my question to @solbu is: would it be sufficient for the date and commit SHA part to be dropped only for (maintenance) release (candidate) builds?

I can only speak for Mageia, but our use case is common. We only care about the stable releases, and some distros also use release candidates in testing environments.


> But that does not work with the weekly test builds, as the date and commit SHA are actually part of the version/build number/identifier. Omitting those will result in all weekly test builds of a release cycle have the same filename, and you can certainly see where that is going to be a problem.

Can those builds have a separate «Makefile» target?
It is only the actuall releases that distros care about.

**Comment by Vezzra** [comment] 2020-11-15 15:12
> Many distributions have their build servers intentionally configured without internet access. All dependencies required should already be provided with the source code, or downloaded separately and installed as a separate package.

On Linux, FO only depends on stuff usually provided by distro repos (such as Boost, Python, SDL, etc.). For macOS and Windows we need to provide SDKs which contain all dependencies, but that's irrelevant for building FO on Linux.

> The idea is that all source code should be able to compile even if the original project and all dependencies permanently goes offline for whatever reason. If that cannot be accomplished, the code is treated as proprietary, and we refuse to package it.

Makes sense. However, FO should meet those requirements, unless I've missed something. As noted above, FO only relies on stuff usually provided by distro repos.

> Mageia did just that a few years ago, when the game «TripleA» changed their compile steps to download 120 separate github projects to fulfill dependencies. Yes, 120, I counted.

Ouch. That's... insane. 😲 

> We only care about the stable releases, and some distros also use release candidates in testing environments.

So you won't care about our weekly test builds, for your purposes it would be sufficient if we change the naming patterns for our releases.

Well, I don't really have any objections to do that - @geoffthemedio? Would it be ok with you if we drop the date and commit SHA part of the filenames of our release builds?

> Can those builds have a separate «Makefile» target?

I'm not sure what's that supposed to address/solve - for release builds, I usually edit the filenames manually...

**Comment by geoffthemedio** [comment] 2020-11-15 17:12
> @geoffthemedio? Would it be ok with you if we drop the date and commit SHA part of the filenames of our release builds?

Fine with me...

**Comment by o01eg** [comment] 2020-12-03 19:33
> Many distributions have their build servers intentionally configured _without_ internet access. All dependencies required should already be provided with the source code, or downloaded separately and installed as a separate package.
> The idea is that all source code should be able to compile even if the original project and all dependencies permanently goes offline for whatever reason. If that cannot be accomplished, the code is treated as proprietary, and we refuse to package it.

@solbu If we switch to Godot UI will it be possible to download `godot-cpp` from Github with some defined commit and `Godot` with some defined `major.minor` version to use for building FreeOrion?

**Comment by solbu** [comment] 2020-12-03 20:56
> @solbu If we switch to Godot UI will it be possible to download `godot-cpp` from Github with some defined commit and `Godot` with some defined `major.minor` version to use for building FreeOrion?

I have no idea what any of that means…

**Comment by o01eg** [comment] 2020-12-03 21:01
`godot-cpp` is a static library without stable releases required to wrap our FreeOrion code, and `Godot` is a unity-like game engine which is required to build client binary.

**Comment by solbu** [comment] 2020-12-03 21:04
My only point of this is that the version number should be enough in the _Stable_ releases.
Any other number that is dependent on a commit ID or any other variable that changes, does not belong in the filenames or the extracted «root-folder» names.

What you do in development/test releases, I don't care one bit. :-)

**Comment by Vezzra** [comment] 2020-12-06 15:16
@solbu,

> I have no idea what any of that means…

Well, @o01eg was referring to your statement:

> Many distributions have their build servers intentionally configured without internet access. All dependencies required should already be provided with the source code, or downloaded separately and installed as a separate package.
The idea is that all source code should be able to compile even if the original project and all dependencies permanently goes offline for whatever reason. If that cannot be accomplished, the code is treated as proprietary, and we refuse to package it.

We are currently considering/evaluating migrating FO to the Godot engine. Right now all dependencies FO has on Linux are usually provided by the repositories of the various Linux distros (e.g. Boost). However, if we actually do the switch to Godot, that will add dependencies which are usually not found in Linux repositories.

The `godot-cpp`dependency @o01eg mentioned would be one of them. I think what he wanted to know is that if we set up our build process so that this dependency gets pulled in at build time (which would be done via `git clone` from a git repo hosted on GitHub), will that affect if you will package FO?

Judging by your above statement, I assume you would not - correct?

**Comment by o01eg** [comment] 2022-08-31 18:56
It's still open. Do something should be done still? Maybe change release tracker issue to reflect new naming scheme for releases.

Looks like CPack source archive generator isn't used.

**Comment by solbu** [comment] 2022-09-01 04:19
> It's still open. Do something should be done still? Maybe change release tracker issue to reflect new naming scheme for releases.

The stable releases still uses the date and commit ID as part of the file name, so the problem is still there.

Right now the stable release source tarball is named «FreeOrion_v0.4.10.2_2021-08-01.f663dad_Source.tar.gz»
The _correct_ filename should be «FreeOrion_v0.4.10.2_Source.tar.gz»

**Comment by solbu** [comment] 2022-09-01 04:31
for some reason i completely missed this comment,
so sorry for the very late reply. :-)

> > I have no idea what any of that means…
> 
> Well, @o01eg was referring to your statement:
> 
> > Many distributions have their build servers intentionally configured without internet access. All dependencies required should already be provided with the source code, or downloaded separately and installed as a separate package.
> > The idea is that all source code should be able to compile even if the original project and all dependencies permanently goes offline for whatever reason. If that cannot be accomplished, the code is treated as proprietary, and we refuse to package it.

I still have No idea what his statement means. :-)
Remember, I am Not a programmer, I am a packager. There is a difference. :-)


> We are currently considering/evaluating migrating FO to the Godot engine. Right now all dependencies FO has on Linux are usually provided by the repositories of the various Linux distros (e.g. Boost). However, if we actually do the switch to Godot, that will add dependencies which are usually not found in Linux repositories.
> 
> The `godot-cpp`dependency @o01eg mentioned would be one of them. I think what he wanted to know is that if we set up our build process so that this dependency gets pulled in at build time (which would be done via `git clone` from a git repo hosted on GitHub), will that affect if you will package FO?

We do not use the git in any way when packaging the game, we only download the Source tarball, nothing else.
Any external dependencies needs to be documented in someway, or provided inside the source tarball.

If the compile stage of a stable release at any time tries to connect to the internet in order to Download missing dependencies the compile process will fail and we will Stop packaging the game and drop it from our distribution – because our build servers cannot connect to the internet.
This is a deliberate limitation, that I know for a fact that my distro Mageia and Fedora have. The reason is that anyone trying to rebuild the package should be able to do so on a deserted island with no internet connectivity, or a future Mars settlement.

**Comment by o01eg** [comment] 2022-09-01 05:44
So it looks like my packaging for Ubuntu PPA where I had to include `godot-cpp` dependency into source tree.

**Comment by Vezzra** [comment] 2023-02-24 12:04
@solbu, we've adopted a new, simpler pattern for the release/release candidate filenames, starting with the upcoming 0.5 release, where there is no date and commit ID anymore in these filenames. Future releases should continue this pattern.

0.5 RC1 is already available on Sourceforge:

https://sourceforge.net/projects/freeorion/files/FreeOrion/FreeOrion%20Version%200.5/

You can inspect the new filenames there. AFAICT these should satisfy your requirements.

I'm closing this ticket. If there are still questions/problems, feel free to reopen this one or create a new one.

**Closed as completed by Vezzra** 2023-02-24 12:04 UTC
Labels: status:resolved, component:deployment, category:tweak
