### ISSUE TITLE
Xorg gets slow even when freeorion window is hidden

### ISSUE THREAD

**Issue by l29ah** [freeorion/freeorion#1493] opened 2017-04-15 21:52 UTC
freeorion is quite heavy on the video subsystem yet it's not that annoying as it is a turn based game, but the fact that all the system GUI gets slow even when freeorion doesn't draw anything on the screen is just terrible. It doesn't slow the system down being in the main menu, however.

### Environment
freeorion e45dedee03a215e5a7be8fa9425a74218e2a1a6a
Gentoo linux
xorg-server-1.19.3
xf86-video-intel-2.99.917_p20170313
Intel(R) Core(TM) i7 CPU L 620 @ 2.00GHz

**Comment by adrianbroher** [comment] 2017-04-16 07:29
Could you please clarify?  'Hidden' like in minimized or 'hidden' like in covered by other windows?

**Comment by l29ah** [comment] 2017-04-16 09:25
On Sun, Apr 16, 2017 at 12:29:37AM -0700, Marcel Metz wrote:
> Could you please clarify?  'Hidden' like in minimized or 'hidden' like in covered by other windows?

Like residing in some other workspace and not being "previewed" by any kind of a taskbar.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by adrianbroher** [comment] 2017-04-17 09:23
The problem that we're unable to query this state.  SDL / the underlying platform sends a limited number of events when a window changes or the application needs to take action like redrawing the window surface. 

When moving the window to another workspace I received no event that would indicate that the application surface is now out of view.  Same goes when moving other windows on top of FO, covering the FO window completely.  Only explicit minimizing the application send a sequence of `SDL_WINDOWEVENT_HIDDEN`, `*_MINIMIZE`, `*_FOCUS_LOST` or when restoring the application `*_SHOWN`, `*_RESTORED`, `*_FOCUS_GAINED`.  When moving the application somewhere else and selecting another window or the desktop you receive only `*_FOCUS_LIST` or `*_FOCUS_GAINED`.

We could however suspend the rendering when the application loses the keyboard focus, somewhat similar as the game currently suspends the music.  But suspending may lead to false reports of game crashing as the game appears to be frozen because it doesn't update the window contents.  This could be circumvented by some kind of 'paused' screen.

The first fix would be to suspend the rendering as soon as the window is hidden, because at this state any rendering isn't required for sure but this wouldn't fix the problem you stated.

@freeorion/developers: any opinions or other ideas?

**Comment by Vezzra** [comment] 2017-04-17 12:27
> But suspending may lead to false reports of game crashing as the game appears to be frozen because it doesn't update the window contents.

Just an idea that came to my mind: instead of completely suspending rendering, maybe just limit the FPS to a very low value, e.g. 5?

**Comment by adrianbroher** [comment] 2017-04-17 12:57
Seems like we already have the feature that @Vezzra describes in place.

Within `Options` > `Video` > `Max FPS (Non Focused)` you can set a value that represents the FPS when the game has lost focus.  By default it seems to be 15.  @l29ah can you set it to a lower value like the suggested 5 FPS and check if this helps with your problem?

**Comment by LGM-Doyle** [comment] 2017-04-17 16:08
I agree with the description of the problem.

Completely suspending rendering while focus is lost breaks several useful features.
- it prevents waiting for turn update/end from another window, because it won't update
- it prevents video capture using a different app if focus is retained by the capture app
- it prevents use a zoom app to examine small glitches

Suspending while minimized will mean that the thumbnails won't update, which is neat but non-essential.

**Comment by l29ah** [comment] 2017-04-17 18:18
On Mon, Apr 17, 2017 at 05:57:19AM -0700, Marcel Metz wrote:
> Seems like we already have the feature that @Vezzra describes in place.
> 
> Within `Options` > `Video` > `Max FPS (Non Focused)` you can set a value that represents the FPS when the game has lost focus.  By default it seems to be 15.  @l29ah can you set it to a lower value like the suggested 5 FPS and check if this helps with your problem?

Yes, setting it to 1 helps a lot.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by Vezzra** [comment] 2017-04-18 13:54
As the feature required to address the issue is already implemented, I suggest to close this as invalid. Anyone any objections?

**Comment by LGM-Doyle** [comment] 2017-04-18 18:06
How about adding `workaround` as well, so that people with the same concern know that there is a solution in this thread.

**Comment by adrianbroher** [comment] 2017-04-19 20:54
> As the feature required to address the issue is already implemented, I suggest to close this as invalid. 

Yeah, there is no point to further work on this.

**Closed as completed by adrianbroher** 2017-04-19 20:54 UTC
Labels: category:refactoring, status:invalid, status:workaround, component:internal
