### ISSUE TITLE
Production rally color indicator

### ISSUE THREAD

**Issue by cpeosphoros** [freeorion/freeorion#1862] opened 2017-11-17 13:29 UTC
When the Production window is open, indicate by color which ships are rallied to the currently selected system.

Here is a mock up:

![rally](https://user-images.githubusercontent.com/748982/32949584-86328aa0-cb8a-11e7-861a-c72dd0f71536.png)

**Comment by Vezzra** [comment] 2017-11-17 14:23
The basic idea is a good one, however, we'll have to come up with another indicator. Coloring the system name of a production item is already used to indicate which items are built at the currently selected system.

Maybe a small indicator graphic overlaying the production item icon?

**Comment by Vezzra** [comment] 2017-11-17 14:24
(Oops, sorry, didn't mean to close the issue, clicked the wrong button... 😉)

**Comment by cpeosphoros** [comment] 2017-11-17 14:40
Or maybe using a different color/shade - or underlining.

**Comment by Vezzra** [comment] 2017-11-17 15:28
Underlining could work, but I don't think different color would. What if you select a system where items are being built *and* that is set as rally point for ships being built at other systems? We need an indicator that works independent of the "production items being built here" one.

**Comment by alleryn** [comment] 2017-11-25 23:43
In terms of using two colors as indicators, a "yellow+blue makes green" system is a possibility.

**Comment by Vezzra** [comment] 2017-11-26 13:55
> In terms of using two colors as indicators, a "yellow+blue makes green" system is a possibility.

I'm confused, how is that supposed to solve the issue at hand? The problem isn't that there could be items which need to have both colors assigned, to problem is that for a given system both kinds of items could be in the queue - items which have the system set as rally point, and items that are produced at the system. But you can't have an item that is both produced at a system and has that same system set as rally point (which wouldn't make any sense of course).

The problem is simply that currently the empire color is used to highlight items produced at the currently selected system, so whatever color you choose to highlight items that have the currently selected system set as rally point can be the same or too similar to the empire color to make them clearly distinguishable.

Of course, that could be solved by using a fixed color for items being produced at a location, e.g. red instead of the empire color. Then you can use blue to indicate "rally point items".

Still, I prefer the icon solution.

**Comment by alleryn** [comment] 2017-11-27 21:12
> The problem isn't that there could be items which need to have both colors assigned, to problem is that for a given system both kinds of items could be in the queue

Oh, right.  I misunderstood the concept.  My mistake.

**Comment by Dilvish-fo** [comment] 2018-03-19 00:22
> But you can't have an item that is both produced at a system and has that same system set as rally point (which wouldn't make any sense of course).

You actually can set the rally like that, ~~although you are totally right that there would be no reason to~~ (edit: see below).  In such case, the PR I proposed for the ProductionPanel display just ignores the fact that the rally point is set.

**Comment by Dilvish-fo** [comment] 2018-03-19 03:52
I just realized that a valid use of setting the rally point to the system of construction is the only current way to essentially undo/reset the rally point (albeit a somewhat awkward way to accomplish that).

**Closed as completed** 2018-04-02 06:04 UTC
Labels: category:feature, component:UI, status:resolved
