### ISSUE TITLE
With System Droplist Open, Mousewhere Anywhere Outside of List (Whole Screen) Switches Selected System

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#1138] opened 2016-11-27 08:29 UTC
Explore enough systems to have scrollbars on the system name droplist. Open the droplist. Mousewheel on the list itself scrolls the list. Mousewheel on the system name changes the selected system. Moving the cursor outside the droplist acts like it is on the name, which is confusing and shouldn't happen.

**Comment by Vezzra** [comment] 2016-11-27 13:53
Confirmed on OSX.

**Comment by Vezzra** [comment] 2016-12-11 17:13
Has #1142 sufficiently addressed this issue so it can be closed?

**Comment by geoffthemedio** [comment] 2016-12-11 17:17
Can't twst now but if it doesn't do as described for you, probably yes.

**Comment by Vezzra** [comment] 2016-12-16 14:19
Yep, seems to be fixed.

Closing as fixed by #1142.

**Closed as completed by Vezzra** 2016-12-16 14:19 UTC
Labels: category:bug, component:UI, status:resolved
