### ISSUE TITLE
AI builds ships with more launch bays than fighter capacity

### ISSUE THREAD

**Issue by aryehklempner** [freeorion/freeorion#2125] opened 2018-05-24 19:55 UTC
* **FreeOrion Version**: 0.4.7.1
* **Operating System**: Ubuntu 18.04
* **Graphic card used**: Intel HD Graphics 4000 (Ivy Bridge i3-3217U)
* **Fetched as**
  * Binary release: Ubuntu `freeorion` package

# Description
This is a great game. The only problems I've had with it are high RAM usage (up to a gigabyte for a game without 3D graphics, and not all older machines have even 4GB, like mine (only 5 years old)). Anyway, I'm on turn 271 of a 7-empire single player game. One of my stealthy, all-seeing scouts spots a previously unknown ship type, so I look it up in the Pedia. 
![image](https://user-images.githubusercontent.com/35413832/40510219-d3cd3da0-5f50-11e8-875c-6a55fe46ff77.png)

If there are only three fighters, then why are there **SEVEN** launch bays?!?! The AI is making a mistake a human would never make. If it doesn't "want" to spend lots of production capacity, then it should leave the slots empty so as not to waste production points. Otherwise, there are plenty of things it can fit in an external slot, like death rays.
# Expected Result
I expect my algorithmic opponents to make ship designs that are at least rational, if not optimal.

**Comment by Vezzra** [comment] 2018-05-25 15:29
I could be wrong, but I wonder if that issue had already come up before - can anyone reproduce this issue with current master? After all, this is reported for 0.4.7.1....

Or, @freeorion/ai-team, can you confirm that the AI has this problem?

**Comment by Morlic-fo** [comment] 2018-05-25 17:16
As far as the current code is concerned, the AI (should) know that launch rate doesn't have any effect beyond the fighter capacity. It also should consider empty slots are better than wasted parts. But I think it should have done both of these things in 0.4.7.1 already.

So, this may still be valid. However, it will take a more recent savegame reproducing the issue to track it down.

**Comment by Vezzra** [comment] 2018-05-27 15:07
Ok, that means this needs at least some investigation, so it needs to stay open.

**Comment by Dilvish-fo** [comment] 2018-05-27 17:08
@aryehklempner did you by any chance save a savegame file with this problem that you could post here?

**Comment by aryehklempner** [comment] 2018-05-27 18:58
Unfortunately not, sorry. Though I imagine playing a game against 6 AIs for 200 or so turns with enough deployed scouts or other sensor-equipped ships would generally reproduce the problem sooner or later.

**Comment by aryehklempner** [comment] 2018-05-28 01:32
I am on turn 147 of another game, though, so I'll keep my eyes peeled; sooner or later the bug should crop up and I'll submit my save.

**Comment by Morlic-fo** [comment] 2019-09-30 18:34
While hard to verify, I assume this issue will be fixed by #2530.

**Comment by Vezzra** [comment] 2019-10-02 14:04
@Morlic-fo, so, close as resolved and reopen in case the issue persists (once #2530 has been merged of course)?

**Closed as completed** 2021-05-04 22:23 UTC
Labels: category:bug, component:AI, status:resolved

**Comment by Vezzra** [comment] 2021-05-09 10:20
@Morlic-fo, I assume this means #2530 (which has been part of 0.4.9) fixed this issue, meaning this issue should also belong to the 0.4.9 milestone?

**Comment by Morlic-fo** [comment] 2021-05-09 11:14
It is likely to have fixed it and since it hasn't been reported since, I assume it to be fixed, yes.
