### ISSUE TITLE
No hulls in a multiplayer game

### ISSUE THREAD

**Issue by l29ah** [freeorion/freeorion#2099] opened 2018-05-12 14:02 UTC
### Environment
* **FreeOrion Version**: https://github.com/Voker57/freeorion/tree/teamsmac-14.5
* **Operating System**: Linux
* **Graphic card used**: Intel
* **Fetched as** 
  * Compiled from source

### Description
after turn 64 ended, save got corrupted and player L29Ah no longer has any hulls listed on design screen:
http://dump.bitcheese.net/files/racuwis/FreeOrion_Voker57_Voker57_0065_2018-May-10_02:29:56.707942.mps

![screenshot](https://dump.bitcheese.net/files/luzocop/loh.png)

### Expected Result
Hulls listed in the ship designer.

### Steps to reproduce
Join the multiplayer game as L29Ah and look in the ship designer.

**Comment by Dilvish-fo** [comment] 2018-05-12 18:26
Do you have a pre-corruption save that still has the hulls?  Does the corruption always happen when you progress the turn or try to make the new save or whatnot?

I have poked at this a little so far.  I confirmed that I get the same lack of hulls if I load the game as L29Ah, and that even after advancing the game a few turns to have the Organic Hull researched, it still does not show up as an available hull.  Also, since the savefile you provided has the main gamestate compressed (I think that's our default setting even with xml) I turned off that compression and resaved to get a fully readable savefile: 
[hulls_missing.zip](https://github.com/freeorion/freeorion/files/1997830/hulls_missing.zip)
opening that up and searching for your empire listing and then your available hulls, it lists
```
				<m_available_hull_types>
					<count>5</count>
					<item_version>0</item_version>
					<item>SH_BASIC_LARGE</item>
					<item>SH_BASIC_MEDIUM</item>
					<item>SH_BASIC_SMALL</item>
					<item>SH_COLONY_BASE</item>
					<item>SH_ROBOTIC</item>
				</m_available_hull_types>
```
Which seems right.
So, yes, this is quite perplexing that none of the hulls are showing up as available ingame.

**Comment by Dilvish-fo** [comment] 2018-05-12 22:58
I just noticed that Geoff had recently Added lists of available parts and hulls to empire pedia articles, so I went and double checked the L29Ah empire pedia page for this game.  It does list the expected hulls as available to the empire; somehow it seems to be just the design screen that is not recognizing them as available.   I see that the pedia page uses ```empire->AvailableShipHulls()``` to get the available hulls, whereas the DesignWnd is doing some hull-by-hull categorization across all hulls in the game, and something must be going awry there.

Most of the recent work in that area had been done by @LGM-Doyle, but I think he was still tied up with non-FO obligations for a while, is that right?

**Comment by Voker57** [comment] 2018-05-13 08:42
Pre-corruption save: http://dump.bitcheese.net/files/zijunet/FreeOrion_Voker57_Voker57_0064_2018-May-10_02:25:42.871327.mps

I wasn't able to reproduce hull disappearance.

**Comment by Vezzra** [comment] 2018-05-13 15:31
If this issue can't be reproduced, it probably doesn't make much sense to keep it open.

@Voker57 already stated he can't reproduce it, @Dilvish-fo, if you can't either, feel free to close it. If it happens again, we can reopen or create a new issue.

**Comment by Dilvish-fo** [comment] 2018-05-13 18:31
It is only one aspect that we cannot currently reproduce.

I think it is reproducible enough to merit keeping open.  We have a savegame file which at first seems to load fine, and for which the key bit of saved data appears fine, but then different parts of the game are giving a disparate handling, one of which is incorrect.  I think it's worthwhile to further investigate why the DesignWnd is not listing these hulls as available even though the empire pedia page correctly lists them as available, for starters.   We have a savefile that fully reproduces that issue.

Then we can hopefully identify what aspect of the savefile data is responsible, and then perhaps we can identify how that data came to be.

**Comment by Dilvish-fo** [comment] 2018-05-13 18:33
But I think it does make sense to downgrade the issue to optional, and have done so, since it seems to be a very rare problem of uncertain trigger.

**Comment by geoffthemedio** [comment] 2018-05-14 18:25
For some reason, `m_ordered_hulls` in `CurrentShipDesignsManager` is empty in that save. I don't know how that code works, and it's not well enough commented for me to figure out if this is an expected situation, or if some weird bug occurred. But, I put in some safety checks that should let that save continue to be played, by ensuring that all hulls are considered when populating the list. https://github.com/freeorion/freeorion/commit/eecd3a004f6399f0eea01168f0de2ea0623d35b6

**Closed as completed by geoffthemedio** 2018-05-14 18:25 UTC
Labels: category:bug, component:UI, status:workaround, component:internal

**Comment by Dilvish-fo** [comment] 2018-05-16 01:44
Please double check whether you have obsoleted that design and whether showing obsolete brings it back for you, and if not then please open a new issue for that, including a savegame file.  Even though seems somewhat similar to what you encountered here, unless/until we establish a common cause it seems fairly distinct.

**Comment by geoffthemedio** [comment] 2018-05-16 06:16
@Dilvish-fo obsoleting isn't the problem.
