### ISSUE TITLE
Game locks up requiring force quit

### ISSUE THREAD

**Issue by bta-notavailable** [freeorion/freeorion#3082] opened 2020-06-28 13:39 UTC
Right click on production item (opening "move to queue top" - "pedia lookup" menu) during turn change causes game to lock up.

**Comment by bta-notavailable** [comment] 2020-06-28 13:44
FreeOrion v0.4.9 [build 2020-02-02.db53471] CMAKE with Ubuntu 18.04.4 LTS on ASUS UX430U.

**Comment by geoffthemedio** [comment] 2020-06-28 17:22
I haven't been able to reproduce this in master. It moves the item in the queue, but it reverts to its original position after the following turn update from the server. Is this reproducible every time for you, and is there a particular point during the turn cycle when you can make it happen (or not)?

**Comment by bta-notavailable** [comment] 2020-06-28 18:04
Hmph! you are right, not every time! It always locked up before, always. Maybe when I am further into the game, with more variables to compute?

**Comment by geoffthemedio** [comment] 2020-06-28 18:05
Do you have some saves from further into a game to test with?

**Comment by bta-notavailable** [comment] 2020-06-28 18:17
No, but I will later today. It happens often enough that I make a habit of avoiding the reflex of making those changes during a turn.

**Comment by geoffthemedio** [comment] 2020-06-28 20:12
Those commands should probably just be disabled if between turns, and rejected if given at that time anyway (eg. if the turn cycles after the popup was opened). But narrowing down the specifics of the issue would be helpful.

**Comment by bta-notavailable** [comment] 2020-06-29 00:42
No luck fishing  for that event tonight. what do you want from me when I do recreate it?

**Comment by geoffthemedio** [comment] 2020-06-29 11:37
Detailed / specific and reproducible instructions on how to recreate the issue would be good. If you can also test a recent development build to verify if it still occurs, that would be better. freeorion.log from immediately after reproducing the issue might be helpful. If you somehow can get a stack trace, that would also help.

**Comment by bta-notavailable** [comment] 2020-06-30 00:51
game is locked up now. Game is not in the middle of a turn. But, that right click menu is up. Either the fan or the hard drive was running for a while right before lock up. The freeorion log is too big to copy and paste.

**Comment by bta-notavailable** [comment] 2020-06-30 00:53
from this location, yes? /home/bta/.local/share/freeorion

**Comment by bta-notavailable** [comment] 2020-06-30 00:54
[freeorion.log](https://github.com/freeorion/freeorion/files/4848751/freeorion.log)

**Comment by geoffthemedio** [comment] 2020-06-30 07:58
That's the log I wanted, but it doesn't seem to contain anything that clarifies the cause of the issue. A stack trace when it's locked up would probably help, if you can figure out how to get one...

**Comment by geoffthemedio** [comment] 2020-06-30 09:44
Hopefully https://github.com/freeorion/freeorion/pull/3087 resolves it... at least for the production queue.

**Comment by geoffthemedio** [comment] 2020-07-04 10:16
Unless you indicate that the lockup issue with the popup on the production or research queue still occurs after #3087 then I'll close this...

**Closed as completed** 2020-07-22 11:24 UTC
Labels: category:bug, component:UI, status:resolved
