### ISSUE TITLE
Does not build with BUILD_HEADLESS

### ISSUE THREAD

**Issue by AMDmi3** [freeorion/freeorion#3125] opened 2020-07-28 12:19 UTC
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: 0.4.10
* **Operating System**: FreeBSD 12.1
* **Graphic card used**: -
* **Fetched as** 
  * Compiled from source

Description
-----------
Does not build when BUILD_HEADLESS is enabled:

```
-- Build type CMAKE_BUILD_TYPE set to Release
-- CCache version: 3.7.1
-- CCache configured for linux: /usr/local/bin/ccache
-- The C compiler identification is Clang 8.0.1
-- The CXX compiler identification is Clang 8.0.1
-- Check for working C compiler: /usr/local/libexec/ccache/cc
-- Check for working C compiler: /usr/local/libexec/ccache/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/libexec/ccache/c++
-- Check for working CXX compiler: /usr/local/libexec/ccache/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Use CCache for Ninja called with: ccache program /usr/local/bin/ccache 3.7.1
-- Performing Test NOT_GNU_CXX_BUG_94190
-- Performing Test NOT_GNU_CXX_BUG_94190 - Success
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Found Threads: TRUE
-- Found PythonInterp: /usr/local/bin/python3.7 (found suitable version "3.7.8", minimum required is "3.5")
-- Found PythonLibs: /usr/local/lib/libpython3.7m.so (found suitable version "3.7.8", minimum required is "3.5")
-- Boost 1.58.0 found.
-- Found Boost components:
   filesystem;iostreams;locale;log;log_setup;serialization;system;thread
-- Boost  found.
-- Found Boost components:
   python37
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.11")
-- Boost 1.58.0 found.
-- Found Boost components:
   filesystem;regex;system
CMake Warning (dev) at /usr/local/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args` (cppcheck)
  does not match the name of the calling package (CPPCheck).  This can lead
  to problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/FindCPPCheck.cmake:12 (find_package_handle_standard_args)
  check/CMakeLists.txt:1 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find cppcheck (missing: CPPCHECK_EXECUTABLE)
CMake Warning (dev) at /usr/local/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args`
  (pycodestyle) does not match the name of the calling package (PyCodestyle).
  This can lead to problems in calling code that expects `find_package`
  result variables (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/FindPyCodestyle.cmake:11 (find_package_handle_standard_args)
  check/CMakeLists.txt:2 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find pycodestyle (missing: PYCODESTYLE_EXECUTABLE)
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Configuring done
CMake Error at GG/CMakeLists.txt:117 (add_library):
  No SOURCES given to target: GiGi


CMake Generate step failed.  Build files cannot be regenerated correctly.
*** Error code 1

Stop.
``` 

Expected Result
---------------
Successful build

Steps to reproduce
------------------
* `cmake -DBUILD_HEADLESS=ON`

**Comment by geoffthemedio** [comment] 2020-08-12 18:13
Can you try with the latest master version of https://github.com/freeorion/freeorion/blob/master/CMakeLists.txt (or the latest commit https://github.com/freeorion/freeorion/commit/8c1f7ed1c390adf34b389f32e768e8181ab97d15) applied on top of v0.4.10 ?

If that helps, we can cherry pick that into the v0.4.10 branch for a bugfix release...

Otherwise apparently we can't reproduce the issue...

**Comment by AMDmi3** [comment] 2020-08-24 20:33
8c1f7ed builds fine, thanks!

**Comment by Vezzra** [comment] 2020-08-26 09:39
@geoffthemedio, @AMDmi3, so, that means if we cherry pick 8c1f7ed1c390adf34b389f32e768e8181ab97d15 to the release branch, the issue should be fixed, right? Should I go ahead with the cherry picking?

**Comment by geoffthemedio** [comment] 2020-08-26 09:43
> Should I go ahead with the cherry picking?

See: https://github.com/freeorion/freeorion/pull/3070

**Comment by Vezzra** [comment] 2020-08-26 09:48
Ah yes, thanks!

**Closed as completed** 2020-08-26 09:49 UTC
Labels: category:bug, component:build system, status:resolved
