### ISSUE TITLE
Pedia entries for Stockpiling techs & new building need update

### ISSUE THREAD

**Issue by Dilvish-fo** [freeorion/freeorion#2080] opened 2018-04-30 15:04 UTC
PR #2072 changed some stockpiling techs and added a building, but overlooked making corresponding changes to the Pedia entries in the stringtables.   So the descriptions for all 3 techs are looking incomplete and/or wrong to me, and the pedia entry for the building has a lookup error for its title and in the body.

**Comment by Vezzra** [comment] 2018-05-13 15:37
Has there been any progress on this, anyone working on it?

**Comment by agrrr3** [comment] 2018-05-16 07:30
Hi,

i probably can contribute something in the evening. Not sure i'll be able
to finish it though.

Regards

2018-05-13 17:37 GMT+02:00 Vezzra <notifications@github.com>:

**Comment by Vezzra** [comment] 2018-05-20 12:52
Quoting a statement of @agrrr3 in the comment section of #2109:

> What is not addressed: we are still missing the stringtable entries for BLD_STOCKPILING_CENTER, BLD_STOCKPILING_CENTER_LABEL, and for the accounting labels for Generic Supplies, INTERSTELLAR_ENTANGLEMENT_FACTORY_POPULATION_BONUS_LABEL, INTERSTELLAR_ENTANGLEMENT_FACTORY_FIXED_BONUS_LABEL.

Anyone correct me if I'm wrong, but looking at the stringtables I actually *do* find an entry for `BLD_STOCKPILING_CENTER` -> "Imperial Entanglement Center". So that should be taken care of already, right?

And concerning the missing accounting labels: do we really need them? As far as I can see, specifiying accounting labels in effectgroups is optional. If we just remove them, the name of the building/tech containing the effects should be used, or am I missing something?

So, assuming I'm correct, all that needs to be done to address the remaining parts of this issue would be remove the accounting labels `BLD_STOCKPILING_CENTER_LABEL`, `INTERSTELLAR_ENTANGLEMENT_FACTORY_POPULATION_BONUS_LABEL` and `INTERSTELLAR_ENTANGLEMENT_FACTORY_FIXED_BONUS_LABEL` - right?

**Comment by Dilvish-fo** [comment] 2018-05-20 17:56
> Anyone correct me if I'm wrong, but looking at the stringtables I actually do find an entry for BLD_STOCKPILING_CENTER -> "Imperial Entanglement Center". So that should be taken care of already, right?

Yes, it looks like you are right on that.   Although I rather think I had encountered an error on that ingame someplace, but perhaps that was just the label form for tooltips being missing, or perhaps I'm just remembering wrong, I'll look into that more.

**Comment by agrrr3** [comment] 2018-05-29 16:48
Just a note why added the labels - so users can see how the different effects (especially the population based bonus) add up

**Comment by Vezzra** [comment] 2018-05-31 12:05
@Dilvish-fo, #2115 has been merged, have all things in this issue here been addressed now, or is still something missing?

**Comment by Vezzra** [comment] 2018-06-01 14:35
> have all things in this issue here been addressed now, or is still something missing?

Apparently `BLD_STOCKPILING_CENTER_LABEL`, `INTERSTELLAR_ENTANGLEMENT_FACTORY_POPULATION_BONUS_LABEL` and `INTERSTELLAR_ENTANGLEMENT_FACTORY_FIXED_BONUS_LABEL` are still missing. I'll try to provide a PR for those.

> Just a note why added the labels - so users can see how the different effects (especially the population based bonus) add up

Well, that's ok, but in that case it would have been better if you also provided the corresponding stringtable entries. 😉

**Comment by Vezzra** [comment] 2018-06-01 15:00
>  I'll try to provide a PR for those.

PR is up: #2134. @Dilvish-fo, does that address all remaining issues, or is there still something missing?

**Comment by Vezzra** [comment] 2018-06-04 17:03
@Dilvish-fo, @agrrr3, #2134 has been merged (and cherry picked). Have all stringtable/pedia entries that need to be added/updated because of #2072 been addressed, or is there anything left to do? Can we close this?

**Comment by Dilvish-fo** [comment] 2018-06-04 21:53
It is my expectation that everything is resolved now, but I've been putting off responding here, hoping to  squeeze in the time for a thorough review.  I'm still not sure when that would wind up happening.  I wouldn't have any objection to going ahead and closing it.

**Comment by agrrr3** [comment] 2018-06-05 05:46
Same here. Didnt reply as the correct thing to do would be a review/check
the ui. What is probably off now is that some effects have multiple labels
(popdependent, fixed..) and some not. Also i dont know if the long
stringtable values work well in the ui

**Comment by Dilvish-fo** [comment] 2018-06-05 13:42
> What is probably off now is that some effects have multiple labels 
(popdependent, fixed..) and some not.

I wouldn't call those labels "off"-- they are really an artifact of the more-complex-than-typical details of the respective conten, I don't recall any other current content with that dual-pronged nature.  And we have already made intentional choices both about that content and about having the two labels.  The possibility that we might be expecting to continue assessing those decisions over time doesn't make them 'off', and I think it's pretty unlikely we'd change those decisions for 0.4.8

> Also i dont know if the long stringtable values work well in the ui

I had a bit of uncertainty there also, but I think they'll work out OK.  @Vezzra, had you already checked them ingame to be sure they don't get clipped?  I think that's unlikely but I suppose one of us should be sure to double check that no later than during RC1, and preferably post here once that's checked.

**Comment by Vezzra** [comment] 2018-06-06 11:54
I didn't have the time to run test games too, so I'm also relying (kind of blindely) on that the fixes for this issue that have gone in more or less work as intended.

To be able to move forward with this, I'm going to close this issue, and rely on the playtesting of the next pre-release builds and the release candidates afterwards. If some strings don't work, or we find other still missing stringtable/pedia entries, lets just open new issues for that.

**Closed as completed by Vezzra** 2018-06-06 11:54 UTC
Labels: category:bug, component:content scripting, status:resolved, component:art music text assets
