### ISSUE TITLE
Time-out on connecting to server for LoadSingleGame (OSX)

### ISSUE THREAD

**Issue by memem359** [freeorion/freeorion#1371] opened 2017-03-01 13:24 UTC
For the recent Mac OSX test build, I am unable to load saved games, as it times-out while trying to connect to the server. Starting a new game (with or without Quickstart) is fine. (This is also true for earlier test builds in February, but I don't know when it started.)

After some investigating, I believe this behavior is due to client/human/HumanClientApp.cpp
Specifically these 3 lines:
- Line 86: global variable for amount of time before a time out connecting to server
`    const unsigned int  SERVER_CONNECT_TIMEOUT = 4500; // in ms`
- Line 448: time between trying to connect to server for "New Game"
`    while (!m_networking.ConnectToLocalHostServer(boost::posix_time::seconds(2))) {`
- Line 660: default (no argument) time for "Load Game" is 5 seconds
`    while (!m_networking.ConnectToLocalHostServer()) {`

On my computer, it takes 1.8 seconds for the server to initialize and be ready for network connections.
- For New Game (normal), the human client waits 4 seconds after the server start, and then connects on 1st try.
- For New Game (quickstart), the human client tries to connect immediately after the server starts (but before it is ready). It fails to connect on the 1st try, but 2 seconds later connects on the 2nd try.
- For Load Game, the human client tries to connect immediately. It fails on the 1st try, and then times out before trying again.

## My Suggestion to the appropriate developer...
Change line 660 to be like line 448: add the 2 second argument to the ConnectToLocalHostServer call. This will let the LoadSinglePlayerGame try two more times to connect before the SERVER_CONECT_TIMEOUT, and it should succeed on the second try, which is after the 1.8 seconds for the server to initialize.

**Comment by Vezzra** [comment] 2017-03-19 14:38
Fixed by #1375.

**Closed as completed by Vezzra** 2017-03-19 14:38 UTC
Labels: category:bug, component:network, status:resolved

**Comment by calebjones** [comment] 2018-10-06 22:33
Error when time-out error appears:

```
2018-10-06 15:32:08.883 FreeOrion[72716:113884306] IMKClient Stall detected, *please Report* your user scenario attaching a spindump (or sysdiagnose) that captures the problem - (imkxpc_presentFunctionRowItemTextInputViewWithEndpoint:reply:) block performed very slowly (44.91 secs).
2018-10-06 15:32:08.886 FreeOrion[72716:113884306] IMKInputSession presentFunctionRowItemTextInputViewWithEndpoint:completionHandler: : [self textInputContext]=0x7f9531c59180 *NO* NSRemoteViewController to client, NSError=Error Domain=NSCocoaErrorDomain Code=4099 "The connection from pid 0 was invalidated from this process." UserInfo={NSDebugDescription=The connection from pid 0 was invalidated from this process.}, com.apple.inputmethod.EmojiFunctionRowItem
```

Also had it output:

```
2018-10-06 15:34:46.200 FreeOrion[72834:113901136] IMKClient Stall detected, *please Report* your user scenario attaching a spindump (or sysdiagnose) that captures the problem - (imkxpc_presentFunctionRowItemTextInputViewWithEndpoint:reply:) block performed very slowly (44.42 secs).
2018-10-06 15:34:46.201 FreeOrion[72834:113901136] IMKClient Stall detected, *please Report* your user scenario attaching a spindump (or sysdiagnose) that captures the problem - (imkxpc_presentFunctionRowItemTextInputViewWithEndpoint:reply:) block performed very slowly (30.08 secs).
2018-10-06 15:34:46.202 FreeOrion[72834:113901136] IMKClient Stall detected, *please Report* your user scenario attaching a spindump (or sysdiagnose) that captures the problem - (imkxpc_presentFunctionRowItemTextInputViewWithEndpoint:reply:) block performed very slowly (8.61 secs).
2018-10-06 15:34:46.203 FreeOrion[72834:113901136] IMKInputSession presentFunctionRowItemTextInputViewWithEndpoint:completionHandler: : [self textInputContext]=0x7fde8f966b20 *NO* NSRemoteViewController to client, NSError=Error Domain=NSCocoaErrorDomain Code=4099 "The connection from pid 0 was invalidated from this process." UserInfo={NSDebugDescription=The connection from pid 0 was invalidated from this process.}, com.apple.inputmethod.EmojiFunctionRowItem
2018-10-06 15:34:46.205 FreeOrion[72834:113901136] IMKInputSession presentFunctionRowItemTextInputViewWithEndpoint:completionHandler: : [self textInputContext]=0x7fde8f966b20 *NO* NSRemoteViewController to client, NSError=Error Domain=NSCocoaErrorDomain Code=4099 "The connection from pid 0 was invalidated from this process." UserInfo={NSDebugDescription=The connection from pid 0 was invalidated from this process.}, com.apple.inputmethod.EmojiFunctionRowItem
2018-10-06 15:34:46.205 FreeOrion[72834:113901136] IMKInputSession presentFunctionRowItemTextInputViewWithEndpoint:completionHandler: : [self textInputContext]=0x7fde8f966b20 *NO* NSRemoteViewController to client, NSError=Error Domain=NSCocoaErrorDomain Code=4099 "The connection from pid 0 was invalidated from this process." UserInfo={NSDebugDescription=The connection from pid 0 was invalidated from this process.}, com.apple.inputmethod.EmojiFunctionRowItem
```

**Comment by calebjones** [comment] 2018-10-07 15:57
Yes, my MBP has the new touchbar. It happens for any save file. I haven't tried different save formats. Here's an example save:

[free-orion-load-timeout.zip](https://github.com/freeorion/freeorion/files/2454060/free-orion-load-timeout.zip)

**Comment by calebjones** [comment] 2018-10-07 18:34
Some more testing today.

"Quick Start" encounters the same error. But "Continue" works fine (game is playable this way as I can pick up where I left off - but only for one game).

EDIT: Continue seems to only work some of the time.

**Comment by calebjones** [comment] 2018-10-08 16:41
More testing...

If I sit there and continuously click "Continue" or "Load Game" it will eventually load. But it's unpredictable and can take many tries.

Perhaps an increased or configurable timeout for how it loads and communicates the other process would help.

**Comment by Vezzra** [comment] 2018-10-09 12:03
I can load that save you provided without issues. From what you describe, this sounds like an issue that depends very  much on the current state of your system - which processes/background tasks/apps/whatever are running etc.

Without being able to reproduce the issue reliably there is not much we can do. (And even then, if it's only reproducible on Mac, there is the problem that none of our devs who are capable of looking into such an issue are on Mac.)

> Perhaps an increased or configurable timeout for how it loads and communicates the other process would help.

From what I've read, and judging by the logs you provided, the error occurs not in FO code, but somewhere in an OSX system library/framework. The error message is, AFAIK, not one of ours, but looks like an exception thrown by a system call. I've no idea what we could do, or how to work around what might be an OSX bug.

Would be interesting to know if the issue persists if you upgrade your system to High Sierra or Mojave...

Anyway, the problem you have seems to be something different from the original issue here, and should be handled by a separate issue. Can you open one and repost your bug report there?

What would also be very important is the complete log files after such a failed load attempt, together with all the error messages dumped on the command line (you know how to launch FO from the command line?).

A backtrace would also be nice, if you know how to use a debugger to get one.

Everything that could give us more info about how and where the error occurs could be helpful.
