### ISSUE TITLE
C++ debug code in AI logs

### ISSUE THREAD

**Issue by Cjkjvfnby** [freeorion/freeorion#735] opened 2016-06-26 13:36 UTC
This Information is redundant for AI logs.

`[debug] AI : v0.4.5+ [build 2016-06-21.94bf367] MSVC 2013`

```
[debug] AI : Universe::serialize : deserializing universe width: 1176.56
[debug] AI : Universe::serialize : deserializing 0 ship designs
[debug] AI : Universe::serialize : deserializing empire object visibility for 1, 1, 0, 0 empires
[debug] AI : Universe::serialize : deserializing 21 objects
[debug] AI : Universe::serialize : deserializing 0 destroyed object ids
[debug] AI : Universe::serialize : deserializing empire known objects for 0 empires
[debug] AI : Universe::serialize : deserializing last allocated ids
[debug] AI : Universe::serialize : deserializing 18 types of statistic
[debug] AI : Universe::serialize : deserializing done
[debug] AI : Universe::serialize : updating empires' latest known object destruction states
[debug] AI : Universe::serialize done
[debug] AI : Universe::serialize : deserializing universe width: 1176.56
[debug] AI : Universe::serialize : deserializing 0 ship designs
[debug] AI : Universe::serialize : deserializing empire object visibility for 1, 1, 1, 1 empires
[debug] AI : Universe::serialize : deserializing 21 objects
[debug] AI : Universe::serialize : deserializing 0 destroyed object ids
[debug] AI : Universe::serialize : deserializing empire known objects for 0 empires
[debug] AI : Universe::serialize : deserializing last allocated ids
[debug] AI : Universe::serialize : deserializing 18 types of statistic
[debug] AI : Universe::serialize : deserializing done
[debug] AI : Universe::serialize : updating empires' latest known object destruction states
[debug] AI : Universe::serialize done
```

**Comment by geoffthemedio** [comment] 2016-06-26 14:50
It would not be redundant in the event there was a failure in that code. In that case, seeing where / what is happening could be helpful.

**Comment by Vezzra** [comment] 2016-09-23 10:27
@Cjkjvfnby, @geoffthemedio: considering the reason @geoffthemedio gave why we probably should leave things as they are, shall we close this as wontfix, or do you guys want to do anything to adjust/improve the issue?

**Comment by Cjkjvfnby** [comment] 2016-09-28 00:13
@geoffthemedio, where and what is happenning should be in error message, not in logs.  If it require a lot of work, then `wontfix` is OK

**Comment by adrianbroher** [comment] 2016-09-28 07:07
> C++ debug code in AI logs

I don't get your point.  The 'AI' logs are not exclusively for python code, but for one of the `freeorionca` processes.

> This Information is redundant for AI logs.

It's processed in the context of `freeorionca` so it's not redundant.  The statements you posted for example are not redundant either, because it's two different deserializing operations (but I'm not sure because a context like wall-clock time or a turn identifier is missing).

> @geoffthemedio, where and what is happenning should be in error message, not in logs.

No idea what you mean.  What are error messages?  Why should the message (what) or the context (where) not in the log file?

**Comment by Cjkjvfnby** [comment] 2016-09-28 22:50
> I don't get your point. The 'AI' logs are not exclusively for python code, but for one of the freeorionca processes.

This logs not looks like part of AI.   This information is not useful for me them I inspect AI behavior via log.

> No idea what you mean. What are error messages? Why should the message (what) or the context (where) not in the log file?

It is related to https://github.com/freeorion/freeorion/issues/735#issuecomment-228604916. Using debug print to check where exception is happens looks wired for me. In case of error this information should be printed by error handler to log.

**Comment by geoffthemedio** [comment] 2016-09-28 23:08
@Cjkjvfnby The logs are for the whole AI process, not just for AI decision-making code in Python. It also logs stuff happening in C++ code. This is by design.

**Comment by Vezzra** [comment] 2016-09-30 21:22
So, can/shall we close this as "wontfix"?

**Comment by Morlic-fo** [comment] 2016-10-01 14:39
I guess same holds for #521 ?

**Comment by Vezzra** [comment] 2016-10-02 01:42
IMO not exactly. #521 is about log messages related to one AI appearing in the log file of another AI, which is a different matter.

**Closed as completed** 2016-10-07 00:22 UTC
Labels: category:bug, status:won't fix, component:AI
