### ISSUE TITLE
Industry and research bonuses do not match their description in translations

### ISSUE THREAD

**Issue by Cjkjvfnby** [freeorion/freeorion#2954] opened 2020-05-17 09:02 UTC
After rework of the industrial and research bonuses, en.txt were nefred.

Other translation contains incorrect buildings descriptions.
https://github.com/freeorion/freeorion/pull/2953

@Vezzra this should be fixed before release.
@Oberlus keep in mind that most of the translations are not maintained on a regular basis.

**Comment by Vezzra** [comment] 2020-05-17 11:40
I agree, actively maintained translations like French and Russian should get an update to incorporate all changes to the English stringtable before the release.

However, in the case of PRs like #2943 I'm more concerned with how the AI is affected and what updates are required for the AI to be able to handle the new numbers (which is why I, personally, would have merged that PR post release, btw).

**Comment by Oberlus** [comment] 2020-05-17 12:08
> However, in the case of PRs like #2943 I'm more concerned with how the AI is affected and what updates are required for the AI to be able to handle the new numbers (which is why I, personally, would have merged that PR post release, btw).

In my experience playing against AI, it tends to delay for too long techs like Quantum Networking (and the rest OP late-game techs), that caused sharp increases in the output graph. #2943, by nerfing those techs, could cause an improvement on overall AI performance, without any modifications in the AI code.
I'm worried, though, about AA and NAI, which AI also tends to delay too much, because now they are even more important.

I can make a PR [nerfing those two techs](https://www.freeorion.org/forum/viewtopic.php?f=6&t=11040&p=101714#p101703). Also, adding two refinements for them would be great, but that would certainly need AI adjustments for it to ever research the refinements.

**Comment by agrrr3** [comment] 2020-05-17 12:26
> However, in the case of PRs like #2943 I'm more concerned with how the AI is affected and what updates are required for the AI to be able to handle the new numbers 

@Oberlus I also forget about this, but most of the times when I change content, I have to do this in at least three places: default/scripting/.., stringtables/en.txt and python/AI/AIDependencies.py

And AIDependencies.py is definitely out of sync, I will open an issue.

> which is why I, personally, would have merged that PR post release

@vezzra Cant you tag the PRs post-release, please? People change and break a lot at the moment which should not happen in ramp-down.

**Comment by Vezzra** [comment] 2020-05-17 12:43
@agrrr3,

> Cant you tag the PRs post-release, please? People change and break a lot at the moment which should not happen in ramp-down.

The problem is, given the limited amount of time I have for FO stuff, I haven't been able to keep track of the ongoing development as closely as I've been used to. I still manage to follow the "big picture", so to speak, but I have long ago given up to follow the finer details.

Which means it's very difficult for me to make proper assessments concerning which issues/PRs should be included in an upcoming release and which should be postponed. I need to rely on the common sense of my fellow devs regarding this.

So, I can only appeal once again to all of you guys actively contributing, please focus your efforts on fixing and polishing things instead of trying to get as much new stuff into master as you can before the release. That really doesn't help with getting out the release, which is/was supposed to be a quick one (to get Python3 support out).

**Comment by Vezzra** [comment] 2020-05-17 12:45
> And AIDependencies.py is definitely out of sync, I will open an issue.

Yes, please do! 👍

**Comment by adrianbroher** [comment] 2020-05-17 12:45
> So, I can only appeal once again to all of you guys actively contributing, please focus your efforts on fixing and polishing things instead of trying to get as much new stuff into master as you can before the release.

Then create a release branch.

**Comment by Vezzra** [comment] 2020-05-17 12:56
> Then create a release branch.

Which I intend to do, I just want to have all major bug fixes in and release-blocking issues resolved, to keep the cherry-picking to a minimum.

I know from experience, that creating a release branch only alleviates all these issues and troubles so much. Because it does not prevent people from wanting to get their favorite features/changes into the release, which means as soon as I create the release branch, requests to cherry pick this and that start to trickle in, and then I have to deal with that (even if "dealing with that" means formulating proper replies why "this and that" won't be approved for inclusion :wink:)

But you're right, at some point I'll just have to draw the line, and if possible I want to do that coming Sunday. I'm going to make a post regarding this on the forum, in the [0.4.10 release thread](https://freeorion.org/forum/viewtopic.php?f=4&t=11579).

**Closed as completed** 2020-05-17 13:33 UTC
Labels: category:bug, component:translation

**Comment by geoffthemedio** [comment] 2020-05-17 13:37
> which is why I, personally, would have merged that PR post release

Unfortunately (or not?) I didn't notice the milestone tag before merging when looking at it today. Sounds like it's not expected to be a major problem in this particular case, though.

**Comment by Vezzra** [comment] 2020-05-17 13:44
Well, it has it's up side - after all, this PR tries to address something that has been a quite pressing issue for a very long time. And the changes introduced actually do need a lot of playtesting.

I'm mostly concerned about degraded AI performance.
